#!/usr/bin/env python3
"""Geometry parity + safety matrix for the SANE A+C production ledger
(docs/holder-position-design.md; the Test 58/61 migration).

sane/gl126_tables.h now carries a frozen `FrameGeom frames[6]` per
`Profile`, generated by tools/gen_sane_tables.frame_geom_entries() from
of135i/holder.py's overscan_geometry()/dual_overscan_geometry() (the same
Python authority the CLI driver positions from). sane/gl126_ops.cpp's
feedl_for_frame(frame, profile) and frame_geometry(profile, frame) read
that ledger at runtime (see tests/test_sane_ops.py's
test_position_and_scan_setup_match_python_replayer and
test_feedl_and_position_budget for the wire-level oracle; this file is
the pure-computation oracle: does the frozen C++ table -- and the C++
functions that read it -- agree with the SAME Python calls the generator
used, exactly, for every profile and every frame).

  1. test_frame_geom_matches_generator -- for every profile x frame 1-6,
     the six FrameGeom fields the generator emitted (parsed straight out
     of sane/gl126_tables.cpp) equal frame_geom_entries()'s own output,
     exact integer equality, no tolerance.
  2. test_frame_geom_safety_bounds -- feedl and end_hwdpi never exceed
     FEEDL_CEILING; a dual profile's line_register is even (the wire
     parity dual_overscan_geometry() constructs by design); delivered_
     lines and chunks are always positive; the proven invariant
     (delivered + 2*align_shift == read_lines, or read_lines/2 for dual)
     holds for every entry.
  3. test_frame_bounds_enforced_before_any_write -- frame 0 and frame 7
     are refused, before any transfer: the C++ probe (feedl_for_frame()
     and frame_geometry(), both via gl126_ops_probe.cpp) and the Python
     authority (holder.check_frame()) agree.

Run with:
    .venv/bin/python tests/test_sane_geometry.py

Requires a C++ compiler (g++) on PATH for the parity/bounds probe calls;
if none is found, those tests print a SKIP line and pass trivially (the
same convention as tests/test_sane_ops.py). The generator-vs-table check
(1) needs no compiler and always runs.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(REPO / "tools"))

from of135i import image as _image  # noqa: E402
from of135i import holder  # noqa: E402
from of135i import tables  # noqa: E402

import gen_sane_tables as gen  # noqa: E402
from test_sane_ops import _build_probe, DUAL_PROFILES, _dual_module  # noqa: E402

GL126_TABLES_CPP = REPO / "sane" / "gl126_tables.cpp"

ALL_PROFILES = (("plain3600", tables, 3600),) + tuple(
    (name, _dual_module(dpi), dpi) for name, dpi in DUAL_PROFILES
)

FIELDS = ("feedl", "line_register", "read_lines", "delivered_lines", "chunks", "end_hwdpi")

_FRAMES_ARRAY_RE = re.compile(
    r"static const FrameGeom (\w+)_FRAMES\[6\] = \{(.*?)\};", re.DOTALL)
_ENTRY_RE = re.compile(
    r"\{(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\}")


def _parse_generated_frames() -> dict[str, list[dict[str, int]]]:
    """Every `<KEY>_FRAMES[6]` array in sane/gl126_tables.cpp, keyed by
    the profile name lowercased (PLAIN3600 -> plain3600), each a list of
    6 dicts (frame 1..6) with the same field names frame_geom_entries()
    returns."""
    src = GL126_TABLES_CPP.read_text()
    out: dict[str, list[dict[str, int]]] = {}
    for m in _FRAMES_ARRAY_RE.finditer(src):
        key = m.group(1).lower()
        entries = _ENTRY_RE.findall(m.group(2))
        assert len(entries) == 6, (key, len(entries))
        out[key] = [dict(zip(FIELDS, (int(v) for v in vals))) for vals in entries]
    return out


def test_frame_geom_matches_generator():
    """The frozen table (sane/gl126_tables.cpp) equals
    tools.gen_sane_tables.frame_geom_entries()'s own output, exactly, for
    every profile x frame 1-6 -- the single-source-bridge invariant
    frame_geom_entries()'s own docstring promises."""
    parsed = _parse_generated_frames()
    checked = 0
    for name, mod, dpi in ALL_PROFILES:
        assert name in parsed, (name, sorted(parsed))
        want = gen.frame_geom_entries(name, mod, dpi)
        assert len(want) == 6, (name, len(want))
        for frame in range(1, 7):
            got = parsed[name][frame - 1]
            w = want[frame - 1]
            for field in FIELDS:
                assert got[field] == w[field], (
                    f"{name} frame {frame} field {field}: table has {got[field]}, "
                    f"frame_geom_entries() has {w[field]}")
            checked += 1
    assert checked == 6 * len(ALL_PROFILES), checked
    # Spelled out, not just cross-checked (docs/holder-position-design.md,
    # PLAIN3600_FRAMES's own example): plain3600's six FEEDL targets.
    plain = parsed["plain3600"]
    assert [f["feedl"] for f in plain] == [6562, 17315, 28051, 38806, 49538, 60276], plain
    assert plain[0] == {"feedl": 6562, "line_register": 5367, "read_lines": 5359,
                        "delivered_lines": 5335, "chunks": 233, "end_hwdpi": 11897}, plain[0]
    print(f"test_frame_geom_matches_generator OK ({checked} profile x frame entries, "
          f"{len(ALL_PROFILES)} profiles)")


def test_frame_geom_safety_bounds():
    """Every frozen entry: feedl and end_hwdpi within FEEDL_CEILING, a
    dual profile's line_register even (wire parity), delivered_lines and
    chunks positive, and the proven invariant delivered + 2*align_shift
    == read_lines (plain) / == read_lines/2 (dual)."""
    parsed = _parse_generated_frames()
    checked = 0
    for name, _mod, dpi in ALL_PROFILES:
        dual = name != "plain3600"
        crop = _image.align_shift(dpi)
        for frame, e in enumerate(parsed[name], start=1):
            assert e["feedl"] <= holder.FEEDL_CEILING, (name, frame, e)
            assert e["end_hwdpi"] <= holder.FEEDL_CEILING, (name, frame, e)
            assert e["feedl"] <= e["end_hwdpi"], (name, frame, e)
            if dual:
                assert e["line_register"] % 2 == 0, (name, frame, e)
                assert e["delivered_lines"] + 2 * crop == e["read_lines"] // 2, (name, frame, e)
            else:
                assert e["delivered_lines"] + 2 * crop == e["read_lines"], (name, frame, e)
            assert e["delivered_lines"] > 0, (name, frame, e)
            assert e["chunks"] > 0, (name, frame, e)
            checked += 1
    assert checked == 6 * len(ALL_PROFILES), checked
    print(f"test_frame_geom_safety_bounds OK ({checked} entries: ceiling, parity, "
          f"positivity, delivered+2*align_shift invariant)")


def test_frame_bounds_enforced_before_any_write():
    """Frame 0 and frame 7 (outside the six-aperture holder) are refused
    before any transfer -- both C++ entry points that index frames[]
    (feedl_for_frame(frame, profile) and frame_geometry(profile, frame),
    via gl126_ops_probe.cpp) and the Python authority
    (holder.check_frame(), which of135i/holder.py's own
    overscan_geometry()/dual_overscan_geometry() call before computing
    anything). 1 and 6 are accepted by all three."""
    for frame in (0, 7):
        try:
            holder.check_frame(frame)
        except Exception as e:  # holder.safety.FrameOutOfRangeError
            assert "outside" in str(e), (frame, e)
        else:
            raise AssertionError(f"holder.check_frame({frame}) did not raise")
    for frame in (1, 6):
        assert holder.check_frame(frame) == frame

    probe = _build_probe()
    if probe is None:
        print("test_frame_bounds_enforced_before_any_write OK (Python bound only; "
              "C++ probe SKIPPED, no g++)")
        return "skipped"

    for frame in (0, 7):
        r = subprocess.run([str(probe), "feedl", str(frame), "plain3600"],
                           capture_output=True, text=True)
        assert r.returncode == 2, (frame, r.stdout, r.stderr)
        assert "outside 1-6" in r.stderr, (frame, r.stderr)
        r2 = subprocess.run([str(probe), "geometry", "plain3600", str(frame)],
                            capture_output=True, text=True)
        assert r2.returncode == 2, (frame, r2.stdout, r2.stderr)
        assert "outside 1-6" in r2.stderr, (frame, r2.stderr)
    for frame in (1, 6):
        r = subprocess.run([str(probe), "feedl", str(frame), "plain3600"],
                           capture_output=True, text=True)
        assert r.returncode == 0, (frame, r.stdout, r.stderr)
        r2 = subprocess.run([str(probe), "geometry", "plain3600", str(frame)],
                            capture_output=True, text=True)
        assert r2.returncode == 0, (frame, r2.stdout, r2.stderr)
    print("test_frame_bounds_enforced_before_any_write OK "
          "(feedl_for_frame + frame_geometry + holder.check_frame agree)")


GL126_CPP = REPO / "sane" / "gl126.cpp"
GL126_OPS_H = REPO / "sane" / "gl126_ops.h"
GL126_H = REPO / "sane" / "gl126.h"
PATCH = REPO / "sane" / "gl126-integration.patch"


def _function_body(signature: str, end_marker: str = "\nvoid ") -> str:
    """The source text of one gl126.cpp function, from its signature to
    the next definition."""
    src = GL126_CPP.read_text()
    start = src.index(signature)
    nxt = src.index(end_marker, start + len(signature))
    return src[start:nxt]


def _offset_calibration_body() -> str:
    """The source text of CommandSetGl126::offset_calibration (up to the
    next member definition) -- the FIRST GL126 hook that writes."""
    return _function_body("void CommandSetGl126::offset_calibration(",
                          "\nvoid CommandSetGl126::")


def _validate_scan_request_body() -> str:
    """The source text of validate_scan_request() -- the write-free
    refusal set both writing entry points share."""
    return _function_body("const Profile* validate_scan_request(")


def _magazine_load_body() -> str:
    """The source text of magazine_load_if_pending() -- the load half,
    which since WP-4 runs BEFORE calibration and moves the magazine."""
    return _function_body("void magazine_load_if_pending(")


def test_offset_calibration_preflight_precedes_any_io():
    """The 'before first write' guarantee at the internal path (Astra
    review 2026-09-10): in offset_calibration (the first hook that
    writes), the geometry preflight -- the 1-kFrameMax frame check,
    feedl_for_frame(frame, profile) and frame_geometry(profile, frame) --
    precedes check_start_state()'s read AND the first write
    (write_table(dev, BASE_INIT...)). And the two functions it calls are
    pure (their gl126_ops.h signatures take only a frame and a Profile --
    no Genesys_Device, no Wire, no interface), so the preflight cannot
    itself do I/O: an out-of-range frame or a window past the travel
    ceiling throws before any transfer. This is the source-order proof of
    zero-writes-on-invalid-frame at the real hook; the runtime probe/holder
    checks above prove the throw itself.

    (A live genesys-testsuite test that constructs a Genesys_Device with a
    fake IUsbDevice and calls offset_calibration was assessed and judged
    disproportionate: gl126 writes go through its own UsbWire ->
    dev->interface->get_usb_device(), no testsuite precedent constructs a
    device+interface+hook, and the preflight is pure-and-first so
    zero-writes holds by construction. See the Astra report.)"""
    # The preflight itself now lives in validate_scan_request() (WP-4:
    # the magazine's load half needs the SAME refusals, and it runs
    # EARLIER than calibration -- see the companion test below). What
    # this test pins is unchanged: the whole refusal set precedes the
    # first device read and the first write, at the first hook that
    # writes.
    preflight = _validate_scan_request_body()
    for needle in ("frame < 1 || frame > kFrameMax",
                   "feedl_for_frame(frame",
                   "frame_geometry(*profile, frame)"):
        assert needle in preflight, (needle, "missing from validate_scan_request")
    # And it is write-free by construction: no device I/O in its body.
    for banned in ("interface->", "check_start_state", "write_table",
                   "run_program", "run_phase_program"):
        assert banned not in preflight, (banned, "validate_scan_request must not do I/O")

    body = _offset_calibration_body()
    i_validate = body.index("validate_scan_request(dev)")
    i_state = body.index("check_start_state(dev)")   # first device read
    i_write = body.index("write_table(dev, BASE_INIT")  # first device write

    assert i_validate < i_state, ("preflight must precede the state read",
                                  i_validate, i_state)
    assert i_validate < i_write, ("preflight must precede the first write",
                                  i_validate, i_write)
    assert i_state < i_write, (i_state, i_write)

    ops_h = GL126_OPS_H.read_text()
    # Pure signatures: frame + Profile only, no device/Wire/interface.
    assert "feedl_for_frame(unsigned frame, const Profile& profile)" in ops_h, ops_h[:0]
    assert "frame_geometry(const Profile& profile, unsigned frame)" in ops_h
    for banned in ("Genesys_Device", "Wire", "interface"):
        # neither declaration line may mention a device/wire type
        for line in ops_h.splitlines():
            if "feedl_for_frame(" in line or "frame_geometry(" in line:
                assert banned not in line, (line, banned)
    print("test_offset_calibration_preflight_precedes_any_io OK "
          "(validate_scan_request precedes the state read and BASE_INIT; "
          "its own body does no I/O; feedl_for_frame/frame_geometry are pure)")


def test_magazine_load_validates_the_request_before_moving_anything():
    """WP-4 moved the first thing that touches the transport EARLIER than
    calibration: the core calls load_document() before
    genesys_scanner_calibration(), and the load half drives the loader
    motor. The scan request's write-free refusals therefore have to run
    there too -- otherwise an impossible request (a frame past the
    holder's six apertures, an unsupported colour mode) would move the
    magazine and only then be refused (Astra review 2026-09-13).

    Source order, like the offset-calibration test above: once a load is
    known to be pending, validate_scan_request() precedes the first
    register read and the load program. The runtime proof that the
    refusal actually happens, with the mark kept, is
    tests/test_sane_magazine.py."""
    body = _magazine_load_body()

    i_pending = body.index("if (!pending) {")            # the early return
    i_validate = body.index("validate_scan_request(dev)")
    i_read = body.index("read_register(REG_0x01)")       # first device read
    i_run = body.index('run_magazine_program(dev, "load"')  # the motor move

    assert i_pending < i_validate, ("no validation when nothing is pending",
                                    i_pending, i_validate)
    assert i_validate < i_read, ("validation must precede the first read",
                                 i_validate, i_read)
    assert i_validate < i_run, ("validation must precede the load program",
                                i_validate, i_run)
    print("test_magazine_load_validates_the_request_before_moving_anything OK "
          "(validate_scan_request precedes the first read and the load program)")


def test_public_frame_option_constraint_is_1_to_6():
    """The 'before first write' guarantee at the PUBLIC path: the SANE
    frontend enforces OPT_FRAME's constraint before any backend hook runs,
    so `scanimage --frame 0` / `--frame 7` are rejected without a single
    transfer. The integration patch declares gl126_frame_range = [1,
    kFrameMax] and binds it to OPT_FRAME as a SANE_CONSTRAINT_RANGE;
    kFrameMax is 6."""
    patch = PATCH.read_text()
    assert "static const SANE_Range gl126_frame_range" in patch
    m = re.search(r"gl126_frame_range\s*=\s*\{.*?1,.*?gl126::kFrameMax",
                  patch, re.DOTALL)
    assert m, "gl126_frame_range must run [1, kFrameMax]"
    assert "OPT_FRAME].constraint_type = SANE_CONSTRAINT_RANGE" in patch
    assert "OPT_FRAME].constraint.range = &gl126_frame_range" in patch
    assert "kFrameMax = 6" in GL126_H.read_text()
    print("test_public_frame_option_constraint_is_1_to_6 OK "
          "(OPT_FRAME SANE_CONSTRAINT_RANGE [1,6]; scanimage rejects 0/7 "
          "before any hook)")


def main() -> int:
    tests = [
        test_frame_geom_matches_generator,
        test_frame_geom_safety_bounds,
        test_frame_bounds_enforced_before_any_write,
        test_offset_calibration_preflight_precedes_any_io,
        test_magazine_load_validates_the_request_before_moving_anything,
        test_public_frame_option_constraint_is_1_to_6,
    ]
    passed = 0
    skipped = 0
    for t in tests:
        result = t()
        if result == "skipped":
            skipped += 1
        else:
            passed += 1
    if skipped:
        print(f"\n{passed} tests passed, {skipped} skipped.")
    else:
        print(f"\n{passed} tests passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
