#!/usr/bin/env python3
"""Geometry parity + safety matrix for the SANE A+C production ledger
(docs/holder-position-design.md; the Test 58/61 migration).

sane/gl126_tables.h now carries a frozen `FrameGeom frames[6]` per
`Profile`, generated by tools/gen_sane_tables.frame_geom_entries() from
of135i/holder.py's overscan_geometry()/dual_overscan_geometry() (the same
Python authority the CLI driver positions from). sane/gl126_ops.cpp's
feedl_for_frame(frame, profile) and frame_geometry(profile, frame) read
that ledger at runtime (see tests/test_sane_ops.py's
test_position_and_scan_setup_match_python_replayer and
test_feedl_and_position_budget for the wire-level oracle; this file is
the pure-computation oracle: does the frozen C++ table -- and the C++
functions that read it -- agree with the SAME Python calls the generator
used, exactly, for every profile and every frame).

  1. test_frame_geom_matches_generator -- for every profile x frame 1-6,
     the six FrameGeom fields the generator emitted (parsed straight out
     of sane/gl126_tables.cpp) equal frame_geom_entries()'s own output,
     exact integer equality, no tolerance.
  2. test_frame_geom_safety_bounds -- feedl and end_hwdpi never exceed
     FEEDL_CEILING; a dual profile's line_register is even (the wire
     parity dual_overscan_geometry() constructs by design); delivered_
     lines and chunks are always positive; the proven invariant
     (delivered + 2*align_shift == read_lines, or read_lines/2 for dual)
     holds for every entry.
  3. test_frame_bounds_enforced_before_any_write -- frame 0 and frame 7
     are refused, before any transfer: the C++ probe (feedl_for_frame()
     and frame_geometry(), both via gl126_ops_probe.cpp) and the Python
     authority (holder.check_frame()) agree.

Run with:
    .venv/bin/python tests/test_sane_geometry.py

Requires a C++ compiler (g++) on PATH for the parity/bounds probe calls;
if none is found, those tests print a SKIP line and pass trivially (the
same convention as tests/test_sane_ops.py). The generator-vs-table check
(1) needs no compiler and always runs.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(REPO / "tools"))

from of135i import image as _image  # noqa: E402
from of135i import holder  # noqa: E402
from of135i import tables  # noqa: E402

import gen_sane_tables as gen  # noqa: E402
from test_sane_ops import _build_probe, DUAL_PROFILES, _dual_module  # noqa: E402

GL126_TABLES_CPP = REPO / "sane" / "gl126_tables.cpp"

ALL_PROFILES = (("plain3600", tables, 3600),) + tuple(
    (name, _dual_module(dpi), dpi) for name, dpi in DUAL_PROFILES
)

FIELDS = ("feedl", "line_register", "read_lines", "delivered_lines", "chunks", "end_hwdpi")

_FRAMES_ARRAY_RE = re.compile(
    r"static const FrameGeom (\w+)_FRAMES\[6\] = \{(.*?)\};", re.DOTALL)
_ENTRY_RE = re.compile(
    r"\{(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+),\s*(\d+)\}")


def _parse_generated_frames() -> dict[str, list[dict[str, int]]]:
    """Every `<KEY>_FRAMES[6]` array in sane/gl126_tables.cpp, keyed by
    the profile name lowercased (PLAIN3600 -> plain3600), each a list of
    6 dicts (frame 1..6) with the same field names frame_geom_entries()
    returns."""
    src = GL126_TABLES_CPP.read_text()
    out: dict[str, list[dict[str, int]]] = {}
    for m in _FRAMES_ARRAY_RE.finditer(src):
        key = m.group(1).lower()
        entries = _ENTRY_RE.findall(m.group(2))
        assert len(entries) == 6, (key, len(entries))
        out[key] = [dict(zip(FIELDS, (int(v) for v in vals))) for vals in entries]
    return out


def test_frame_geom_matches_generator():
    """The frozen table (sane/gl126_tables.cpp) equals
    tools.gen_sane_tables.frame_geom_entries()'s own output, exactly, for
    every profile x frame 1-6 -- the single-source-bridge invariant
    frame_geom_entries()'s own docstring promises."""
    parsed = _parse_generated_frames()
    checked = 0
    for name, mod, dpi in ALL_PROFILES:
        assert name in parsed, (name, sorted(parsed))
        want = gen.frame_geom_entries(name, mod, dpi)
        assert len(want) == 6, (name, len(want))
        for frame in range(1, 7):
            got = parsed[name][frame - 1]
            w = want[frame - 1]
            for field in FIELDS:
                assert got[field] == w[field], (
                    f"{name} frame {frame} field {field}: table has {got[field]}, "
                    f"frame_geom_entries() has {w[field]}")
            checked += 1
    assert checked == 6 * len(ALL_PROFILES), checked
    # Spelled out, not just cross-checked (docs/holder-position-design.md,
    # PLAIN3600_FRAMES's own example): plain3600's six FEEDL targets.
    plain = parsed["plain3600"]
    assert [f["feedl"] for f in plain] == [6562, 17315, 28051, 38806, 49538, 60276], plain
    assert plain[0] == {"feedl": 6562, "line_register": 5367, "read_lines": 5359,
                        "delivered_lines": 5335, "chunks": 233, "end_hwdpi": 11897}, plain[0]
    print(f"test_frame_geom_matches_generator OK ({checked} profile x frame entries, "
          f"{len(ALL_PROFILES)} profiles)")


def test_frame_geom_safety_bounds():
    """Every frozen entry: feedl and end_hwdpi within FEEDL_CEILING, a
    dual profile's line_register even (wire parity), delivered_lines and
    chunks positive, and the proven invariant delivered + 2*align_shift
    == read_lines (plain) / == read_lines/2 (dual)."""
    parsed = _parse_generated_frames()
    checked = 0
    for name, _mod, dpi in ALL_PROFILES:
        dual = name != "plain3600"
        crop = _image.align_shift(dpi)
        for frame, e in enumerate(parsed[name], start=1):
            assert e["feedl"] <= holder.FEEDL_CEILING, (name, frame, e)
            assert e["end_hwdpi"] <= holder.FEEDL_CEILING, (name, frame, e)
            assert e["feedl"] <= e["end_hwdpi"], (name, frame, e)
            if dual:
                assert e["line_register"] % 2 == 0, (name, frame, e)
                assert e["delivered_lines"] + 2 * crop == e["read_lines"] // 2, (name, frame, e)
            else:
                assert e["delivered_lines"] + 2 * crop == e["read_lines"], (name, frame, e)
            assert e["delivered_lines"] > 0, (name, frame, e)
            assert e["chunks"] > 0, (name, frame, e)
            checked += 1
    assert checked == 6 * len(ALL_PROFILES), checked
    print(f"test_frame_geom_safety_bounds OK ({checked} entries: ceiling, parity, "
          f"positivity, delivered+2*align_shift invariant)")


def test_frame_bounds_enforced_before_any_write():
    """Frame 0 and frame 7 (outside the six-aperture holder) are refused
    before any transfer -- both C++ entry points that index frames[]
    (feedl_for_frame(frame, profile) and frame_geometry(profile, frame),
    via gl126_ops_probe.cpp) and the Python authority
    (holder.check_frame(), which of135i/holder.py's own
    overscan_geometry()/dual_overscan_geometry() call before computing
    anything). 1 and 6 are accepted by all three."""
    for frame in (0, 7):
        try:
            holder.check_frame(frame)
        except Exception as e:  # holder.safety.FrameOutOfRangeError
            assert "outside" in str(e), (frame, e)
        else:
            raise AssertionError(f"holder.check_frame({frame}) did not raise")
    for frame in (1, 6):
        assert holder.check_frame(frame) == frame

    probe = _build_probe()
    if probe is None:
        print("test_frame_bounds_enforced_before_any_write OK (Python bound only; "
              "C++ probe SKIPPED, no g++)")
        return "skipped"

    for frame in (0, 7):
        r = subprocess.run([str(probe), "feedl", str(frame), "plain3600"],
                           capture_output=True, text=True)
        assert r.returncode == 2, (frame, r.stdout, r.stderr)
        assert "outside 1-6" in r.stderr, (frame, r.stderr)
        r2 = subprocess.run([str(probe), "geometry", "plain3600", str(frame)],
                            capture_output=True, text=True)
        assert r2.returncode == 2, (frame, r2.stdout, r2.stderr)
        assert "outside 1-6" in r2.stderr, (frame, r2.stderr)
    for frame in (1, 6):
        r = subprocess.run([str(probe), "feedl", str(frame), "plain3600"],
                           capture_output=True, text=True)
        assert r.returncode == 0, (frame, r.stdout, r.stderr)
        r2 = subprocess.run([str(probe), "geometry", "plain3600", str(frame)],
                            capture_output=True, text=True)
        assert r2.returncode == 0, (frame, r2.stdout, r2.stderr)
    print("test_frame_bounds_enforced_before_any_write OK "
          "(feedl_for_frame + frame_geometry + holder.check_frame agree)")


def main() -> int:
    tests = [
        test_frame_geom_matches_generator,
        test_frame_geom_safety_bounds,
        test_frame_bounds_enforced_before_any_write,
    ]
    passed = 0
    skipped = 0
    for t in tests:
        result = t()
        if result == "skipped":
            skipped += 1
        else:
            passed += 1
    if skipped:
        print(f"\n{passed} tests passed, {skipped} skipped.")
    else:
        print(f"\n{passed} tests passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
