"""Vendor magazine JOG and LOAD sequences for the of135i driver.

AUTO-GENERATED by tools/gen_load_table.py from
traces/20260905-vendor-clean-load.trace.json.gz -- do not edit by hand.

OPEN (ops 37-88): the vendor's device-open sequence -- chip-id ack,
app-start register table (mode 0x78, LOADER motor profile 0x7e/0x7f
= 0x75/0x30), end-of-access acks, AFE enable, EEPROM reads, AFE reset
and AFE base values. The register context of the jog and the load;
replayed by Scanner.initialize(prep=False) instead of BASE_INIT_PAIRS
(whose scan motor profile made the jog's first move run at scan
speed, Test 16).

JOG (ops 88-170): the vendor's app-start jog -- interrupt/sensor
acks, feed 6690, 0x35=0xbb, feed 6690, eject 3090 -- run after the
OPEN sequence with the magazine loose in the slot. Every
vendor load that engaged the cassette was preceded by it; every
load of ours that did not engage lacked it (Tests 11b-15). Its
three completions read 0xf855 (done, loader-sensor bit SET).
Replayed by Scanner.jog_magazine().

LOAD (ops 194-260): after the operator took the magazine fully out
and reinserted it to the stop -- loader-sensor ack (reg 0x32), the
engaging feed (mode 0x18, FEEDL 0x1a22) with the vendor's full
register block (four batches, 126 registers incl. 0x01=0x22,
0x03=0x30, 0x15=0x90, 0x35=0xbb), loader slope tables and GO, the
slow prescan traverse (mode 0x1c, FEEDL 71490) and the first idle
housekeeping cycle. Completions 0xf455 (sensor CLEAR: cassette
pulled past the sensor) and 0xdc55. Replayed by
Scanner.load_magazine().

Both run with the same executor semantics as every other phase
(device.py _exec_ops), behind the start-state guard (safety.py);
the motor completions use the masked test device.load_status_
matches (state class AND loader-sensor bit 0x08), not an exact
status word. The JOG + reinsert + LOAD flow is NOT yet hardware-
verified (Test 15 ran LOAD without the jog: feed done, sensor bit
still set, magazine loose).
"""

from __future__ import annotations

from .tables import Op, Phase

OPEN_OP_RANGE = (37, 88)

OPEN = Phase(
    name="open",
    op_range=(37, 88),
    ops=[
        Op('cr', 0.0297, bm=0xc0, br=0x0c, wv=0x008a, wi=0x26fe, length=1, resp=bytes.fromhex('01')),
        Op('cw', 0.0034, bm=0x40, br=0x0c, wv=0x008b, wi=0x26fe, data=bytes.fromhex('00')),
        Op('cr', 0.0038, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0428, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0122027803200402054806180700080009000a480b6c0c000d00110012041308140115801601170c181419001a001b001c001d001e101f00200c2100221a2300')),
        Op('cr', 0.0032, bm=0xc0, br=0x04, wv=0x008e, wi=0x3722, length=2, resp=bytes.fromhex('1455')),
        Op('cr', 0.004, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('241a2500260027002b202c122dc030ee3180321f338e348035fb36fc3721386039023a003b003c003d003e003f014f6352075309540b5501560357055a125b00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('5c005e1f5f07600061006320677f687f690170067109720873097400750076007700780079007a007b007c007d007e757f308000812282008301841885008600')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('87009300940095009d08a009a400a520a600a700a800a900aa00ab30b800b938ba00bd00be00bf00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x0c, wv=0x008c, wi=0x0010, data=bytes.fromhex('0d')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0054, bm=0x40, br=0x0c, wv=0x008c, wi=0x0013, data=bytes.fromhex('0d')),
        Op('cr', 0.0036, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0b64')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('130f')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0b6c')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x0c, wv=0x008b, wi=0x0007, data=bytes.fromhex('01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x008b, wi=0x0009, data=bytes.fromhex('00000000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008a, wi=0x0010, length=3, resp=bytes.fromhex('c84013')),
        Op('cw', 0.0043, bm=0x40, br=0x04, wv=0x008b, wi=0x000b, data=bytes.fromhex('00000100')),
        Op('cr', 0.0036, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0042, bm=0xc0, br=0x04, wv=0x008a, wi=0x000f, length=64, resp=bytes.fromhex('ffffffffffffffff000000000000000000000000000000000000000000000000000000fcffffffffffffffffffffffffffffffffffffffffffffffffffffffff')),
        Op('poll', 0.008, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('d855'), dur=0.004),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0310')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0300')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0042, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51005d005ef8')),
        Op('cr', 0.0038, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0042, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51015d005e80')),
        Op('cr', 0.0038, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51025d005e00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51035d005e00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51045d005e00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51055d005e00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51065d005e00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('51075d005e00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
    ],
)

JOG_OP_RANGE = (88, 170)

JOG = Phase(
    name="jog",
    op_range=(88, 170),
    ops=[
        Op('cr', 0.0042, bm=0xc0, br=0x0c, wv=0x008e, length=1, resp=bytes.fromhex('00')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x008e, wi=0x3122, length=2, resp=bytes.fromhex('fc55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('317c')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0239, bm=0xc0, br=0x04, wv=0x008e, wi=0x3122, length=2, resp=bytes.fromhex('7c55')),
        Op('cw', 0.0032, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('31fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0755')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3205')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('d855')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0038, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('338e')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3207')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0042, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('d855')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0908')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0042, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0218ae00afff3d003e1a3f22')),
        Op('cr', 0.0038, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0044, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0036, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0042, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0038, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 1.5986, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855'), dur=1.5946),
        Op('cw', 0.0161, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0900')),
        Op('cr', 0.0033, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('1f55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('321f')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0042, bm=0xc0, br=0x04, wv=0x008e, wi=0x3522, length=2, resp=bytes.fromhex('fb55')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('35bb')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('1f55')),
        Op('poll', 0.5092, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855'), dur=0.5048),
        Op('cr', 0.0038, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('1f55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('321d')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0044, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.0038, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('1c0002183d003e1a3f227d007e757f308a008b008c008d008e008f00900091009200ae00afff')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0043, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0037, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 1.6184, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855'), dur=1.6143),
        Op('cr', 0.0037, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('1d55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('321f')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0908')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('1c0002183d003e0c3f127d007e757f308a008b008c008d008e008f00900091009200ae00afff')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0044, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0036, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 0.8753, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855'), dur=0.8712),
        Op('cw', 0.0155, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0900')),
        Op('cr', 0.0031, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
    ],
)

LOAD_OP_RANGE = (194, 260)

LOAD = Phase(
    name="load",
    op_range=(194, 260),
    ops=[
        Op('cr', 0.0039, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('1f55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('321d')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('1c0002183d003e1a3f227d007e757f308a008b008c008d008e008f009000912a92f8012203300402054806180700080009000a480b6c0c000d00110012041308')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('140115901601170c181419001a001b001d001e101f00200c2100221a2300241a2500260027002b202c122dc030ee3180338e348035bb36fc3721386039023a00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3b003c004f6352075309540b5501560357055a125b005c005e1f5f07600061006320677f687f690170067109720873097400750076007700780079007a007b00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('7c00800081228200830184188500860087009300940095009d08a009a400a520a600a700a800a900aa00ab30b800b938ba00bd00be00bf00ae00afff')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0044, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0036, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0042, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0038, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 1.6133, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f455'), dur=1.6093),
        Op('cw', 0.0038, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('1c00021c3d013e173f427d007e757f308a008b008c008d008e008f009000912a92f8ae00afff')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0045, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0035, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0002, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 1.0966, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('dc55'), dur=1.0925),
        Op('cw', 0.0159, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0035, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3a00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('330e')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.116, bm=0xc0, br=0x04, wv=0x008e, wi=0x3122, length=2, resp=bytes.fromhex('fe55')),
        Op('cr', 0.0032, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('dc55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3a00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('330e')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3205')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 2.0731, bm=0xc0, br=0x04, wv=0x008e, wi=0x3522, length=2, resp=bytes.fromhex('bb55')),
        Op('poll', 0.0079, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555'), dur=0.004),
        Op('cr', 0.1045, bm=0xc0, br=0x04, wv=0x008e, wi=0x3122, length=2, resp=bytes.fromhex('fe55')),
        Op('cr', 0.0035, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('dc55')),
    ],
)

# Kept for callers that predate JOG: the LOAD slice.
OP_RANGE = LOAD_OP_RANGE

PHASES = [OPEN, JOG, LOAD]
