"""Vendor magazine-load sequence for the of135i driver.

AUTO-GENERATED by tools/gen_load_table.py from
traces/20260905-vendor-clean-load.trace.json.gz ops 194-260 -- do not edit by hand.

The vendor app's standalone insert flow (Test 14, docs/test-log.md):
magazine taken fully out and reinserted fresh to the stop, then
loader-sensor ack (reg 0x32), the engaging feed (mode 0x18, FEEDL
0x1a22) programmed with the vendor's full register block (four
batches, 126 registers incl. 0x01=0x22, 0x03=0x30, 0x15=0x90,
0x35=0xbb) plus loader slope tables and GO, the slow prescan
traverse (mode 0x1c, FEEDL 71490) and the first idle housekeeping
cycle. Replayed verbatim by Scanner.load_magazine() with the same
executor semantics as every other phase (device.py _exec_ops),
after initialize() and behind the start-state guard (safety.py).
The two motor-completion polls are checked with the masked
completion test (device.load_status_matches): state class AND
loader-sensor bit 0x08, not an exact status word.

History: the previous table (eject-from-loaded ops 291-640) ran
the feed as a bare 19-register batch and never engaged the
cassette on hardware (Tests 11b/12b/13). This table is NOT yet
hardware-verified as a load.
"""

from __future__ import annotations

from .tables import Op, Phase

OP_RANGE = (194, 260)

LOAD = Phase(
    name="load",
    op_range=(194, 260),
    ops=[
        Op('cr', 0.0039, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('1f55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('321d')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f855')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('1c0002183d003e1a3f227d007e757f308a008b008c008d008e008f009000912a92f8012203300402054806180700080009000a480b6c0c000d00110012041308')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('140115901601170c181419001a001b001d001e101f00200c2100221a2300241a2500260027002b202c122dc030ee3180338e348035bb36fc3721386039023a00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3b003c004f6352075309540b5501560357055a125b005c005e1f5f07600061006320677f687f690170067109720873097400750076007700780079007a007b00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('7c00800081228200830184188500860087009300940095009d08a009a400a520a600a700a800a900aa00ab30b800b938ba00bd00be00bf00ae00afff')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0044, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0036, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0042, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0038, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 1.6133, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('f455'), dur=1.6093),
        Op('cw', 0.0038, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('1c00021c3d013e173f427d007e757f308a008b008c008d008e008f009000912a92f8ae00afff')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0045, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('00c0001000020000')),
        Op('cr', 0.0035, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0002, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0082, wi=0x0001, data=bytes.fromhex('0000011000020000')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('bo', 0.0041, data=bytes.fromhex('c7e5ef433a2e0625801fcd1b1e190b1767150814ea12eb1118115810b00f150f930e130ea20d3d0dde0c850c350ce80ba00b5a0b1c0be10aac0a750a440a140ae609bd0992096c09470923090009e008bf08a108850868084d0832081808ff07e807d207ba07a40790077b076707540742072f071d070d07fb06eb06db06cc06bd06ae06a00692068406760668065c064f06430637062b061f0614060906fe05f405e805de05d405ca05c105b805ae05a5059b0593058a0582057905700569056105580551054a0541053a0533052c0525051d051605100509050205fc04f604f004e904e304dd04d704d104cb04c504c004ba04b504af04aa04a504a0049a04950490048b04860481047c04780473046e046904650461045c04580454044f044b04470443043e043a04360432042e042a04260422041f041b041704130410040c04090405040204fe03fb03f703f403f103ed03ea03e703e403e003dd03da03d703d303d103ce03ca03c803c503c203bf03bc03b903b603b303b103ae03ab03a803a603a303a0039e039b0398039603930391038e038c03890387038403820380037d037b0378037603740371036f036d036b03680366036403620360035e035b03590357035503530351034f034d034b03490347034503430341033f033d033b033903370336033403310330032e032c032a03290327032503230321032003')),
        Op('cr', 0.0001, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0018, length=1, resp=bytes.fromhex('02')),
        Op('cw', 0.0039, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('0f01')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('poll', 1.0966, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('dc55'), dur=1.0925),
        Op('cw', 0.0159, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0035, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3a00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('330e')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.116, bm=0xc0, br=0x04, wv=0x008e, wi=0x3122, length=2, resp=bytes.fromhex('fe55')),
        Op('cr', 0.0032, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('dc55')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3a00')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('36fc')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cw', 0.0041, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('330e')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 0.0041, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cw', 0.004, bm=0x40, br=0x04, wv=0x0083, data=bytes.fromhex('3205')),
        Op('cr', 0.0039, bm=0xc0, br=0x0c, wv=0x008e, wi=0x0020, length=1, resp=bytes.fromhex('55')),
        Op('cr', 2.0731, bm=0xc0, br=0x04, wv=0x008e, wi=0x3522, length=2, resp=bytes.fromhex('bb55')),
        Op('poll', 0.0079, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555'), dur=0.004),
        Op('cr', 0.1045, bm=0xc0, br=0x04, wv=0x008e, wi=0x3122, length=2, resp=bytes.fromhex('fe55')),
        Op('cr', 0.0035, bm=0xc0, br=0x04, wv=0x008e, wi=0x3222, length=2, resp=bytes.fromhex('0555')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0022, length=2, resp=bytes.fromhex('f055')),
        Op('cr', 0.004, bm=0xc0, br=0x04, wv=0x018e, wi=0x0122, length=2, resp=bytes.fromhex('dc55')),
    ],
)

PHASES = [LOAD]
