/* GENERATED by tools/gen_sane_tables.py from of135i/tables*.py --
 * do not edit. Regenerate after any table change.
 *
 * Register values captured from the vendor driver and verified
 * byte-exact against USB traces (docs/protocol-notes.md); these are
 * interoperability facts, not vendor code. Reads and polls are not
 * reproduced here: the backend polls explicitly with timeouts
 * (docs/sane-port.md, decision 3).
 */

#ifndef BACKEND_GENESYS_GL126_TABLES_H
#define BACKEND_GENESYS_GL126_TABLES_H

#include <cstddef>
#include <cstdint>

namespace genesys {
namespace gl126 {

/** One register write: the chip takes [reg][val] byte pairs. */
struct RegPair {
    std::uint8_t reg;
    std::uint8_t val;
};

/** A value the hook must compute and patch in before writing.
 *  `index` addresses the phase's pair array; the captured value
 *  standing there belongs to the reference unit and must not be
 *  written as-is. */
struct RegInjection {
    const char* name;
    std::size_t index;
};

/** A buffer transfer: descriptor address plus payload length. */
struct BufWrite {
    std::uint32_t addr;
    std::uint32_t length;
};

/** One phase of the captured sequence. */
struct Phase {
    const char* name;
    const RegPair* regs;
    std::size_t reg_count;
    const RegInjection* injections;
    std::size_t injection_count;
    const BufWrite* buffers;
    std::size_t buffer_count;
};

/** An op-program transfer kind (docs/sane-hook2-offset.md
 *  section 6); gl126_ops.cpp is the runner that executes these. */
enum class OpKind : std::uint8_t {
    Write,          /* control write: register batch, 0x82 buffer
                       descriptor, or 0x8c write */
    AckRead,        /* control read, 1 B, must be 0x55 */
    Read,           /* control read, logged only (provenance) */
    PollDataReady,  /* poll reg 0x101 until bit 0x01 (DATAENB) sets */
    BulkIn,         /* bulk IN of `len` bytes from EP 0x81 */
    BulkDone,       /* control read after a bulk transfer, logged only */
};

/** One op-program transfer. `data` is the write payload (Write) or
 *  the captured reply (AckRead/Read/PollDataReady/BulkDone,
 *  provenance only -- the runner does not require a live reply to
 *  match it, except AckRead's fixed 0x55 and PollDataReady's bit
 *  0x01); nullptr for BulkIn. */
struct Op {
    OpKind kind;
    std::uint8_t request;    /* bRequest; 0 for BulkIn */
    std::uint16_t value;     /* wValue */
    std::uint16_t index;     /* wIndex */
    const std::uint8_t* data;
    std::uint16_t len;       /* Write/reads: byte length; BulkIn: bulk length */
    std::uint16_t dur_ms;    /* captured poll duration, ms (0 otherwise) */
};

/** An ordered op program for one phase -- prep/afe_base/cal_dark_a/
 *  cal_dark_b only, the whole scope of SANE hook 2. */
struct OpProgram {
    const char* name;
    const Op* ops;
    std::size_t count;
};

/** One scan profile: a resolution and its phase sequence. */
struct Profile {
    const char* name;
    unsigned dpi;
    unsigned image_width;      /* px per line, RGB16LE */
    unsigned chunk_len;        /* bytes per image bulk-read */
    unsigned lines_per_chunk;
    unsigned shading_lines;
    unsigned shading_upload_len;
    const std::uint8_t* slope_position;
    std::size_t slope_position_len;
    const std::uint8_t* slope_scan;
    std::size_t slope_scan_len;
    const Phase* phases;
    std::size_t phase_count;
    const OpProgram* programs;  /* prep/afe_base/cal_dark_a/cal_dark_b */
    std::size_t program_count;
};

/** Power-on base register table, written once per session. */
extern const RegPair BASE_INIT[116];
constexpr std::size_t BASE_INIT_COUNT = 116;

/** AFE bring-up values that follow the base table. */
extern const RegPair AFE_BASE[8];
constexpr std::size_t AFE_BASE_COUNT = 8;

/** Cold-start table (reg 0x01 lacks the ready bit 0x20). */
extern const RegPair COLD_INIT[125];
constexpr std::size_t COLD_INIT_COUNT = 125;

/** Loader motor speed registers used by the magazine phases. */
extern const RegPair LOADER_SPEED[13];
constexpr std::size_t LOADER_SPEED_COUNT = 13;

extern const std::uint8_t SLOPE_LOADER[512];
constexpr std::size_t SLOPE_LOADER_LEN = 512;

extern const std::uint8_t SLOPE_PLAIN3600_POSITION[512];
constexpr std::size_t SLOPE_PLAIN3600_POSITION_LEN = 512;

extern const std::uint8_t SLOPE_PLAIN3600_SCAN[512];
constexpr std::size_t SLOPE_PLAIN3600_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_IR3600_SCAN[512];
constexpr std::size_t SLOPE_IR3600_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI600_SCAN[512];
constexpr std::size_t SLOPE_DPI600_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI1200_SCAN[512];
constexpr std::size_t SLOPE_DPI1200_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI2400_SCAN[512];
constexpr std::size_t SLOPE_DPI2400_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI7200_SCAN[512];
constexpr std::size_t SLOPE_DPI7200_SCAN_LEN = 512;

/** The magazine phases (OPEN / JOG / LOAD), in order. */
extern const Phase MAGAZINE_PHASES[3];
constexpr std::size_t MAGAZINE_PHASE_COUNT = 3;

/** Every scan profile, indexed by PROFILE_COUNT. */
extern const Profile PROFILES[6];
constexpr std::size_t PROFILE_COUNT = 6;

} // namespace gl126
} // namespace genesys

#endif // BACKEND_GENESYS_GL126_TABLES_H
