/* sane - Scanner Access Now Easy.

   Copyright (C) 2026 Christian Gillinger

   This file is part of the SANE package.

   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License as
   published by the Free Software Foundation; either version 2 of the
   License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful, but
   WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
   General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

/* GENERATED by tools/gen_sane_tables.py from the companion
 * userspace driver's own captured tables, do not edit. Regenerate
 * after any table change.
 *
 * Register values captured from the vendor driver and verified
 * byte-exact against USB traces; these are interoperability
 * facts, not vendor code. Reads and polls are not reproduced
 * here: the backend polls explicitly with timeouts.
 *
 * Protocol notes and the reverse-engineering record:
 * https://github.com/cgillinger/opticfilm135i-linux
 */

#ifndef BACKEND_GENESYS_GL126_TABLES_H
#define BACKEND_GENESYS_GL126_TABLES_H

#include <cstddef>
#include <cstdint>

namespace genesys {
namespace gl126 {

/** One register write: the chip takes [reg][val] byte pairs. */
struct RegPair {
    std::uint8_t reg;
    std::uint8_t val;
};

/** A value the hook must compute and patch in before writing.
 *  `index` addresses the phase's pair array; the captured value
 *  standing there belongs to the reference unit and must not be
 *  written as-is. */
struct RegInjection {
    const char* name;
    std::size_t index;
};

/** A buffer transfer: descriptor address plus payload length. */
struct BufWrite {
    std::uint32_t addr;
    std::uint32_t length;
};

/** One phase of the captured sequence. */
struct Phase {
    const char* name;
    const RegPair* regs;
    std::size_t reg_count;
    const RegInjection* injections;
    std::size_t injection_count;
    const BufWrite* buffers;
    std::size_t buffer_count;
};

/** An op-program transfer kind;
 *  gl126_ops.cpp is the runner that executes these. */
enum class OpKind : std::uint8_t {
    Write,          /* control write: register batch, 0x82 buffer
                       descriptor, or 0x8c write */
    AckRead,        /* control read, 1 B, must be 0x55 */
    Read,           /* control read, logged only (provenance) */
    PollDataReady,  /* poll reg 0x101 until bit 0x01 (DATAENB) sets */
    PollClass,      /* poll reg 0x100 until (reply[0] & 0xf0) matches
                       the captured settled value's upper nibble */
    BulkIn,         /* bulk IN of `len` bytes from EP 0x81 */
    BulkOut,        /* bulk OUT of `len` bytes to EP 0x02 */
    BulkDone,       /* control read after a bulk transfer, logged only */
    PollMasked,     /* poll until (reply[0] & mask) == want: POSITION's
                       W3 (class F), PARK's Wait A (reg 0x35 bit 0x40)
                       and Wait B (the PARK_COMPLETE status word) */
    ReadModifyWrite,/* read register (index>>8) via 0x008e/index, write
                       back (v & mask) | want as a 2-byte register batch,
                       no ack read (PARK's three RMW registers, 4
                       sites) */
    Sleep,          /* no transfer: wait dur_ms, the companion driver's
                       own replayer pacing, which the magazine flow was
                       hardware-verified with */
    PollBestEffort, /* poll until (reply[0] & mask) == want, but a timeout
                       logs and continues instead of failing closed, the
                       driver's own non-raising polls (cold start, eject
                       completion, the load flow's state reads) */
};

/** One op-program transfer. `data` is the write payload (Write, and a
 *  BulkOut not covered by a bulk injection) or the captured reply
 *  (AckRead/Read/PollDataReady/PollClass/BulkDone, provenance only,
 *  the runner does not require a live reply to match it, except
 *  AckRead's fixed 0x55, PollDataReady's bit 0x01 and PollClass's
 *  upper nibble). `data` is nullptr for BulkIn, and for a BulkOut a
 *  bulk injection covers, its captured chunk is the reference unit's
 *  own calibration data and must not be kept; `len` still gives the
 *  wire length. */
struct Op {
    OpKind kind;
    std::uint8_t request;    /* bRequest; 0 for BulkIn/BulkOut */
    std::uint16_t value;     /* wValue */
    std::uint16_t index;     /* wIndex */
    const std::uint8_t* data;
    std::uint16_t len;       /* Write/reads: byte length; BulkIn/BulkOut: bulk length */
    std::uint16_t dur_ms;    /* captured poll duration, ms (0 otherwise) */
    std::uint8_t mask;       /* PollMasked: poll mask; ReadModifyWrite: and_mask;
                                0 for every other kind */
    std::uint8_t want;       /* PollMasked/PollBestEffort: target value;
                                ReadModifyWrite: or_mask; 0 for every other kind.
                                ReadModifyWrite's target register is (index >> 8),
                                the same encoding as its own read setup
                                (index = (reg << 8) | 0x22) */
    std::uint32_t timeout_ms;/* PollMasked/PollBestEffort: this site's own
                                budget, mirroring what the driver allows it
                                (max(3x captured, 1 s); cold start: 15 s /
                                30 s). 0 = use the RunPolicy value. */
};

/** A value the op-program runner must compute and patch into a
 *  Write op's payload before sending it: gl126_ops.cpp's
 *  run_program() takes a name -> byte map and refuses
 *  (OpsFailure::MissingInjection, before any transfer) if a name
 *  here is not in it. `op_index` addresses the OpProgram's own
 *  `ops` array (one-to-one with the captured ops); `byte_offset`
 *  is the byte inside that op's payload, always odd (a value
 *  byte, never a register number). The captured value standing
 *  there belongs to the reference unit and must not be written
 *  as-is. */
struct OpInjection {
    const char* name;
    std::size_t op_index;
    std::size_t byte_offset;
};

/** A payload the op-program runner must compute and split across a
 *  run of consecutive BulkOut ops before sending them: run_program()
 *  takes a name -> byte vector map and refuses
 *  (OpsFailure::MissingInjection, before any transfer) if a name
 *  here is not in it, or OpsFailure::BadInjection if the value is
 *  longer than the ops' combined length. `first_op`/`last_op`
 *  address the OpProgram's own `ops` array, inclusive, and are
 *  always a contiguous run of BulkOut ops. A shorter value is
 *  zero-padded to the combined length before slicing, exactly the
 *  driver's own rule for a "bo" injection. */
struct OpBulkInjection {
    const char* name;
    std::size_t first_op;
    std::size_t last_op;
};

/** An ordered op program for one phase: prep/afe_base/cal_dark_a/
 *  cal_dark_b (offset calibration), cal_white/cal_gain_check_a/
 *  cal_gain_check_b (gain calibration) and
 *  cal_shading_measure/cal_shading_upload/cal_shading_verify/
 *  cal_shading_verify_upload (shading calibration, the last two
 *  are one captured phase, `cal_shading_verify`, split at its
 *  own `split_at`). */
struct OpProgram {
    const char* name;
    const Op* ops;
    std::size_t count;
    const OpInjection* injections;  /* nullptr/0 when none */
    std::size_t injection_count;
    const OpBulkInjection* bulk_injections;  /* nullptr/0 when none */
    std::size_t bulk_injection_count;
};

/** The production geometry for one frame, frozen from the driver's
 *  own holder geometry by gen_sane_tables.py. This is the runtime
 *  positioning/window authority: feedl_for_frame()/frame_geometry()
 *  read it, not the legacy feedl_frame1/feedl_pitch/captured_lines
 *  fields below (kept as capture ground truth / wire-structure
 *  source only). */
struct FrameGeom {
    unsigned feedl;            /* commanded POSITION target (plain: window
                                  centre; dual: fixed-K re-anchor) */
    unsigned line_register;    /* line count programmed into the scan register
                                  (plain: incl the 8-line drain; dual: the
                                  interleaved wire count); begin_scan injects it */
    unsigned read_lines;       /* image lines actually read off the wire; the
                                  byte budget and chunk driver size come from
                                  this (differs from line_register by the drain) */
    unsigned delivered_lines;  /* lines the frontend receives (after colour
                                  crop / parity split) */
    unsigned chunks;           /* image chunks to read */
    unsigned end_hwdpi;        /* furthest motor position the pass reaches;
                                  re-checked <= FEEDL_CEILING before any write */
};

/** One scan profile: a resolution and its phase sequence. */
struct Profile {
    const char* name;
    unsigned dpi;
    unsigned image_width;      /* px per line as READ off the wire, RGB16LE */
    unsigned delivered_width;  /* px per line DELIVERED to the frontend:
                                  == image_width for every profile but the
                                  anisotropic dpi2400 (3600 across / 2400 along),
                                  where the sensor axis is scaled to
                                  round(image_width * along_dpi / across_dpi) = 3504
                                  so the delivered pixels are square. The raw read
                                  path (chunk_len, chunk_count, byte budget) is
                                  sized from image_width and is unchanged; the
                                  core's ImagePipelineNodeScaleRows resamples the
                                  host image from image_width to this. */
    unsigned chunk_len;        /* bytes per image bulk-read */
    unsigned lines_per_chunk;
    unsigned shading_lines;
    unsigned shading_upload_len;
    unsigned captured_lines;   /* legacy capture evidence (DEFAULT_LINES, the
                                  frame-1 vendor trace's line count); not written
                                  to the wire at runtime,
                                  frames[].line_register drives the scan register */
    unsigned chunk_count;      /* image chunks the vendor read (IMAGE_CHUNK_COUNT):
                                  chunk_count * lines_per_chunk lines are read,
                                  which for ir3600 is fewer than captured_lines */
    unsigned feedl_frame1;     /* legacy capture ground truth (vendor grid),
                                  not used at runtime, use frames[] */
    unsigned feedl_pitch;      /* legacy capture ground truth (vendor grid),
                                  not used at runtime, use frames[] */
    const FrameGeom* frames;   /* production geometry, frames 1-6 (index
                                  frame-1); the runtime positioning/window authority */
    const std::uint8_t* slope_position;
    std::size_t slope_position_len;
    const std::uint8_t* slope_scan;
    std::size_t slope_scan_len;
    const Phase* phases;
    std::size_t phase_count;
    const OpProgram* programs;  /* prep/afe_base/cal_dark_a/cal_dark_b/
                                   cal_white/cal_gain_check_a/cal_gain_check_b/
                                   cal_shading_measure/cal_shading_upload/
                                   cal_shading_verify/cal_shading_verify_upload */
    std::size_t program_count;
};

/** Power-on base register table, written once per session. */
extern const RegPair BASE_INIT[116];
constexpr std::size_t BASE_INIT_COUNT = 116;

/** AFE bring-up values that follow the base table. */
extern const RegPair AFE_BASE[8];
constexpr std::size_t AFE_BASE_COUNT = 8;

/** Cold-start table (reg 0x01 lacks the ready bit 0x20). */
extern const RegPair COLD_INIT[125];
constexpr std::size_t COLD_INIT_COUNT = 125;

/** Loader motor speed registers used by the magazine phases. */
extern const RegPair LOADER_SPEED[13];
constexpr std::size_t LOADER_SPEED_COUNT = 13;

extern const std::uint8_t SLOPE_LOADER[512];
constexpr std::size_t SLOPE_LOADER_LEN = 512;

extern const std::uint8_t SLOPE_PLAIN3600_POSITION[512];
constexpr std::size_t SLOPE_PLAIN3600_POSITION_LEN = 512;

extern const std::uint8_t SLOPE_PLAIN3600_SCAN[512];
constexpr std::size_t SLOPE_PLAIN3600_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_IR3600_SCAN[512];
constexpr std::size_t SLOPE_IR3600_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI600_SCAN[512];
constexpr std::size_t SLOPE_DPI600_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI1200_SCAN[512];
constexpr std::size_t SLOPE_DPI1200_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI2400_SCAN[512];
constexpr std::size_t SLOPE_DPI2400_SCAN_LEN = 512;

extern const std::uint8_t SLOPE_DPI7200_SCAN[512];
constexpr std::size_t SLOPE_DPI7200_SCAN_LEN = 512;

/** The magazine phases (OPEN / JOG / LOAD), in order. */
extern const Phase MAGAZINE_PHASES[3];
constexpr std::size_t MAGAZINE_PHASE_COUNT = 3;

/** The magazine flow's op programs, in the order they run:
 *  cold_init (the driver's cold-start sequence), open + jog (the
 *  vendor's app start, whose jog is the eject of a latched
 *  magazine), load (after the operator reseated it) and eject.
 *  Looked up by name through gl126_ops.h's magazine_program(). */
extern const OpProgram MAGAZINE_PROGRAMS[5];
constexpr std::size_t MAGAZINE_PROGRAM_COUNT = 5;

/** Every scan profile, indexed by PROFILE_COUNT. */
extern const Profile PROFILES[6];
constexpr std::size_t PROFILE_COUNT = 6;

} // namespace gl126
} // namespace genesys

#endif // BACKEND_GENESYS_GL126_TABLES_H
