#!/usr/bin/env python3
"""Compile the vendor magazine-load sequence into of135i/tables_load.py.

Source: the 2026-09-02 capture of the vendor app's plain insert flow
(traces/20260902-vendor-eject-from-loaded.trace.json.gz, ops 291-640):
loader-sensor ack (reg 0x32), feed (mode 0x18, FEEDL 0x1a22, loader
speed regs + loader slope tables) and the slow prescan traverse (mode
0x1c, FEEDL 71490). This is exactly the op slice tools/load_magazine.py
replayed directly from the trace file until the 2026-09-05 safety
pass; the table module makes the sequence part of the driver
(Scanner.load_magazine(), protected by the start-state guard) and
independent of the trace file, which is not published.

Regenerate with:
    .venv/bin/python tools/gen_load_table.py

tests/test_safety.py checks the generated module against the trace
slice byte for byte when the trace is present.
"""

from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "tools"))

from gen_tables import make_op  # noqa: E402

TRACE = REPO / "traces" / "20260902-vendor-eject-from-loaded.trace.json.gz"
OUT = REPO / "of135i" / "tables_load.py"
OP_RANGE = (291, 640)


def load_ops() -> list[dict]:
    raw = json.load(gzip.open(TRACE, "rt"))
    return [make_op(o) for o in raw[OP_RANGE[0]:OP_RANGE[1]]]


def render_op(op: dict, indent: str = "    ") -> str:
    args = [repr(op["kind"]), repr(round(op["dt"], 4))]
    kw = []
    if op["bm"]:
        kw.append(f'bm={op["bm"]:#04x}')
    if op["br"]:
        kw.append(f'br={op["br"]:#04x}')
    if op["wv"]:
        kw.append(f'wv={op["wv"]:#06x}')
    if op["wi"]:
        kw.append(f'wi={op["wi"]:#06x}')
    if op["data"]:
        kw.append(f"data=bytes.fromhex({op['data'].hex()!r})")
    if op["length"]:
        kw.append(f'length={op["length"]}')
    if op["resp"]:
        kw.append(f"resp=bytes.fromhex({op['resp'].hex()!r})")
    if op["dur"]:
        kw.append(f'dur={round(op["dur"], 4)}')
    return f"{indent}Op({', '.join(args + kw)}),"


def main() -> int:
    ops = load_ops()
    lines = [
        '"""Vendor magazine-load sequence for the of135i driver.',
        "",
        "AUTO-GENERATED by tools/gen_load_table.py from",
        f"traces/{TRACE.name} ops {OP_RANGE[0]}-{OP_RANGE[1]} -- do not edit by hand.",
        "",
        "The vendor app's plain insert flow, captured 2026-09-02 and hardware-",
        "verified end to end (load -> scan -> eject) the same day: loader-",
        "sensor ack (reg 0x32), feed (mode 0x18, FEEDL 0x1a22, loader speed",
        "profile + loader slope tables) and the slow prescan traverse (mode",
        "0x1c, FEEDL 71490). Replayed verbatim by Scanner.load_magazine()",
        "with the same executor semantics as every other phase (device.py",
        "_exec_ops), after initialize() and behind the start-state guard",
        "(safety.py).",
        "",
        "Known limitation (docs/hardware-safety.md, magazine section): this",
        "sequence sets the vendor's 'loaded' indication but has been observed",
        "leaving the magazine mechanically unlatched (2026-09-04). It is the",
        "verified load flow, not a proof that the magazine is locked.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from .tables import Op, Phase",
        "",
        f"OP_RANGE = {OP_RANGE!r}",
        "",
        "LOAD = Phase(",
        '    name="load",',
        f"    op_range={OP_RANGE!r},",
        "    ops=[",
    ]
    lines.extend(render_op(op, indent="        ") for op in ops)
    lines.extend([
        "    ],",
        ")",
        "",
        "PHASES = [LOAD]",
    ])
    OUT.write_text("\n".join(lines) + "\n")
    kinds: dict[str, int] = {}
    for op in ops:
        kinds[op["kind"]] = kinds.get(op["kind"], 0) + 1
    print(f"wrote {OUT} ({len(ops)} ops: {kinds})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
