#!/usr/bin/env python3
"""Compile the vendor magazine JOG and LOAD sequences into of135i/tables_load.py.

Source: the 2026-09-05 clean standalone vendor load
(traces/20260905-vendor-clean-load.trace.json.gz; Test 14 in
docs/test-log.md): QuickScan in the Win11 VM, captured with usbmon on
the Linux host. Two slices:

JOG, ops 88-170 -- the vendor's app-start jog, run right after the base
register table + AFE values with the magazine loose in the slot:
interrupt/sensor acks (regs 0x31/0x32/0x36/0x33), motor enable, feed
6690 (short batch), 0x35=0xbb, feed 6690 (19-register batch), eject
3090, motor disable. Every vendor load that engaged the cassette
(eject-from-loaded 2026-09-02, load-only 2026-08-30, clean-load
2026-09-05) was preceded by exactly this jog; every load of ours that
did not engage (Tests 11b/12b/13/15) lacked it. The jog's own feeds
never clear the loader-sensor bit (0xf855 after each) -- it positions
the mechanism for the load that follows.

LOAD, ops 194-260 -- after the operator took the magazine fully out
and reinserted it to the stop: loader-sensor ack (reg 0x32), the
ENGAGING feed (mode 0x18, FEEDL 0x1a22) with the vendor's full register
block (four batches, 126 registers incl. 0x01=0x22, 0x03=0x30,
0x15=0x90, 0x35=0xbb), loader slope tables and GO, the slow prescan
traverse (mode 0x1c, FEEDL 71490) and the first idle housekeeping
cycle.

Never regenerate from a capture whose load is not standalone: the
2026-09-02 eject-cut table (ops 291-640 of eject-from-loaded) carried
a stripped feed and no jog.

Regenerate with:
    .venv/bin/python tools/gen_load_table.py

tests/test_safety.py checks the generated module against the trace
slices byte for byte when the trace is present.
"""

from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "tools"))

from gen_tables import make_op  # noqa: E402

TRACE = REPO / "traces" / "20260905-vendor-clean-load.trace.json.gz"
OUT = REPO / "of135i" / "tables_load.py"
PHASES = [("JOG", "jog", (88, 170)), ("LOAD", "load", (194, 260))]


def load_ops(op_range: tuple[int, int]) -> list[dict]:
    raw = json.load(gzip.open(TRACE, "rt"))
    return [make_op(o) for o in raw[op_range[0]:op_range[1]]]


def render_op(op: dict, indent: str = "    ") -> str:
    args = [repr(op["kind"]), repr(round(op["dt"], 4))]
    kw = []
    if op["bm"]:
        kw.append(f'bm={op["bm"]:#04x}')
    if op["br"]:
        kw.append(f'br={op["br"]:#04x}')
    if op["wv"]:
        kw.append(f'wv={op["wv"]:#06x}')
    if op["wi"]:
        kw.append(f'wi={op["wi"]:#06x}')
    if op["data"]:
        kw.append(f"data=bytes.fromhex({op['data'].hex()!r})")
    if op["length"]:
        kw.append(f'length={op["length"]}')
    if op["resp"]:
        kw.append(f"resp=bytes.fromhex({op['resp'].hex()!r})")
    if op["dur"]:
        kw.append(f'dur={round(op["dur"], 4)}')
    return f"{indent}Op({', '.join(args + kw)}),"


def main() -> int:
    lines = [
        '"""Vendor magazine JOG and LOAD sequences for the of135i driver.',
        "",
        "AUTO-GENERATED by tools/gen_load_table.py from",
        f"traces/{TRACE.name} -- do not edit by hand.",
        "",
        "JOG (ops 88-170): the vendor's app-start jog -- interrupt/sensor",
        "acks, feed 6690, 0x35=0xbb, feed 6690, eject 3090 -- run after the",
        "base table + AFE values with the magazine loose in the slot. Every",
        "vendor load that engaged the cassette was preceded by it; every",
        "load of ours that did not engage lacked it (Tests 11b-15). Its",
        "three completions read 0xf855 (done, loader-sensor bit SET).",
        "Replayed by Scanner.jog_magazine().",
        "",
        "LOAD (ops 194-260): after the operator took the magazine fully out",
        "and reinserted it to the stop -- loader-sensor ack (reg 0x32), the",
        "engaging feed (mode 0x18, FEEDL 0x1a22) with the vendor's full",
        "register block (four batches, 126 registers incl. 0x01=0x22,",
        "0x03=0x30, 0x15=0x90, 0x35=0xbb), loader slope tables and GO, the",
        "slow prescan traverse (mode 0x1c, FEEDL 71490) and the first idle",
        "housekeeping cycle. Completions 0xf455 (sensor CLEAR: cassette",
        "pulled past the sensor) and 0xdc55. Replayed by",
        "Scanner.load_magazine().",
        "",
        "Both run with the same executor semantics as every other phase",
        "(device.py _exec_ops), behind the start-state guard (safety.py);",
        "the motor completions use the masked test device.load_status_",
        "matches (state class AND loader-sensor bit 0x08), not an exact",
        "status word. The JOG + reinsert + LOAD flow is NOT yet hardware-",
        "verified (Test 15 ran LOAD without the jog: feed done, sensor bit",
        "still set, magazine loose).",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from .tables import Op, Phase",
        "",
    ]
    summary = []
    for const, name, op_range in PHASES:
        ops = load_ops(op_range)
        lines.append(f"{const}_OP_RANGE = {op_range!r}")
        lines.append("")
        lines.append(f"{const} = Phase(")
        lines.append(f'    name="{name}",')
        lines.append(f"    op_range={op_range!r},")
        lines.append("    ops=[")
        lines.extend(render_op(op, indent="        ") for op in ops)
        lines.append("    ],")
        lines.append(")")
        lines.append("")
        kinds: dict[str, int] = {}
        for op in ops:
            kinds[op["kind"]] = kinds.get(op["kind"], 0) + 1
        summary.append(f"{const} {len(ops)} ops {kinds}")
    lines.append("# Kept for callers that predate JOG: the LOAD slice.")
    lines.append("OP_RANGE = LOAD_OP_RANGE")
    lines.append("")
    lines.append("PHASES = [JOG, LOAD]")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}: " + "; ".join(summary))
    return 0


if __name__ == "__main__":
    sys.exit(main())
