#!/usr/bin/env python3
"""Emit the GL126 register tables as C++ for the SANE genesys backend.

Stage 2 of docs/sane-port.md: the Python driver replays captured phases
verbatim; the backend writes the same registers from generated tables.
This tool is the bridge. It reads `of135i/tables*.py` -- the single source
of truth, verified byte-exact against the USB captures -- and writes
`sane/gl126_tables.{h,cpp}`. Nothing here is hand-maintained: regenerate
after any table change, never edit the output.

What a phase becomes
--------------------
Each `Phase` is an ordered op stream (control writes, bulk writes, reads).
Only the writes carry state the backend must reproduce:

  * `cw` 0x40/0x04 wValue=0x0083 -- a register batch, `[reg][val]` pairs.
    These are flattened, in order, into one pair array per phase.
  * `cw` 0x40/0x04 wValue=0x0082 wIndex=1 -- a buffer descriptor,
    `[addr u32][len u32]`, followed by the `bo` ops carrying the payload.
    Emitted as an address/length record; the payload is either a slope
    table (emitted once, by name) or computed at run time (shading).
  * `cw` 0x40/0x0c -- end-of-access, emitted as its wValue/wIndex.

Reads and polls are deliberately NOT emitted into the pair tables.
Decision 3 in docs/sane-port.md: the C++ hooks poll explicitly with
timeouts rather than replaying the capture's pacing, so a captured read
is provenance, not behaviour. The generator counts them so the header can
state how many ops each phase covered.

Op programs (docs/sane-hook2-offset.md section 6)
--------------------------------------------------
The pair tables above lose three things hook 2 needs: transfer
boundaries, interleaving (a read between two writes), and the bulk
IN/OUT dance around a calibration read. For the phases hook 2/3/4 run
(`prep`, `afe_base`, `cal_dark_a`, `cal_dark_b`, `cal_white`,
`cal_gain_check_a`, `cal_gain_check_b`, `cal_shading_measure`,
`cal_shading_upload`, `cal_shading_verify`), every profile also gets one
or more ordered `OpProgram`s: one `Op` per captured transfer, in
captured order, kept one-to-one with `phase.ops` (or a contiguous slice
of it -- see "Split programs" below). The mapping (see `decode_ops`):

  * `cw`                                             -> `Write`
  * `cr` br=0x0c wv=0x008e wi=0x0020 length=1         -> `AckRead`
  * `cr` br=0x0c wv=0x008e wi=0x0018 length=1         -> `BulkDone`
  * `poll` wv=0x018e wi=0x0122 and resp[0] & 0x01     -> `PollDataReady`
  * `poll` wv=0x018e wi=0x0022 (reg 0x100)            -> `PollClass`
    (docs/sane-hook4-shading.md section 3, W2 -- the only site the
    vendor polls that register; the settled reply is kept as `data` and
    the runner waits for an upper-nibble class match against it)
  * every other `cr`/`poll`                           -> `Read`
  * `bi`                                              -> `BulkIn`
  * `bo`                                              -> `BulkOut` (bulk
    OUT of `len(op.data)` bytes to EP 0x02). A BulkOut COVERED by a bulk
    injection (see "Injection points" below) is emitted with `data =
    nullptr`: its captured chunk is the reference unit's own shading
    table -- calibration data of ONE unit -- and must never be written
    to another, the same principle as a register injection. Only the
    `len` survives. A BulkOut NOT covered by any injection keeps its
    captured payload as `data` (provenance/default); none of the phases
    emitted today has one -- the slope-table uploads in position/scan
    will, later.

`Read`/`AckRead`/`PollDataReady`/`PollClass`/`BulkDone` always carry the
captured reply as `data` (provenance, mirrored into a generated byte
blob); `Write` always carries its payload the same way; `BulkOut` does
too, EXCEPT when a bulk injection covers it (see above). `gl126_ops.cpp`
(the runner) polls `PollDataReady`/`PollClass` for real and fails closed
on a bad `AckRead`, a short `BulkIn`, or a short `BulkOut`; see
docs/sane-hook2-offset.md section 3 and docs/sane-hook4-shading.md
section 3.

Split programs (docs/sane-hook4-shading.md section 6)
-------------------------------------------------------
`cal_shading_verify` genuinely re-measures then re-uploads a table
computed from that measurement, so it cannot run as one program: its
own `phase.split_at` names the local op index of the re-upload's buffer
descriptor. It is emitted as TWO programs, `cal_shading_verify` (ops
`[0, split_at)`, the re-measurement) and `cal_shading_verify_upload`
(ops `[split_at, end)`, the re-upload), op indices in the second
re-based to 0 -- injection op indices are adjusted the same way.

Injection points
----------------
A phase's `injections` name the bytes that carry computed values (gain
codes, offset codes, FEEDL, line count, shading tables) instead of their
captured ones. Writing the captured byte instead would scan with
another unit's calibration, so each one is emitted as a named index (or
range of indices, for a bulk payload) into the phase's pair array. The
backend patches those entries before writing; it must not rely on the
captured value.

The same `injections` dict also feeds an OpInjection table on any phase
that gets an op program (see above): cal_gain_check_a's gain_r/gain_g/
gain_b (docs/sane-hook3-gain.md section 6, part A/2) address the op
program's own `ops` array directly -- op_index is the index into the
ORIGINAL captured op list, which is exactly the emitted op program's
index (one-to-one, asserted in op_injections_for()) -- unlike the pair-
table RegInjection above, which needs the op-index-to-pair-index
remapping decode_phase() computes.

A phase's `("bo", (op_indices...))` specs (the shading-table uploads)
instead feed an OpBulkInjection table: `{name, first_op, last_op}`, the
INCLUSIVE range of consecutive `BulkOut` ops the named payload is split
across (docs/sane-hook4-shading.md section 6) -- see
`op_bulk_injections_for()`. For a split program the range is re-based
the same way the ops themselves are.

Usage:  python tools/gen_sane_tables.py [--check]
        --check regenerates into memory and fails if the checked-in
        output differs (for the offline suite).
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from of135i import (  # noqa: E402
    tables, tables_base, tables_ir, tables_load,
    tables_dpi600, tables_dpi1200, tables_dpi2400, tables_dpi7200,
)

OUT_DIR = REPO / "sane"
STEM = "gl126_tables"

# The scan-table modules, in the order they are emitted. `tables` is the
# 3600 dpi visible-only profile (the plain scan); `tables_ir` is 3600 dpi
# dual-light. The rest are the dual-light profiles for the other four
# resolutions. `tables_load` holds the magazine phases (no dpi).
PROFILES = [
    ("plain3600", tables, 3600, "3600 dpi, visible only (plain scan)"),
    ("ir3600", tables_ir, 3600, "3600 dpi, dual-light (IR + visible)"),
    ("dpi600", tables_dpi600, 600, "600 dpi, dual-light"),
    ("dpi1200", tables_dpi1200, 1200, "1200 dpi, dual-light"),
    ("dpi2400", tables_dpi2400, 2400, "2400 dpi, dual-light"),
    ("dpi7200", tables_dpi7200, 7200, "7200 dpi, dual-light"),
]

# Wire constants (of135i/usbio.py).
REQ_WRITE = 0x04
REQ_END_ACCESS = 0x0C
WV_REGS = 0x0083
WV_BUF_DESC = 0x0082

# Op-program wire constants (docs/sane-hook2-offset.md section 2).
WV_STATUS = 0x008E          # register read / ack read / bulk-done read
WI_ACK = 0x0020             # ack read after a write -> must be 0x55
WI_BULK_DONE = 0x0018       # read after a bulk transfer -> logged only
WV_EXT_STATUS = 0x018E      # extended register read (0x100-0x105)
WI_DATAENB = 0x0122         # reg 0x101: bit 0x01 = data ready
WI_REG100 = 0x0022          # reg 0x100: W2, docs/sane-hook4-shading.md section 3

# Phases that get an op program: hook 2's whole scope (docs/sane-hook2-
# offset.md section 6), hook 3's (docs/sane-hook3-gain.md section 6) and
# hook 4's (docs/sane-hook4-shading.md section 6), in the order they run.
# `cal_shading_verify` is special: it is decoded once and split into two
# programs (see the module docstring's "Split programs" section and the
# main emit loop below), so it is NOT looked up in `phase.name` against
# this tuple the way the others are.
OP_PROGRAM_PHASES = ("prep", "afe_base", "cal_dark_a", "cal_dark_b",
                     "cal_white", "cal_gain_check_a", "cal_gain_check_b",
                     "cal_shading_measure", "cal_shading_upload")
# The name of the phase that gets split, and the two program names it
# produces (docs/sane-hook4-shading.md section 6).
_SPLIT_PHASE = "cal_shading_verify"
_SPLIT_PROGRAM_NAMES = ("cal_shading_verify", "cal_shading_verify_upload")

# The two phases that must yield exactly one PollDataReady/BulkIn/BulkDone.
_DARK_PHASES = ("cal_dark_a", "cal_dark_b")
# Hook 3's three phases: at least one PollDataReady/BulkIn, exactly one
# BulkDone (cal_white has three BulkIn ops; docs/sane-hook3-gain.md
# section 6, part A/1).
_GAIN_PHASES = ("cal_white", "cal_gain_check_a", "cal_gain_check_b")
# Hook 4's four programs (docs/sane-hook4-shading.md section 6): the two
# 128-line measurements (measure, and the first half of verify) each
# carry exactly one PollDataReady and at least one BulkIn and no BulkOut;
# cal_shading_measure alone also carries the W2 PollClass. The two upload
# programs (upload, and the second half of verify) are pure bulk OUT: at
# least one BulkOut, no BulkIn/PollDataReady/PollClass. BulkDone is
# deliberately left unconstrained here (it is 0 on the upload programs, 2
# on verify's measurement half, 1 on measure -- see docs/sane-hook4-
# shading.md section 6, "the validator no longer insists on one BulkDone
# per program"); the wire-equality test (tests/test_sane_ops.py) is what
# pins the exact per-profile transfer counts.
_SHADING_MEASURE_PHASES = ("cal_shading_measure", "cal_shading_verify")
_SHADING_UPLOAD_PHASES = ("cal_shading_upload", "cal_shading_verify_upload")


@dataclass
class BufWrite:
    """One buffer transfer: descriptor plus the payload's total length."""
    addr: int
    length: int
    payload: bytes


@dataclass
class PhaseTables:
    """A phase reduced to what the backend has to reproduce."""
    name: str
    pairs: list[tuple[int, int]]            # (reg, val), in write order
    injections: dict[str, int]              # name -> index into `pairs`
    bo_injections: dict[str, tuple[int, int]]   # name -> (buf index, length)
    buffers: list[BufWrite]
    end_access: list[tuple[int, int]]       # (wValue, wIndex)
    op_count: int
    read_count: int
    split_at: int | None


def decode_phase(phase) -> PhaseTables:
    """Reduce one `Phase` op stream to register pairs, buffers and the
    indices its injection points land on.

    The injection specs address `(op_index, byte_offset)` in the captured
    op data. A register batch is `[reg][val]` pairs, so an even offset is a
    register number and an odd one is its value; every injection in the
    tables targets a value byte. The mapping from op/offset to pair index
    is therefore `pairs_before_this_op + byte_offset // 2`, and it is
    computed here rather than assumed, so a table change that moves a byte
    is caught by the assertion below instead of silently mis-indexing.
    """
    pairs: list[tuple[int, int]] = []
    buffers: list[BufWrite] = []
    end_access: list[tuple[int, int]] = []
    reads = 0
    # op index -> index in `pairs` where that op's pairs start
    pair_base: dict[int, int] = {}
    # op index -> index in `buffers` for that op's descriptor
    buf_of_op: dict[int, int] = {}
    pending_buf: int | None = None

    for i, op in enumerate(phase.ops):
        if op.kind == "cw" and op.br == REQ_WRITE and op.wv == WV_REGS:
            pair_base[i] = len(pairs)
            data = op.data
            if len(data) % 2:
                raise ValueError(
                    f"{phase.name}: register write op {i} has an odd length "
                    f"({len(data)} B); it is not whole [reg][val] pairs")
            pairs.extend((data[k], data[k + 1]) for k in range(0, len(data), 2))
        elif op.kind == "cw" and op.br == REQ_WRITE and op.wv == WV_BUF_DESC:
            addr = int.from_bytes(op.data[0:4], "little")
            length = int.from_bytes(op.data[4:8], "little")
            buf_of_op[i] = len(buffers)
            buffers.append(BufWrite(addr=addr, length=length, payload=b""))
            pending_buf = len(buffers) - 1
        elif op.kind == "bo":
            if pending_buf is None:
                raise ValueError(f"{phase.name}: bulk OUT at op {i} with no "
                                 f"preceding buffer descriptor")
            buffers[pending_buf].payload += op.data
            buf_of_op[i] = pending_buf
        elif op.kind == "cw" and op.br == REQ_END_ACCESS:
            end_access.append((op.wv, op.wi))
        elif op.kind in ("cr", "poll", "bi"):
            reads += 1

    injections: dict[str, int] = {}
    bo_injections: dict[str, tuple[int, int]] = {}
    for name, spec in phase.injections.items():
        if spec[0] == "byte":
            _, idx, off = spec
            if idx not in pair_base:
                raise ValueError(f"{phase.name}: injection {name!r} targets op "
                                 f"{idx}, which is not a register write")
            if off % 2 == 0:
                raise ValueError(f"{phase.name}: injection {name!r} targets byte "
                                 f"{off}, a register number rather than a value")
            injections[name] = pair_base[idx] + off // 2
        elif spec[0] == "bo":
            _, idxs = spec
            bufs = {buf_of_op[i] for i in idxs if i in buf_of_op}
            if len(bufs) != 1:
                raise ValueError(f"{phase.name}: injection {name!r} spans "
                                 f"{len(bufs)} buffers, expected exactly one")
            b = bufs.pop()
            bo_injections[name] = (b, sum(len(phase.ops[i].data) for i in idxs))

    return PhaseTables(
        name=phase.name, pairs=pairs, injections=injections,
        bo_injections=bo_injections, buffers=buffers, end_access=end_access,
        op_count=len(phase.ops), read_count=reads, split_at=phase.split_at,
    )


@dataclass
class OpEntry:
    """One op-program transfer, already classified into the C++ OpKind
    the runner (gl126_ops.cpp) understands."""
    kind: str            # "Write" | "AckRead" | "Read" | "PollDataReady"
                          # | "PollClass" | "BulkIn" | "BulkOut" | "BulkDone"
    request: int          # bRequest; 0 for BulkIn/BulkOut
    value: int             # wValue
    index: int              # wIndex
    data: bytes            # Write/BulkOut: payload; else: captured reply (b"" for BulkIn)
    length: int             # Write/reads: byte length; BulkIn/BulkOut: bulk length
    dur_ms: int             # captured poll duration in ms (0 otherwise)


def decode_ops(phase) -> list[OpEntry]:
    """Reduce one `Phase` op stream to an ordered op-program, one `OpEntry`
    per captured transfer -- see the module docstring's "Op programs"
    section for the mapping rules. Raises ValueError on an op kind the
    mapping does not cover."""
    entries: list[OpEntry] = []
    for i, op in enumerate(phase.ops):
        if op.kind == "cw":
            entries.append(OpEntry("Write", op.br, op.wv, op.wi, op.data,
                                   len(op.data), 0))
        elif op.kind == "cr":
            if (op.br == REQ_END_ACCESS and op.wv == WV_STATUS
                    and op.wi == WI_ACK and op.length == 1):
                entries.append(OpEntry("AckRead", op.br, op.wv, op.wi,
                                       op.resp, op.length, 0))
            elif (op.br == REQ_END_ACCESS and op.wv == WV_STATUS
                    and op.wi == WI_BULK_DONE and op.length == 1):
                entries.append(OpEntry("BulkDone", op.br, op.wv, op.wi,
                                       op.resp, op.length, 0))
            else:
                entries.append(OpEntry("Read", op.br, op.wv, op.wi,
                                       op.resp, op.length, 0))
        elif op.kind == "poll":
            dur_ms = round(op.dur * 1000)
            if (op.wv == WV_EXT_STATUS and op.wi == WI_DATAENB
                    and len(op.resp) >= 1 and (op.resp[0] & 0x01)):
                entries.append(OpEntry("PollDataReady", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms))
            elif op.wv == WV_EXT_STATUS and op.wi == WI_REG100:
                entries.append(OpEntry("PollClass", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms))
            else:
                entries.append(OpEntry("Read", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms))
        elif op.kind == "bi":
            entries.append(OpEntry("BulkIn", 0, 0, 0, b"", op.length, 0))
        elif op.kind == "bo":
            entries.append(OpEntry("BulkOut", 0, 0, 0, op.data, len(op.data), 0))
        else:
            raise ValueError(f"{phase.name}: op {i} has unknown kind {op.kind!r}")
    return entries


_KNOWN_OP_KINDS = frozenset((
    "Write", "AckRead", "Read", "PollDataReady", "PollClass",
    "BulkIn", "BulkOut", "BulkDone",
))


def validate_op_program(phase_name: str, entries: list[OpEntry]) -> None:
    """cal_dark_a/cal_dark_b must each yield exactly one PollDataReady
    (the W1 wait), one BulkIn (the 3072 B dark buffer) and one BulkDone
    (docs/sane-hook2-offset.md section 1, S4/S5).

    cal_white/cal_gain_check_a/cal_gain_check_b (hook 3) are looser: at
    least one PollDataReady and one BulkIn (cal_white has three -- the
    31104 B white line comes back as 16384+14336+384), exactly one
    BulkDone (docs/sane-hook3-gain.md section 6, part A/1).

    cal_shading_measure/cal_shading_verify (hook 4, the two 128-line
    measurements): exactly one PollDataReady, at least one BulkIn, no
    BulkOut; cal_shading_measure alone also carries the W2 PollClass
    (docs/sane-hook4-shading.md section 6). cal_shading_upload/
    cal_shading_verify_upload (the two pure-bulk-OUT uploads): at least
    one BulkOut, no BulkIn/PollDataReady/PollClass. Every program, of
    every kind: no op kind outside `_KNOWN_OP_KINDS` -- decode_ops only
    ever produces one of those, so this is a defensive check against a
    future OpKind this function was not updated for."""
    unknown = {e.kind for e in entries} - _KNOWN_OP_KINDS
    if unknown:
        raise ValueError(f"{phase_name}: op program has unknown op kind(s) {sorted(unknown)}")

    def count(kind: str) -> int:
        return sum(1 for e in entries if e.kind == kind)

    if phase_name in _DARK_PHASES:
        for kind in ("PollDataReady", "BulkIn", "BulkDone"):
            n = count(kind)
            if n != 1:
                raise ValueError(
                    f"{phase_name}: expected exactly one {kind} op, got {n}")
    elif phase_name in _GAIN_PHASES:
        for kind in ("PollDataReady", "BulkIn"):
            n = count(kind)
            if n < 1:
                raise ValueError(
                    f"{phase_name}: expected at least one {kind} op, got {n}")
        n_done = count("BulkDone")
        if n_done != 1:
            raise ValueError(
                f"{phase_name}: expected exactly one BulkDone op, got {n_done}")
    elif phase_name in _SHADING_MEASURE_PHASES:
        n_poll = count("PollDataReady")
        if n_poll != 1:
            raise ValueError(
                f"{phase_name}: expected exactly one PollDataReady op, got {n_poll}")
        n_bulk_in = count("BulkIn")
        if n_bulk_in < 1:
            raise ValueError(
                f"{phase_name}: expected at least one BulkIn op, got {n_bulk_in}")
        n_bulk_out = count("BulkOut")
        if n_bulk_out != 0:
            raise ValueError(
                f"{phase_name}: expected no BulkOut op, got {n_bulk_out}")
        if phase_name == "cal_shading_measure":
            # W2 (reg 0x100 polled, not merely read) is captured on the
            # plain3600 profile only -- every dual-light profile's own
            # capture reads that register once as a plain `cr` (already
            # "Read"), never a coalesced `poll` (docs/sane-hook4-
            # shading.md section 3: "the only place the vendor polls
            # that register").  So the invariant that holds across every
            # profile is "at most one", not "exactly one".
            n_class = count("PollClass")
            if n_class > 1:
                raise ValueError(
                    f"{phase_name}: expected at most one PollClass op, got {n_class}")
    elif phase_name in _SHADING_UPLOAD_PHASES:
        n_bulk_out = count("BulkOut")
        if n_bulk_out < 1:
            raise ValueError(
                f"{phase_name}: expected at least one BulkOut op, got {n_bulk_out}")
        for kind in ("BulkIn", "PollDataReady", "PollClass"):
            n = count(kind)
            if n != 0:
                raise ValueError(
                    f"{phase_name}: expected no {kind} op, got {n}")


def op_injections_for(phase, entries: list[OpEntry],
                      base_op_index: int = 0) -> list[tuple[str, int, int]]:
    """Derive an op program's OpInjection entries -- (name, op_index,
    byte_offset), LOCAL to this program -- from `phase.injections`'s
    "byte" specs, checked against the op program itself rather than
    assumed (docs/sane-hook3-gain.md section 6, part A/2). `entries` is
    one-to-one with `phase.ops[base_op_index:base_op_index+len(entries)]`
    by construction (decode_ops emits exactly one OpEntry per captured
    op, in order; `base_op_index` is nonzero only for the second half of
    a split program -- docs/sane-hook4-shading.md section 6). A spec
    whose op_index falls outside that range belongs to the OTHER half of
    a split phase and is silently skipped here (present in the other
    call for that half instead).

    Only cal_gain_check_a carries any among the phases in scope here
    (gain_r/gain_g/gain_b -> ops 0/2/4, byte 5); every other program's
    list is empty."""
    out: list[tuple[str, int, int]] = []
    for name, spec in phase.injections.items():
        if spec[0] != "byte":
            continue
        _, idx, off = spec
        if not (base_op_index <= idx < base_op_index + len(entries)):
            continue
        local_idx = idx - base_op_index
        if entries[local_idx].kind != "Write":
            raise ValueError(
                f"{phase.name}: op injection {name!r} targets op {idx}, "
                f"which is not a Write in the op program")
        if not (0 <= off < entries[local_idx].length):
            raise ValueError(
                f"{phase.name}: op injection {name!r} targets byte {off}, "
                f"outside op {idx}'s {entries[local_idx].length} B payload")
        if off % 2 == 0:
            raise ValueError(
                f"{phase.name}: op injection {name!r} targets byte {off}, "
                f"a register number rather than a value")
        out.append((name, local_idx, off))
    out.sort(key=lambda t: (t[1], t[0]))
    return out


def op_bulk_injections_for(phase, entries: list[OpEntry],
                           base_op_index: int = 0) -> list[tuple[str, int, int]]:
    """Derive an op program's OpBulkInjection entries -- (name,
    first_op, last_op), LOCAL to this program (inclusive, re-based by
    `base_op_index` the same way op_injections_for's are) -- from
    `phase.injections`'s "bo" specs: the shading-table uploads (docs/
    sane-hook4-shading.md section 6). A spec whose indices fall outside
    `[base_op_index, base_op_index+len(entries))` belongs to the OTHER
    half of a split phase and is silently skipped (cal_shading_upload
    has one such spec; cal_shading_verify's belongs entirely to the
    upload half). Asserts the named indices are a contiguous run of
    BulkOut ops in the op program -- the runner slices the injected
    payload across them in order, so a gap or a non-BulkOut op in the
    middle would silently misroute bytes."""
    out: list[tuple[str, int, int]] = []
    for name, spec in phase.injections.items():
        if spec[0] != "bo":
            continue
        _, idxs = spec
        if not all(base_op_index <= i < base_op_index + len(entries) for i in idxs):
            continue
        local = sorted(i - base_op_index for i in idxs)
        if local != list(range(local[0], local[0] + len(local))):
            raise ValueError(
                f"{phase.name}: bulk injection {name!r} op indices {idxs} "
                f"are not consecutive")
        first, last = local[0], local[-1]
        for i in range(first, last + 1):
            if entries[i].kind != "BulkOut":
                raise ValueError(
                    f"{phase.name}: bulk injection {name!r} targets op "
                    f"{i + base_op_index}, which is not a BulkOut in the "
                    f"op program")
        out.append((name, first, last))
    out.sort(key=lambda t: t[1])
    return out


def strip_bulk_injected_data(entries: list[OpEntry],
                             bulk_injections: list[tuple[str, int, int]]) -> None:
    """Clear the captured payload of every BulkOut op a bulk injection
    covers, in place -- `entries` is LOCAL and `bulk_injections`' indices
    already are too, so no re-basing is needed here. The captured chunk
    is the reference unit's own shading table and must never be written
    to another unit (the same principle as a register injection); `len`
    is untouched (it still comes from the captured op, `emit_op_program`
    just has nothing to put in the byte blob for it -- see
    `emit_op_program`'s `nullptr` rule below). A BulkOut NOT named by any
    bulk injection is left alone and keeps its captured payload."""
    for _, first, last in bulk_injections:
        for i in range(first, last + 1):
            entries[i].data = b""


def emit_op_program(key: str, phase_name: str, entries: list[OpEntry],
                    injections: list[tuple[str, int, int]],
                    bulk_injections: list[tuple[str, int, int]],
                    c: list[str]) -> tuple[str, str, int, str, int]:
    """Emit one OpProgram's backing arrays (a byte blob for every op's
    `data`, the Op array, and -- if any -- the OpInjection and
    OpBulkInjection arrays) and return (ops array identifier, injections
    array identifier or "nullptr", injection count, bulk injections array
    identifier or "nullptr", bulk injection count)."""
    base = c_ident(key.upper(), phase_name.upper())
    blob = bytearray()
    offsets: list[int] = []
    for e in entries:
        offsets.append(len(blob))
        blob.extend(e.data)

    data_name = f"{base}_OPS_DATA"
    if blob:
        c.append(f"static const std::uint8_t {data_name}[{len(blob)}] = {{")
        c.append(fmt_bytes(bytes(blob)))
        c.append("};\n")

    ops_name = f"{base}_OPS"
    c.append(f"/* {key} / {phase_name}: op program, {len(entries)} ops "
             f"(docs/sane-hook2-offset.md section 6, "
             f"docs/sane-hook3-gain.md section 6, "
             f"docs/sane-hook4-shading.md section 6). */")
    c.append(f"static const Op {ops_name}[{len(entries)}] = {{")
    for e, off in zip(entries, offsets):
        data_expr = f"{data_name} + {off}" if e.data else "nullptr"
        c.append(f"    {{OpKind::{e.kind}, 0x{e.request:02x}, "
                 f"0x{e.value:04x}, 0x{e.index:04x}, {data_expr}, "
                 f"{e.length}, {e.dur_ms}}},")
    c.append("};\n")

    if injections:
        inj_name = f"{base}_OPS_INJ"
        c.append(f"/* Computed values patched into {ops_name} at run time "
                 f"(docs/sane-hook3-gain.md section 6). */")
        c.append(f"static const OpInjection {inj_name}[{len(injections)}] = {{")
        for name, op_idx, byte_off in injections:
            c.append(f'    {{"{name}", {op_idx}, {byte_off}}},')
        c.append("};\n")
    else:
        inj_name = "nullptr"

    if bulk_injections:
        bulk_inj_name = f"{base}_OPS_BULK_INJ"
        c.append(f"/* Bulk payloads patched into {ops_name} at run time "
                 f"(docs/sane-hook4-shading.md section 6). */")
        c.append(f"static const OpBulkInjection {bulk_inj_name}"
                 f"[{len(bulk_injections)}] = {{")
        for name, first_op, last_op in bulk_injections:
            c.append(f'    {{"{name}", {first_op}, {last_op}}},')
        c.append("};\n")
    else:
        bulk_inj_name = "nullptr"

    return ops_name, inj_name, len(injections), bulk_inj_name, len(bulk_injections)


def c_ident(*parts: str) -> str:
    return "_".join(p.replace("-", "_") for p in parts)


def fmt_pairs(pairs: list[tuple[int, int]], indent: str = "    ") -> str:
    """Four pairs per line, hex, so a diff against a capture stays readable."""
    out, line = [], []
    for reg, val in pairs:
        line.append(f"{{0x{reg:02x}, 0x{val:02x}}}")
        if len(line) == 4:
            out.append(indent + ", ".join(line) + ",")
            line = []
    if line:
        out.append(indent + ", ".join(line) + ",")
    return "\n".join(out)


def fmt_bytes(data: bytes, indent: str = "    ") -> str:
    out, line = [], []
    for b in data:
        line.append(f"0x{b:02x}")
        if len(line) == 12:
            out.append(indent + ", ".join(line) + ",")
            line = []
    if line:
        out.append(indent + ", ".join(line) + ",")
    return "\n".join(out)


def emit() -> tuple[str, str]:
    """Return (header, source) for the generated tables."""
    h: list[str] = []
    c: list[str] = []

    banner = (
        "/* GENERATED by tools/gen_sane_tables.py from of135i/tables*.py --\n"
        " * do not edit. Regenerate after any table change.\n"
        " *\n"
        " * Register values captured from the vendor driver and verified\n"
        " * byte-exact against USB traces (docs/protocol-notes.md); these are\n"
        " * interoperability facts, not vendor code. Reads and polls are not\n"
        " * reproduced here: the backend polls explicitly with timeouts\n"
        " * (docs/sane-port.md, decision 3).\n"
        " */\n")

    h.append(banner)
    h.append("#ifndef BACKEND_GENESYS_GL126_TABLES_H")
    h.append("#define BACKEND_GENESYS_GL126_TABLES_H\n")
    h.append("#include <cstddef>")
    h.append("#include <cstdint>\n")
    h.append("namespace genesys {")
    h.append("namespace gl126 {\n")
    h.append("/** One register write: the chip takes [reg][val] byte pairs. */")
    h.append("struct RegPair {")
    h.append("    std::uint8_t reg;")
    h.append("    std::uint8_t val;")
    h.append("};\n")
    h.append("/** A value the hook must compute and patch in before writing.")
    h.append(" *  `index` addresses the phase's pair array; the captured value")
    h.append(" *  standing there belongs to the reference unit and must not be")
    h.append(" *  written as-is. */")
    h.append("struct RegInjection {")
    h.append("    const char* name;")
    h.append("    std::size_t index;")
    h.append("};\n")
    h.append("/** A buffer transfer: descriptor address plus payload length. */")
    h.append("struct BufWrite {")
    h.append("    std::uint32_t addr;")
    h.append("    std::uint32_t length;")
    h.append("};\n")
    h.append("/** One phase of the captured sequence. */")
    h.append("struct Phase {")
    h.append("    const char* name;")
    h.append("    const RegPair* regs;")
    h.append("    std::size_t reg_count;")
    h.append("    const RegInjection* injections;")
    h.append("    std::size_t injection_count;")
    h.append("    const BufWrite* buffers;")
    h.append("    std::size_t buffer_count;")
    h.append("};\n")
    h.append("/** An op-program transfer kind (docs/sane-hook2-offset.md")
    h.append(" *  section 6, docs/sane-hook4-shading.md section 6);")
    h.append(" *  gl126_ops.cpp is the runner that executes these. */")
    h.append("enum class OpKind : std::uint8_t {")
    h.append("    Write,          /* control write: register batch, 0x82 buffer")
    h.append("                       descriptor, or 0x8c write */")
    h.append("    AckRead,        /* control read, 1 B, must be 0x55 */")
    h.append("    Read,           /* control read, logged only (provenance) */")
    h.append("    PollDataReady,  /* poll reg 0x101 until bit 0x01 (DATAENB) sets */")
    h.append("    PollClass,      /* poll reg 0x100 until (reply[0] & 0xf0) matches")
    h.append("                       the captured settled value's upper nibble */")
    h.append("    BulkIn,         /* bulk IN of `len` bytes from EP 0x81 */")
    h.append("    BulkOut,        /* bulk OUT of `len` bytes to EP 0x02 */")
    h.append("    BulkDone,       /* control read after a bulk transfer, logged only */")
    h.append("};\n")
    h.append("/** One op-program transfer. `data` is the write payload (Write, and a")
    h.append(" *  BulkOut NOT covered by a bulk injection) or the captured reply")
    h.append(" *  (AckRead/Read/PollDataReady/PollClass/BulkDone, provenance only --")
    h.append(" *  the runner does not require a live reply to match it, except")
    h.append(" *  AckRead's fixed 0x55, PollDataReady's bit 0x01 and PollClass's")
    h.append(" *  upper nibble). `data` is nullptr for BulkIn, and for a BulkOut a")
    h.append(" *  bulk injection covers -- its captured chunk is the reference")
    h.append(" *  unit's own calibration data and must not be kept; `len` still")
    h.append(" *  gives the wire length. */")
    h.append("struct Op {")
    h.append("    OpKind kind;")
    h.append("    std::uint8_t request;    /* bRequest; 0 for BulkIn/BulkOut */")
    h.append("    std::uint16_t value;     /* wValue */")
    h.append("    std::uint16_t index;     /* wIndex */")
    h.append("    const std::uint8_t* data;")
    h.append("    std::uint16_t len;       /* Write/reads: byte length; BulkIn/BulkOut: bulk length */")
    h.append("    std::uint16_t dur_ms;    /* captured poll duration, ms (0 otherwise) */")
    h.append("};\n")
    h.append("/** A value the op-program runner must compute and patch into a")
    h.append(" *  Write op's payload before sending it (docs/sane-hook3-gain.md")
    h.append(" *  section 6/Part B) -- gl126_ops.cpp's run_program() takes a")
    h.append(" *  name -> byte map and refuses (OpsFailure::MissingInjection,")
    h.append(" *  before any transfer) if a name here is not in it. `op_index`")
    h.append(" *  addresses the OpProgram's own `ops` array (one-to-one with the")
    h.append(" *  captured ops); `byte_offset` is the byte inside that op's")
    h.append(" *  payload -- always odd (a value byte, never a register")
    h.append(" *  number). The captured value standing there belongs to the")
    h.append(" *  reference unit and must not be written as-is. */")
    h.append("struct OpInjection {")
    h.append("    const char* name;")
    h.append("    std::size_t op_index;")
    h.append("    std::size_t byte_offset;")
    h.append("};\n")
    h.append("/** A payload the op-program runner must compute and split across a")
    h.append(" *  run of consecutive BulkOut ops before sending them (docs/sane-")
    h.append(" *  hook4-shading.md section 6) -- run_program() takes a name ->")
    h.append(" *  byte vector map and refuses (OpsFailure::MissingInjection, before")
    h.append(" *  any transfer) if a name here is not in it, or")
    h.append(" *  OpsFailure::BadInjection if the value is longer than the ops'")
    h.append(" *  combined length. `first_op`/`last_op` address the OpProgram's own")
    h.append(" *  `ops` array, INCLUSIVE, and are always a contiguous run of")
    h.append(" *  BulkOut ops. A shorter value is zero-padded to the combined")
    h.append(" *  length before slicing, exactly of135i/tables.py's Phase.patched()")
    h.append(" *  rule for a \"bo\" injection. */")
    h.append("struct OpBulkInjection {")
    h.append("    const char* name;")
    h.append("    std::size_t first_op;")
    h.append("    std::size_t last_op;")
    h.append("};\n")
    h.append("/** An ordered op program for one phase -- prep/afe_base/cal_dark_a/")
    h.append(" *  cal_dark_b (SANE hook 2), cal_white/cal_gain_check_a/")
    h.append(" *  cal_gain_check_b (SANE hook 3, docs/sane-hook3-gain.md) and")
    h.append(" *  cal_shading_measure/cal_shading_upload/cal_shading_verify/")
    h.append(" *  cal_shading_verify_upload (SANE hook 4, docs/sane-hook4-")
    h.append(" *  shading.md -- the last two are one captured phase,")
    h.append(" *  `cal_shading_verify`, split at its own `split_at`). */")
    h.append("struct OpProgram {")
    h.append("    const char* name;")
    h.append("    const Op* ops;")
    h.append("    std::size_t count;")
    h.append("    const OpInjection* injections;  /* nullptr/0 when none */")
    h.append("    std::size_t injection_count;")
    h.append("    const OpBulkInjection* bulk_injections;  /* nullptr/0 when none */")
    h.append("    std::size_t bulk_injection_count;")
    h.append("};\n")
    h.append("/** One scan profile: a resolution and its phase sequence. */")
    h.append("struct Profile {")
    h.append("    const char* name;")
    h.append("    unsigned dpi;")
    h.append("    unsigned image_width;      /* px per line, RGB16LE */")
    h.append("    unsigned chunk_len;        /* bytes per image bulk-read */")
    h.append("    unsigned lines_per_chunk;")
    h.append("    unsigned shading_lines;")
    h.append("    unsigned shading_upload_len;")
    h.append("    const std::uint8_t* slope_position;")
    h.append("    std::size_t slope_position_len;")
    h.append("    const std::uint8_t* slope_scan;")
    h.append("    std::size_t slope_scan_len;")
    h.append("    const Phase* phases;")
    h.append("    std::size_t phase_count;")
    h.append("    const OpProgram* programs;  /* prep/afe_base/cal_dark_a/cal_dark_b/")
    h.append("                                   cal_white/cal_gain_check_a/cal_gain_check_b/")
    h.append("                                   cal_shading_measure/cal_shading_upload/")
    h.append("                                   cal_shading_verify/cal_shading_verify_upload */")
    h.append("    std::size_t program_count;")
    h.append("};\n")

    c.append(banner)
    c.append(f'#include "{STEM}.h"\n')
    c.append("namespace genesys {")
    c.append("namespace gl126 {\n")

    # ---- flat register tables from tables_base -------------------------
    for name, pairs, doc in [
        ("BASE_INIT", tables_base.BASE_INIT_PAIRS,
         "Power-on base register table, written once per session."),
        ("AFE_BASE", tables_base.AFE_BASE_PAIRS,
         "AFE bring-up values that follow the base table."),
        ("COLD_INIT", tables_base.COLD_INIT_PAIRS,
         "Cold-start table (reg 0x01 lacks the ready bit 0x20)."),
        ("LOADER_SPEED", tables_base.LOADER_SPEED_PAIRS,
         "Loader motor speed registers used by the magazine phases."),
    ]:
        h.append(f"/** {doc} */")
        h.append(f"extern const RegPair {name}[{len(pairs)}];")
        h.append(f"constexpr std::size_t {name}_COUNT = {len(pairs)};\n")
        c.append(f"/* {doc} */")
        c.append(f"const RegPair {name}[{len(pairs)}] = {{")
        c.append(fmt_pairs(list(pairs)))
        c.append("};\n")

    # ---- slope tables, deduplicated ------------------------------------
    # The same 512 B payload is written to several addresses and shared
    # between profiles; emitting it once keeps the object small and makes
    # an accidental divergence visible as a new array.
    slopes: dict[bytes, str] = {}

    def slope_name(payload: bytes, suggested: str) -> str:
        if payload in slopes:
            return slopes[payload]
        ident = f"SLOPE_{suggested.upper()}"
        n = 2
        while ident in slopes.values():
            ident = f"SLOPE_{suggested.upper()}_{n}"
            n += 1
        slopes[payload] = ident
        h.append(f"extern const std::uint8_t {ident}[{len(payload)}];")
        h.append(f"constexpr std::size_t {ident}_LEN = {len(payload)};\n")
        c.append(f"const std::uint8_t {ident}[{len(payload)}] = {{")
        c.append(fmt_bytes(payload))
        c.append("};\n")
        return ident

    slope_name(tables_base.SLOPE_TABLE_LOADER, "loader")

    # ---- profiles -------------------------------------------------------
    profile_entries: list[str] = []
    for key, mod, dpi, doc in PROFILES:
        pos = slope_name(mod.SLOPE_TABLE_POSITION, f"{key}_position")
        scan = slope_name(mod.SLOPE_TABLE_SCAN, f"{key}_scan")

        phase_entries: list[str] = []
        for phase in mod.PHASES:
            pt = decode_phase(phase)
            base = c_ident(key.upper(), pt.name.upper())

            if pt.pairs:
                c.append(f"/* {key} / {pt.name}: {len(pt.pairs)} register writes "
                         f"from {pt.op_count} captured ops "
                         f"({pt.read_count} reads not reproduced). */")
                c.append(f"static const RegPair {base}_REGS[{len(pt.pairs)}] = {{")
                c.append(fmt_pairs(pt.pairs))
                c.append("};\n")
                regs_ref = f"{base}_REGS"
            else:
                regs_ref = "nullptr"

            if pt.injections:
                c.append(f"/* Computed values patched into {base}_REGS. */")
                c.append(f"static const RegInjection {base}_INJ"
                         f"[{len(pt.injections)}] = {{")
                for name, idx in sorted(pt.injections.items(), key=lambda kv: kv[1]):
                    reg, val = pt.pairs[idx]
                    c.append(f'    {{"{name}", {idx}}},'
                             f'   /* reg 0x{reg:02x}, captured 0x{val:02x} */')
                c.append("};\n")
                inj_ref = f"{base}_INJ"
            else:
                inj_ref = "nullptr"

            if pt.buffers:
                c.append(f"/* Buffer transfers in {key} / {pt.name}. */")
                c.append(f"static const BufWrite {base}_BUFS[{len(pt.buffers)}] = {{")
                for b in pt.buffers:
                    note = ""
                    if b.payload and b.payload in slopes:
                        note = f"   /* {slopes[b.payload]} */"
                    elif not b.payload:
                        note = "   /* payload computed at run time */"
                    c.append(f"    {{0x{b.addr:08x}, {b.length}}},{note}")
                c.append("};\n")
                bufs_ref = f"{base}_BUFS"
            else:
                bufs_ref = "nullptr"

            phase_entries.append(
                f'    {{"{pt.name}", {regs_ref}, {len(pt.pairs)}, '
                f'{inj_ref}, {len(pt.injections)}, '
                f'{bufs_ref}, {len(pt.buffers)}}},')

        c.append(f"static const Phase {key.upper()}_PHASES"
                 f"[{len(phase_entries)}] = {{")
        c.extend(phase_entries)
        c.append("};\n")

        # ---- op programs: hook 2's prep/afe_base/cal_dark_a/cal_dark_b
        # (docs/sane-hook2-offset.md section 6), hook 3's cal_white/
        # cal_gain_check_a/cal_gain_check_b (docs/sane-hook3-gain.md
        # section 6) and hook 4's cal_shading_measure/cal_shading_upload/
        # cal_shading_verify/cal_shading_verify_upload (docs/sane-hook4-
        # shading.md section 6; the last two come from splitting the one
        # captured cal_shading_verify phase at its own split_at).
        program_entries: list[str] = []
        for phase in mod.PHASES:
            if phase.name in OP_PROGRAM_PHASES:
                entries = decode_ops(phase)
                validate_op_program(phase.name, entries)
                injections = op_injections_for(phase, entries)
                bulk_injections = op_bulk_injections_for(phase, entries)
                strip_bulk_injected_data(entries, bulk_injections)
                ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                    key, phase.name, entries, injections, bulk_injections, c)
                program_entries.append(
                    f'    {{"{phase.name}", {ops_name}, {len(entries)}, '
                    f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')
            elif phase.name == _SPLIT_PHASE:
                if phase.split_at is None:
                    raise ValueError(
                        f"{phase.name}: split phase has no split_at")
                all_entries = decode_ops(phase)
                halves = (
                    (all_entries[:phase.split_at], 0),
                    (all_entries[phase.split_at:], phase.split_at),
                )
                for prog_name, (entries, base_idx) in zip(_SPLIT_PROGRAM_NAMES, halves):
                    validate_op_program(prog_name, entries)
                    injections = op_injections_for(phase, entries, base_idx)
                    bulk_injections = op_bulk_injections_for(phase, entries, base_idx)
                    strip_bulk_injected_data(entries, bulk_injections)
                    ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                        key, prog_name, entries, injections, bulk_injections, c)
                    program_entries.append(
                        f'    {{"{prog_name}", {ops_name}, {len(entries)}, '
                        f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')

        progs_name = f"{key.upper()}_PROGRAMS"
        c.append(f"static const OpProgram {progs_name}[{len(program_entries)}] = {{")
        c.extend(program_entries)
        c.append("};\n")

        profile_entries.append(
            f'    {{"{key}", {dpi}, {getattr(mod, "IMAGE_WIDTH", 0)}, '
            f'{getattr(mod, "IMAGE_CHUNK_LEN", 0)}, '
            f'{getattr(mod, "LINES_PER_CHUNK", 0)}, '
            f'{getattr(mod, "SHADING_LINES", 0)}, '
            f'{getattr(mod, "SHADING_UPLOAD_LEN", 0)}, '
            f'{pos}, {pos}_LEN, {scan}, {scan}_LEN, '
            f'{key.upper()}_PHASES, {len(phase_entries)}, '
            f'{progs_name}, {len(program_entries)}}},   /* {doc} */')

    # ---- magazine phases (no dpi) ---------------------------------------
    load_entries: list[str] = []
    for phase in tables_load.PHASES:
        pt = decode_phase(phase)
        base = c_ident("LOAD", pt.name.upper())
        if pt.pairs:
            c.append(f"/* magazine / {pt.name}: {len(pt.pairs)} register writes "
                     f"from {pt.op_count} captured ops. */")
            c.append(f"static const RegPair {base}_REGS[{len(pt.pairs)}] = {{")
            c.append(fmt_pairs(pt.pairs))
            c.append("};\n")
            regs_ref = f"{base}_REGS"
        else:
            regs_ref = "nullptr"
        bufs_ref = "nullptr"
        if pt.buffers:
            c.append(f"static const BufWrite {base}_BUFS[{len(pt.buffers)}] = {{")
            for b in pt.buffers:
                note = f"   /* {slopes[b.payload]} */" if b.payload in slopes else ""
                c.append(f"    {{0x{b.addr:08x}, {b.length}}},{note}")
            c.append("};\n")
            bufs_ref = f"{base}_BUFS"
        load_entries.append(
            f'    {{"{pt.name}", {regs_ref}, {len(pt.pairs)}, '
            f'nullptr, 0, {bufs_ref}, {len(pt.buffers)}}},')

    h.append("/** The magazine phases (OPEN / JOG / LOAD), in order. */")
    h.append(f"extern const Phase MAGAZINE_PHASES[{len(load_entries)}];")
    h.append(f"constexpr std::size_t MAGAZINE_PHASE_COUNT = {len(load_entries)};\n")
    c.append(f"const Phase MAGAZINE_PHASES[{len(load_entries)}] = {{")
    c.extend(load_entries)
    c.append("};\n")

    h.append("/** Every scan profile, indexed by PROFILE_COUNT. */")
    h.append(f"extern const Profile PROFILES[{len(profile_entries)}];")
    h.append(f"constexpr std::size_t PROFILE_COUNT = {len(profile_entries)};\n")
    c.append(f"const Profile PROFILES[{len(profile_entries)}] = {{")
    c.extend(profile_entries)
    c.append("};\n")

    h.append("} // namespace gl126")
    h.append("} // namespace genesys\n")
    h.append("#endif // BACKEND_GENESYS_GL126_TABLES_H")
    c.append("} // namespace gl126")
    c.append("} // namespace genesys")

    return "\n".join(h) + "\n", "\n".join(c) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if the checked-in output is out of date")
    args = ap.parse_args(argv)

    header, source = emit()
    h_path = OUT_DIR / f"{STEM}.h"
    c_path = OUT_DIR / f"{STEM}.cpp"

    if args.check:
        for path, want in ((h_path, header), (c_path, source)):
            if not path.exists():
                print(f"missing generated file: {path}", file=sys.stderr)
                return 1
            if path.read_text() != want:
                print(f"{path} is out of date; run tools/gen_sane_tables.py",
                      file=sys.stderr)
                return 1
        print("generated SANE tables are up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    h_path.write_text(header)
    c_path.write_text(source)
    print(f"wrote {h_path} ({len(header)} B)")
    print(f"wrote {c_path} ({len(source)} B)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
