#!/usr/bin/env python3
"""Compile the vendor magazine-load sequence into of135i/tables_load.py.

Source: the 2026-09-05 clean standalone vendor load
(traces/20260905-vendor-clean-load.trace.json.gz, ops 194-260; Test 14
in docs/test-log.md): QuickScan in the Win11 VM, magazine taken fully
out and reinserted fresh to the stop, captured with usbmon on the
Linux host. The slice is: loader-sensor ack (reg 0x32), the ENGAGING
feed (mode 0x18, FEEDL 0x1a22) programmed as the vendor programs it --
four register batches, 126 registers incl. 0x01=0x22, 0x03=0x30,
0x15=0x90, 0x35=0xbb -- with the loader slope tables and the GO, the
slow prescan traverse (mode 0x1c, FEEDL 71490) and the first idle
housekeeping cycle after it (0x36/0x3a/0x33/0x32 writes, status reads).

Why this source: the previous table was cut from the 2026-09-02
eject-from-loaded capture (ops 291-640), where the load ran AFTER the
app-start jog with the registers already set, so its feed was a bare
19-register batch executing with the base table's 0x35=0xfb. On the
real scanner the transport ran but the cassette never engaged (Tests
11b/12b/13). Never regenerate from a capture whose load is not
standalone.

Regenerate with:
    .venv/bin/python tools/gen_load_table.py

tests/test_safety.py checks the generated module against the trace
slice byte for byte when the trace is present, and that the feed
carries the full register block.
"""

from __future__ import annotations

import gzip
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(REPO / "tools"))

from gen_tables import make_op  # noqa: E402

TRACE = REPO / "traces" / "20260905-vendor-clean-load.trace.json.gz"
OUT = REPO / "of135i" / "tables_load.py"
OP_RANGE = (194, 260)


def load_ops() -> list[dict]:
    raw = json.load(gzip.open(TRACE, "rt"))
    return [make_op(o) for o in raw[OP_RANGE[0]:OP_RANGE[1]]]


def render_op(op: dict, indent: str = "    ") -> str:
    args = [repr(op["kind"]), repr(round(op["dt"], 4))]
    kw = []
    if op["bm"]:
        kw.append(f'bm={op["bm"]:#04x}')
    if op["br"]:
        kw.append(f'br={op["br"]:#04x}')
    if op["wv"]:
        kw.append(f'wv={op["wv"]:#06x}')
    if op["wi"]:
        kw.append(f'wi={op["wi"]:#06x}')
    if op["data"]:
        kw.append(f"data=bytes.fromhex({op['data'].hex()!r})")
    if op["length"]:
        kw.append(f'length={op["length"]}')
    if op["resp"]:
        kw.append(f"resp=bytes.fromhex({op['resp'].hex()!r})")
    if op["dur"]:
        kw.append(f'dur={round(op["dur"], 4)}')
    return f"{indent}Op({', '.join(args + kw)}),"


def main() -> int:
    ops = load_ops()
    lines = [
        '"""Vendor magazine-load sequence for the of135i driver.',
        "",
        "AUTO-GENERATED by tools/gen_load_table.py from",
        f"traces/{TRACE.name} ops {OP_RANGE[0]}-{OP_RANGE[1]} -- do not edit by hand.",
        "",
        "The vendor app's standalone insert flow (Test 14, docs/test-log.md):",
        "magazine taken fully out and reinserted fresh to the stop, then",
        "loader-sensor ack (reg 0x32), the engaging feed (mode 0x18, FEEDL",
        "0x1a22) programmed with the vendor's full register block (four",
        "batches, 126 registers incl. 0x01=0x22, 0x03=0x30, 0x15=0x90,",
        "0x35=0xbb) plus loader slope tables and GO, the slow prescan",
        "traverse (mode 0x1c, FEEDL 71490) and the first idle housekeeping",
        "cycle. Replayed verbatim by Scanner.load_magazine() with the same",
        "executor semantics as every other phase (device.py _exec_ops),",
        "after initialize() and behind the start-state guard (safety.py).",
        "The two motor-completion polls are checked with the masked",
        "completion test (device.load_status_matches): state class AND",
        "loader-sensor bit 0x08, not an exact status word.",
        "",
        "History: the previous table (eject-from-loaded ops 291-640) ran",
        "the feed as a bare 19-register batch and never engaged the",
        "cassette on hardware (Tests 11b/12b/13). This table is NOT yet",
        "hardware-verified as a load.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from .tables import Op, Phase",
        "",
        f"OP_RANGE = {OP_RANGE!r}",
        "",
        "LOAD = Phase(",
        '    name="load",',
        f"    op_range={OP_RANGE!r},",
        "    ops=[",
    ]
    lines.extend(render_op(op, indent="        ") for op in ops)
    lines.extend([
        "    ],",
        ")",
        "",
        "PHASES = [LOAD]",
    ])
    OUT.write_text("\n".join(lines) + "\n")
    kinds: dict[str, int] = {}
    for op in ops:
        kinds[op["kind"]] = kinds.get(op["kind"], 0) + 1
    print(f"wrote {OUT} ({len(ops)} ops: {kinds})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
