#!/usr/bin/env python3
"""Emit the GL126 register tables as C++ for the SANE genesys backend.

Stage 2 of docs/sane-port.md: the Python driver replays captured phases
verbatim; the backend writes the same registers from generated tables.
This tool is the bridge. It reads `of135i/tables*.py` -- the single source
of truth, verified byte-exact against the USB captures -- and writes
`sane/gl126_tables.{h,cpp}`. Nothing here is hand-maintained: regenerate
after any table change, never edit the output.

What a phase becomes
--------------------
Each `Phase` is an ordered op stream (control writes, bulk writes, reads).
Only the writes carry state the backend must reproduce:

  * `cw` 0x40/0x04 wValue=0x0083 -- a register batch, `[reg][val]` pairs.
    These are flattened, in order, into one pair array per phase.
  * `cw` 0x40/0x04 wValue=0x0082 wIndex=1 -- a buffer descriptor,
    `[addr u32][len u32]`, followed by the `bo` ops carrying the payload.
    Emitted as an address/length record; the payload is either a slope
    table (emitted once, by name) or computed at run time (shading).
  * `cw` 0x40/0x0c -- end-of-access, emitted as its wValue/wIndex.

Reads and polls are deliberately NOT emitted into the pair tables.
Decision 3 in docs/sane-port.md: the C++ hooks poll explicitly with
timeouts rather than replaying the capture's pacing, so a captured read
is provenance, not behaviour. The generator counts them so the header can
state how many ops each phase covered.

Op programs (docs/sane-hook2-offset.md section 6)
--------------------------------------------------
The pair tables above lose three things hook 2 needs: transfer
boundaries, interleaving (a read between two writes), and the bulk
IN/OUT dance around a calibration read. For the phases hook 2/3/4 run
(`prep`, `afe_base`, `cal_dark_a`, `cal_dark_b`, `cal_white`,
`cal_gain_check_a`, `cal_gain_check_b`, `cal_shading_measure`,
`cal_shading_upload`, `cal_shading_verify`), every profile also gets one
or more ordered `OpProgram`s: one `Op` per captured transfer, in
captured order, kept one-to-one with `phase.ops` (or a contiguous slice
of it -- see "Split programs" below). The mapping (see `decode_ops`):

  * `cw`                                             -> `Write`
  * `cr` br=0x0c wv=0x008e wi=0x0020 length=1         -> `AckRead`
  * `cr` br=0x0c wv=0x008e wi=0x0018 length=1         -> `BulkDone`
  * `poll` wv=0x018e wi=0x0122 and resp[0] & 0x01     -> `PollDataReady`
  * `poll` wv=0x018e wi=0x0022 (reg 0x100)            -> `PollClass`
    (docs/sane-hook4-shading.md section 3, W2 -- the only site the
    vendor polls that register; the settled reply is kept as `data` and
    the runner waits for an upper-nibble class match against it)
  * every other `cr`/`poll`                           -> `Read`
  * `bi`                                              -> `BulkIn`
  * `bo`                                              -> `BulkOut` (bulk
    OUT of `len(op.data)` bytes to EP 0x02). A BulkOut COVERED by a bulk
    injection (see "Injection points" below) is emitted with `data =
    nullptr`: its captured chunk is the reference unit's own shading
    table -- calibration data of ONE unit -- and must never be written
    to another, the same principle as a register injection. Only the
    `len` survives. A BulkOut NOT covered by any injection keeps its
    captured payload as `data` (provenance/default); none of the phases
    emitted today has one -- the slope-table uploads in position/scan
    will, later.

`Read`/`AckRead`/`PollDataReady`/`PollClass`/`BulkDone` always carry the
captured reply as `data` (provenance, mirrored into a generated byte
blob); `Write` always carries its payload the same way; `BulkOut` does
too, EXCEPT when a bulk injection covers it (see above). `gl126_ops.cpp`
(the runner) polls `PollDataReady`/`PollClass` for real and fails closed
on a bad `AckRead`, a short `BulkIn`, or a short `BulkOut`; see
docs/sane-hook2-offset.md section 3 and docs/sane-hook4-shading.md
section 3.

Split programs (docs/sane-hook4-shading.md section 6)
-------------------------------------------------------
`cal_shading_verify` genuinely re-measures then re-uploads a table
computed from that measurement, so it cannot run as one program: its
own `phase.split_at` names the local op index of the re-upload's buffer
descriptor. It is emitted as TWO programs, `cal_shading_verify` (ops
`[0, split_at)`, the re-measurement) and `cal_shading_verify_upload`
(ops `[split_at, end)`, the re-upload), op indices in the second
re-based to 0 -- injection op indices are adjusted the same way.

Injection points
----------------
A phase's `injections` name the bytes that carry computed values (gain
codes, offset codes, FEEDL, line count, shading tables) instead of their
captured ones. Writing the captured byte instead would scan with
another unit's calibration, so each one is emitted as a named index (or
range of indices, for a bulk payload) into the phase's pair array. The
backend patches those entries before writing; it must not rely on the
captured value.

The same `injections` dict also feeds an OpInjection table on any phase
that gets an op program (see above): cal_gain_check_a's gain_r/gain_g/
gain_b (docs/sane-hook3-gain.md section 6, part A/2) address the op
program's own `ops` array directly -- op_index is the index into the
ORIGINAL captured op list, which is exactly the emitted op program's
index (one-to-one, asserted in op_injections_for()) -- unlike the pair-
table RegInjection above, which needs the op-index-to-pair-index
remapping decode_phase() computes.

A phase's `("bo", (op_indices...))` specs (the shading-table uploads)
instead feed an OpBulkInjection table: `{name, first_op, last_op}`, the
INCLUSIVE range of consecutive `BulkOut` ops the named payload is split
across (docs/sane-hook4-shading.md section 6) -- see
`op_bulk_injections_for()`. For a split program the range is re-based
the same way the ops themselves are.

Usage:  python tools/gen_sane_tables.py [--check]
        --check regenerates into memory and fails if the checked-in
        output differs (for the offline suite).
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, replace as dc_replace
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

from of135i import (  # noqa: E402
    tables, tables_base, tables_ir, tables_load,
    tables_dpi600, tables_dpi1200, tables_dpi2400, tables_dpi7200,
    holder, image as _image,
)

OUT_DIR = REPO / "sane"
STEM = "gl126_tables"

# The scan-table modules, in the order they are emitted. `tables` is the
# 3600 dpi visible-only profile (the plain scan); `tables_ir` is 3600 dpi
# dual-light. The rest are the dual-light profiles for the other four
# resolutions. `tables_load` holds the magazine phases (no dpi).
PROFILES = [
    ("plain3600", tables, 3600, "3600 dpi, visible only (plain scan)"),
    ("ir3600", tables_ir, 3600, "3600 dpi, dual-light (IR + visible)"),
    ("dpi600", tables_dpi600, 600, "600 dpi, dual-light"),
    ("dpi1200", tables_dpi1200, 1200, "1200 dpi, dual-light"),
    ("dpi2400", tables_dpi2400, 2400, "2400 dpi, dual-light"),
    ("dpi7200", tables_dpi7200, 7200, "7200 dpi, dual-light"),
]

# Wire constants (of135i/usbio.py).
REQ_WRITE = 0x04
REQ_END_ACCESS = 0x0C
WV_REGS = 0x0083
WV_BUF_DESC = 0x0082

# Op-program wire constants (docs/sane-hook2-offset.md section 2).
WV_STATUS = 0x008E          # register read / ack read / bulk-done read
WI_ACK = 0x0020             # ack read after a write -> must be 0x55
WI_BULK_DONE = 0x0018       # read after a bulk transfer -> logged only
WV_EXT_STATUS = 0x018E      # extended register read (0x100-0x105)
WI_DATAENB = 0x0122         # reg 0x101: bit 0x01 = data ready
WI_REG100 = 0x0022          # reg 0x100: W2, docs/sane-hook4-shading.md section 3

# Phases that get an op program: hook 2's whole scope (docs/sane-hook2-
# offset.md section 6), hook 3's (docs/sane-hook3-gain.md section 6) and
# hook 4's (docs/sane-hook4-shading.md section 6), in the order they run.
# `cal_shading_verify` is special: it is decoded once and split into two
# programs (see the module docstring's "Split programs" section and the
# main emit loop below), so it is NOT looked up in `phase.name` against
# this tuple the way the others are.
OP_PROGRAM_PHASES = ("prep", "afe_base", "cal_dark_a", "cal_dark_b",
                     "cal_white", "cal_gain_check_a", "cal_gain_check_b",
                     "cal_shading_measure", "cal_shading_upload")
# The name of the phase that gets split, and the two program names it
# produces (docs/sane-hook4-shading.md section 6).
_SPLIT_PHASE = "cal_shading_verify"
_SPLIT_PROGRAM_NAMES = ("cal_shading_verify", "cal_shading_verify_upload")

# The two phases that must yield exactly one PollDataReady/BulkIn/BulkDone.
_DARK_PHASES = ("cal_dark_a", "cal_dark_b")
# Hook 3's three phases: at least one PollDataReady/BulkIn, exactly one
# BulkDone (cal_white has three BulkIn ops; docs/sane-hook3-gain.md
# section 6, part A/1).
_GAIN_PHASES = ("cal_white", "cal_gain_check_a", "cal_gain_check_b")
# Hook 4's four programs (docs/sane-hook4-shading.md section 6): the two
# 128-line measurements (measure, and the first half of verify) each
# carry exactly one PollDataReady and at least one BulkIn and no BulkOut;
# cal_shading_measure alone also carries the W2 PollClass. The two upload
# programs (upload, and the second half of verify) are pure bulk OUT: at
# least one BulkOut, no BulkIn/PollDataReady/PollClass. BulkDone is
# deliberately left unconstrained here (it is 0 on the upload programs, 2
# on verify's measurement half, 1 on measure -- see docs/sane-hook4-
# shading.md section 6, "the validator no longer insists on one BulkDone
# per program"); the wire-equality test (tests/test_sane_ops.py) is what
# pins the exact per-profile transfer counts.
_SHADING_MEASURE_PHASES = ("cal_shading_measure", "cal_shading_verify")
_SHADING_UPLOAD_PHASES = ("cal_shading_upload", "cal_shading_verify_upload")


@dataclass
class BufWrite:
    """One buffer transfer: descriptor plus the payload's total length."""
    addr: int
    length: int
    payload: bytes


@dataclass
class PhaseTables:
    """A phase reduced to what the backend has to reproduce."""
    name: str
    pairs: list[tuple[int, int]]            # (reg, val), in write order
    injections: dict[str, int]              # name -> index into `pairs`
    bo_injections: dict[str, tuple[int, int]]   # name -> (buf index, length)
    buffers: list[BufWrite]
    end_access: list[tuple[int, int]]       # (wValue, wIndex)
    op_count: int
    read_count: int
    split_at: int | None


def decode_phase(phase) -> PhaseTables:
    """Reduce one `Phase` op stream to register pairs, buffers and the
    indices its injection points land on.

    The injection specs address `(op_index, byte_offset)` in the captured
    op data. A register batch is `[reg][val]` pairs, so an even offset is a
    register number and an odd one is its value; every injection in the
    tables targets a value byte. The mapping from op/offset to pair index
    is therefore `pairs_before_this_op + byte_offset // 2`, and it is
    computed here rather than assumed, so a table change that moves a byte
    is caught by the assertion below instead of silently mis-indexing.
    """
    pairs: list[tuple[int, int]] = []
    buffers: list[BufWrite] = []
    end_access: list[tuple[int, int]] = []
    reads = 0
    # op index -> index in `pairs` where that op's pairs start
    pair_base: dict[int, int] = {}
    # op index -> index in `buffers` for that op's descriptor
    buf_of_op: dict[int, int] = {}
    pending_buf: int | None = None

    for i, op in enumerate(phase.ops):
        if op.kind == "cw" and op.br == REQ_WRITE and op.wv == WV_REGS:
            pair_base[i] = len(pairs)
            data = op.data
            if len(data) % 2:
                raise ValueError(
                    f"{phase.name}: register write op {i} has an odd length "
                    f"({len(data)} B); it is not whole [reg][val] pairs")
            pairs.extend((data[k], data[k + 1]) for k in range(0, len(data), 2))
        elif op.kind == "cw" and op.br == REQ_WRITE and op.wv == WV_BUF_DESC:
            addr = int.from_bytes(op.data[0:4], "little")
            length = int.from_bytes(op.data[4:8], "little")
            buf_of_op[i] = len(buffers)
            buffers.append(BufWrite(addr=addr, length=length, payload=b""))
            pending_buf = len(buffers) - 1
        elif op.kind == "bo":
            if pending_buf is None:
                raise ValueError(f"{phase.name}: bulk OUT at op {i} with no "
                                 f"preceding buffer descriptor")
            buffers[pending_buf].payload += op.data
            buf_of_op[i] = pending_buf
        elif op.kind == "cw" and op.br == REQ_END_ACCESS:
            end_access.append((op.wv, op.wi))
        elif op.kind in ("cr", "poll", "bi"):
            reads += 1

    injections: dict[str, int] = {}
    bo_injections: dict[str, tuple[int, int]] = {}
    for name, spec in phase.injections.items():
        if spec[0] == "byte":
            _, idx, off = spec
            if idx not in pair_base:
                raise ValueError(f"{phase.name}: injection {name!r} targets op "
                                 f"{idx}, which is not a register write")
            if off % 2 == 0:
                raise ValueError(f"{phase.name}: injection {name!r} targets byte "
                                 f"{off}, a register number rather than a value")
            injections[name] = pair_base[idx] + off // 2
        elif spec[0] == "bo":
            _, idxs = spec
            bufs = {buf_of_op[i] for i in idxs if i in buf_of_op}
            if len(bufs) != 1:
                raise ValueError(f"{phase.name}: injection {name!r} spans "
                                 f"{len(bufs)} buffers, expected exactly one")
            b = bufs.pop()
            bo_injections[name] = (b, sum(len(phase.ops[i].data) for i in idxs))

    return PhaseTables(
        name=phase.name, pairs=pairs, injections=injections,
        bo_injections=bo_injections, buffers=buffers, end_access=end_access,
        op_count=len(phase.ops), read_count=reads, split_at=phase.split_at,
    )


@dataclass
class OpEntry:
    """One op-program transfer, already classified into the C++ OpKind
    the runner (gl126_ops.cpp) understands."""
    kind: str            # "Write" | "AckRead" | "Read" | "PollDataReady"
                          # | "PollClass" | "BulkIn" | "BulkOut" | "BulkDone"
                          # | "PollMasked" | "ReadModifyWrite" (docs/sane-
                          # hook5-frame.md section 4/6, hooks 5-7: POSITION's
                          # completion poll, PARK's two waits and its three
                          # read-modify-write sites) | "Sleep" |
                          # "PollBestEffort" (docs/sane-wp4-magazine.md
                          # section 3: the magazine flow's replayed pacing
                          # and its non-raising polls)
    request: int          # bRequest; 0 for BulkIn/BulkOut
    value: int             # wValue
    index: int              # wIndex
    data: bytes            # Write/BulkOut: payload; else: captured reply (b"" for BulkIn)
    length: int             # Write/reads: byte length; BulkIn/BulkOut: bulk length
    dur_ms: int             # captured poll duration in ms (0 otherwise)
    mask: int = 0           # PollMasked/PollBestEffort: poll mask; ReadModifyWrite: and_mask
    want: int = 0           # PollMasked/PollBestEffort: target value; ReadModifyWrite: or_mask
    timeout_ms: int = 0     # PollMasked/PollBestEffort: this site's own budget
                             # (0 = use the RunPolicy value)


#: of135i/device.py LOAD_STATUS_MASK -- the magazine flow's completion
#: rule: state class AND loader-sensor bit 0x08, busy bit clear, the
#: never-observed 0x02 clear; only 0x04 masked out (session-variable).
MAGAZINE_STATUS_MASK = 0xFB
#: of135i/device.py _poll_one's lenient status-word rule (upper nibble =
#: state class) and its reg-0x32 rule (bits 3-4 are sensor state).
_LENIENT_STATUS_MASK = 0xF0
_LENIENT_REG32_MASK = 0xFF & ~0x18
#: of135i/device.py _PACE_THRESHOLD / _PACE_CAP: the replayer sleeps the
#: captured gap before an op when it exceeds the threshold, capped.
_PACE_THRESHOLD = 0.05
_PACE_CAP = 2.0
#: The magazine phases whose motor completions the driver runs STRICTLY
#: (device.py: jog_magazine()/load_magazine() pass strict_polls; the
#: device-open phase does not).
_MAGAZINE_STRICT_PHASES = ("jog", "load")
#: The five programs of the magazine flow, in the order they run
#: (docs/sane-wp4-magazine.md section 3). "open"/"jog"/"load" are decoded
#: from tables_load's captured phases; "cold_init"/"eject" are built from
#: of135i/device.py, which builds them itself.
_MAGAZINE_PROGRAM_NAMES = ("cold_init", "open", "jog", "load", "eject")


def _poll_timeout_ms(dur: float) -> int:
    """device.py _poll_one's budget for one captured poll: three times
    the captured duration, never below a second."""
    return round(max(3.0 * dur, 1.0) * 1000)


def _magazine_poll(phase, op, dur_ms: int) -> OpEntry:
    """One magazine-phase `poll`, classified as docs/sane-wp4-magazine.md
    section 3.2 describes (see decode_ops)."""
    strict = (phase.name in _MAGAZINE_STRICT_PHASES and op.wv == WV_EXT_STATUS)
    settled = op.resp[0] if op.resp else 0
    timeout = _poll_timeout_ms(op.dur)
    if strict:
        return OpEntry("PollMasked", op.br, op.wv, op.wi, op.resp, op.length,
                       dur_ms, mask=MAGAZINE_STATUS_MASK,
                       want=settled & MAGAZINE_STATUS_MASK, timeout_ms=timeout)
    if op.wv == WV_EXT_STATUS:
        mask = _LENIENT_STATUS_MASK
    elif op.wv == WV_STATUS and op.wi == 0x3222:
        mask = _LENIENT_REG32_MASK
    else:
        mask = 0xFF
    return OpEntry("PollBestEffort", op.br, op.wv, op.wi, op.resp, op.length,
                   dur_ms, mask=mask, want=settled & mask, timeout_ms=timeout)


def decode_ops(phase, magazine: bool = False) -> list[OpEntry]:
    """Reduce one `Phase` op stream to an ordered op-program, one `OpEntry`
    per captured transfer -- see the module docstring's "Op programs"
    section for the mapping rules. Raises ValueError on an op kind the
    mapping does not cover.

    ``magazine=True`` (docs/sane-wp4-magazine.md section 3.2) decodes the
    OPEN/JOG/LOAD phases, which the Python driver runs with semantics the
    calibration and scan phases never needed, and which were
    hardware-verified in exactly that form (Tests 17-23, 7/7):

      * the replayer's PACING is kept -- a `Sleep` op carrying
        min(dt, 2 s) is emitted before every op whose captured gap
        exceeds 50 ms (device.py _exec_ops). Hook 5 dropped the
        pre-sleep for POSITION deliberately; that was a choice for a
        rewritten PARK, not a rule for a flow verified with it.
      * a status-word `poll` in JOG/LOAD is a MOTOR COMPLETION the
        driver runs strictly -> `PollMasked` under LOAD_STATUS_MASK
        (state class AND loader-sensor bit), fail-closed.
      * every other `poll` -> `PollBestEffort` with the driver's own
        leniency at that site (status word: state class; reg 0x32: bits
        3-4 masked out, they are sensor state) -- logged and continued
        on timeout, exactly as _poll_one does for a non-strict poll.
      * each of those polls carries its OWN budget (three times the
        captured duration, never below a second), because the captured
        durations here span 4 ms to 1.6 s.
    """
    entries: list[OpEntry] = []
    for i, op in enumerate(phase.ops):
        if magazine and op.dt > _PACE_THRESHOLD:
            entries.append(OpEntry("Sleep", 0, 0, 0, b"", 0,
                                   round(min(op.dt, _PACE_CAP) * 1000)))
        if op.kind == "cw":
            entries.append(OpEntry("Write", op.br, op.wv, op.wi, op.data,
                                   len(op.data), 0))
        elif op.kind == "cr":
            if (op.br == REQ_END_ACCESS and op.wv == WV_STATUS
                    and op.wi == WI_ACK and op.length == 1):
                entries.append(OpEntry("AckRead", op.br, op.wv, op.wi,
                                       op.resp, op.length, 0))
            elif (op.br == REQ_END_ACCESS and op.wv == WV_STATUS
                    and op.wi == WI_BULK_DONE and op.length == 1):
                entries.append(OpEntry("BulkDone", op.br, op.wv, op.wi,
                                       op.resp, op.length, 0))
            else:
                entries.append(OpEntry("Read", op.br, op.wv, op.wi,
                                       op.resp, op.length, 0))
        elif op.kind == "poll":
            dur_ms = round(op.dur * 1000)
            if magazine:
                entries.append(_magazine_poll(phase, op, dur_ms))
            elif (op.wv == WV_EXT_STATUS and op.wi == WI_DATAENB
                    and len(op.resp) >= 1 and (op.resp[0] & 0x01)):
                entries.append(OpEntry("PollDataReady", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms))
            elif op.wv == WV_EXT_STATUS and op.wi == WI_REG100:
                entries.append(OpEntry("PollClass", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms))
            elif phase.name == "position" and op.wv == WV_EXT_STATUS and op.wi == WI_DATAENB:
                # POSITION's own completion poll (docs/sane-hook5-frame.md
                # section 3, W3 / decision 2): class F only, on reg 0x101 --
                # Test 31 rules out the bit-0x01 (DATAENB) variant, so this
                # is deliberately NOT PollDataReady even though it shares
                # that op's wValue/wIndex. mask/want are a FIXED 0xf0/0xf0,
                # not derived from this capture's own settled reply (unlike
                # PollClass/hook4's W2, which accepts whatever the capture
                # settled on) -- every POSITION move waits for class F.
                entries.append(OpEntry("PollMasked", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms,
                                       mask=0xF0, want=0xF0))
            else:
                entries.append(OpEntry("Read", op.br, op.wv, op.wi,
                                       op.resp, op.length, dur_ms))
        elif op.kind == "bi":
            entries.append(OpEntry("BulkIn", 0, 0, 0, b"", op.length, 0))
        elif op.kind == "bo":
            entries.append(OpEntry("BulkOut", 0, 0, 0, op.data, len(op.data), 0))
        else:
            raise ValueError(f"{phase.name}: op {i} has unknown kind {op.kind!r}")
    return entries


_KNOWN_OP_KINDS = frozenset((
    "Write", "AckRead", "Read", "PollDataReady", "PollClass",
    "BulkIn", "BulkOut", "BulkDone", "PollMasked", "ReadModifyWrite",
    "Sleep", "PollBestEffort",
))


def validate_op_program(phase_name: str, entries: list[OpEntry]) -> None:
    """cal_dark_a/cal_dark_b must each yield exactly one PollDataReady
    (the W1 wait), one BulkIn (the 3072 B dark buffer) and one BulkDone
    (docs/sane-hook2-offset.md section 1, S4/S5).

    cal_white/cal_gain_check_a/cal_gain_check_b (hook 3) are looser: at
    least one PollDataReady and one BulkIn (cal_white has three -- the
    31104 B white line comes back as 16384+14336+384), exactly one
    BulkDone (docs/sane-hook3-gain.md section 6, part A/1).

    cal_shading_measure/cal_shading_verify (hook 4, the two 128-line
    measurements): exactly one PollDataReady, at least one BulkIn, no
    BulkOut; cal_shading_measure alone also carries the W2 PollClass
    (docs/sane-hook4-shading.md section 6). cal_shading_upload/
    cal_shading_verify_upload (the two pure-bulk-OUT uploads): at least
    one BulkOut, no BulkIn/PollDataReady/PollClass. Every program, of
    every kind: no op kind outside `_KNOWN_OP_KINDS` -- decode_ops only
    ever produces one of those, so this is a defensive check against a
    future OpKind this function was not updated for."""
    unknown = {e.kind for e in entries} - _KNOWN_OP_KINDS
    if unknown:
        raise ValueError(f"{phase_name}: op program has unknown op kind(s) {sorted(unknown)}")

    def count(kind: str) -> int:
        return sum(1 for e in entries if e.kind == kind)

    if phase_name in _DARK_PHASES:
        for kind in ("PollDataReady", "BulkIn", "BulkDone"):
            n = count(kind)
            if n != 1:
                raise ValueError(
                    f"{phase_name}: expected exactly one {kind} op, got {n}")
    elif phase_name in _GAIN_PHASES:
        for kind in ("PollDataReady", "BulkIn"):
            n = count(kind)
            if n < 1:
                raise ValueError(
                    f"{phase_name}: expected at least one {kind} op, got {n}")
        n_done = count("BulkDone")
        if n_done != 1:
            raise ValueError(
                f"{phase_name}: expected exactly one BulkDone op, got {n_done}")
    elif phase_name in _SHADING_MEASURE_PHASES:
        n_poll = count("PollDataReady")
        if n_poll != 1:
            raise ValueError(
                f"{phase_name}: expected exactly one PollDataReady op, got {n_poll}")
        n_bulk_in = count("BulkIn")
        if n_bulk_in < 1:
            raise ValueError(
                f"{phase_name}: expected at least one BulkIn op, got {n_bulk_in}")
        n_bulk_out = count("BulkOut")
        if n_bulk_out != 0:
            raise ValueError(
                f"{phase_name}: expected no BulkOut op, got {n_bulk_out}")
        if phase_name == "cal_shading_measure":
            # W2 (reg 0x100 polled, not merely read) is captured on the
            # plain3600 profile only -- every dual-light profile's own
            # capture reads that register once as a plain `cr` (already
            # "Read"), never a coalesced `poll` (docs/sane-hook4-
            # shading.md section 3: "the only place the vendor polls
            # that register").  So the invariant that holds across every
            # profile is "at most one", not "exactly one".
            n_class = count("PollClass")
            if n_class > 1:
                raise ValueError(
                    f"{phase_name}: expected at most one PollClass op, got {n_class}")
    elif phase_name in _SHADING_UPLOAD_PHASES:
        n_bulk_out = count("BulkOut")
        if n_bulk_out < 1:
            raise ValueError(
                f"{phase_name}: expected at least one BulkOut op, got {n_bulk_out}")
        for kind in ("BulkIn", "PollDataReady", "PollClass"):
            n = count(kind)
            if n != 0:
                raise ValueError(
                    f"{phase_name}: expected no {kind} op, got {n}")
    elif phase_name == "position":
        # docs/sane-hook5-frame.md section 2/4: exactly 1 PollMasked (W3,
        # the completion poll) and 2 BulkOut (the slope-table upload,
        # written to two addresses).
        n_poll = count("PollMasked")
        if n_poll != 1:
            raise ValueError(
                f"{phase_name}: expected exactly one PollMasked op, got {n_poll}")
        n_bo = count("BulkOut")
        if n_bo != 2:
            raise ValueError(
                f"{phase_name}: expected exactly two BulkOut ops, got {n_bo}")
    elif phase_name == "scan_setup":
        # docs/sane-hook5-frame.md section 2/4: no polls at all (S1 lets
        # the first bulk IN block instead), 3 BulkOut (the scan-table
        # upload, written to three addresses).
        for kind in ("PollDataReady", "PollClass", "PollMasked"):
            n = count(kind)
            if n != 0:
                raise ValueError(
                    f"{phase_name}: expected no {kind} op, got {n}")
        n_bo = count("BulkOut")
        if n_bo != 3:
            raise ValueError(
                f"{phase_name}: expected exactly three BulkOut ops, got {n_bo}")
    elif phase_name in _MAGAZINE_PROGRAM_NAMES:
        # docs/sane-wp4-magazine.md section 3. Invariants that would be a
        # real regression if they moved, not a recount of every op:
        #   * no BulkIn anywhere -- the magazine flow reads no image data;
        #   * every BulkOut carries its payload (the slope table is not
        #     unit-specific calibration data, so nothing is injected) and
        #     they come in pairs, because every motor move uploads the
        #     slope table to BOTH scanner-RAM addresses (device.py:
        #     without that a move runs against whatever curve is in RAM,
        #     which stalled the mechanism once);
        #   * the driver's fail-closed completions are exactly where it
        #     puts them: four in the jog (feed, feed, eject, plus the
        #     interstitial), two in the load (the engaging feed and the
        #     traverse), none anywhere else -- the cold start and the
        #     eject poll best-effort, as the driver does.
        n_bulk_in = count("BulkIn")
        if n_bulk_in != 0:
            raise ValueError(
                f"{phase_name}: expected no BulkIn op, got {n_bulk_in}")
        n_bo = count("BulkOut")
        if n_bo % 2 != 0:
            raise ValueError(
                f"{phase_name}: slope-table uploads come in pairs (both RAM "
                f"addresses), got {n_bo} BulkOut ops")
        missing = [i for i, e in enumerate(entries)
                   if e.kind == "BulkOut" and not e.data]
        if missing:
            raise ValueError(
                f"{phase_name}: BulkOut op(s) {missing} carry no payload; the "
                f"magazine flow injects nothing")
        want_masked = {"jog": 4, "load": 2}.get(phase_name, 0)
        n_masked = count("PollMasked")
        if n_masked != want_masked:
            raise ValueError(
                f"{phase_name}: expected exactly {want_masked} PollMasked "
                f"op(s), got {n_masked}")
        for e in entries:
            if e.kind in ("PollMasked", "PollBestEffort") and e.timeout_ms <= 0:
                raise ValueError(
                    f"{phase_name}: a {e.kind} op carries no timeout budget")
    elif phase_name == "park":
        # docs/sane-hook5-frame.md section 2/4: 2 PollMasked (Wait A on
        # reg 0x35 bit 0x40, Wait B on the PARK_COMPLETE status word).
        # DEVIATION from the plan's own prose ("3 ReadModifyWrite"): the
        # actual of135i/device.py::_park_semantic_steps() performs FOUR
        # real read-then-write-back actions, not three -- reg 0x15 once,
        # reg 0x32 TWICE (once before Wait A, once again in the closing
        # idle round after Wait B) and reg 0x35 once (after Wait A). See
        # build_park_program()'s own docstring for the evidence; this
        # validator follows the source, not the plan's recap.
        n_poll = count("PollMasked")
        if n_poll != 2:
            raise ValueError(
                f"{phase_name}: expected exactly two PollMasked ops, got {n_poll}")
        n_rmw = count("ReadModifyWrite")
        if n_rmw != 4:
            raise ValueError(
                f"{phase_name}: expected exactly four ReadModifyWrite ops, got {n_rmw}")


def op_injections_for(phase, entries: list[OpEntry],
                      base_op_index: int = 0) -> list[tuple[str, int, int]]:
    """Derive an op program's OpInjection entries -- (name, op_index,
    byte_offset), LOCAL to this program -- from `phase.injections`'s
    "byte" specs, checked against the op program itself rather than
    assumed (docs/sane-hook3-gain.md section 6, part A/2). `entries` is
    one-to-one with `phase.ops[base_op_index:base_op_index+len(entries)]`
    by construction (decode_ops emits exactly one OpEntry per captured
    op, in order; `base_op_index` is nonzero only for the second half of
    a split program -- docs/sane-hook4-shading.md section 6). A spec
    whose op_index falls outside that range belongs to the OTHER half of
    a split phase and is silently skipped here (present in the other
    call for that half instead).

    Only cal_gain_check_a carries any among the phases in scope here
    (gain_r/gain_g/gain_b -> ops 0/2/4, byte 5); every other program's
    list is empty."""
    out: list[tuple[str, int, int]] = []
    for name, spec in phase.injections.items():
        if spec[0] != "byte":
            continue
        _, idx, off = spec
        if not (base_op_index <= idx < base_op_index + len(entries)):
            continue
        local_idx = idx - base_op_index
        if entries[local_idx].kind != "Write":
            raise ValueError(
                f"{phase.name}: op injection {name!r} targets op {idx}, "
                f"which is not a Write in the op program")
        if not (0 <= off < entries[local_idx].length):
            raise ValueError(
                f"{phase.name}: op injection {name!r} targets byte {off}, "
                f"outside op {idx}'s {entries[local_idx].length} B payload")
        if off % 2 == 0:
            raise ValueError(
                f"{phase.name}: op injection {name!r} targets byte {off}, "
                f"a register number rather than a value")
        out.append((name, local_idx, off))
    out.sort(key=lambda t: (t[1], t[0]))
    return out


def op_bulk_injections_for(phase, entries: list[OpEntry],
                           base_op_index: int = 0) -> list[tuple[str, int, int]]:
    """Derive an op program's OpBulkInjection entries -- (name,
    first_op, last_op), LOCAL to this program (inclusive, re-based by
    `base_op_index` the same way op_injections_for's are) -- from
    `phase.injections`'s "bo" specs: the shading-table uploads (docs/
    sane-hook4-shading.md section 6). A spec whose indices fall outside
    `[base_op_index, base_op_index+len(entries))` belongs to the OTHER
    half of a split phase and is silently skipped (cal_shading_upload
    has one such spec; cal_shading_verify's belongs entirely to the
    upload half). Asserts the named indices are a contiguous run of
    BulkOut ops in the op program -- the runner slices the injected
    payload across them in order, so a gap or a non-BulkOut op in the
    middle would silently misroute bytes."""
    out: list[tuple[str, int, int]] = []
    for name, spec in phase.injections.items():
        if spec[0] != "bo":
            continue
        _, idxs = spec
        if not all(base_op_index <= i < base_op_index + len(entries) for i in idxs):
            continue
        local = sorted(i - base_op_index for i in idxs)
        if local != list(range(local[0], local[0] + len(local))):
            raise ValueError(
                f"{phase.name}: bulk injection {name!r} op indices {idxs} "
                f"are not consecutive")
        first, last = local[0], local[-1]
        for i in range(first, last + 1):
            if entries[i].kind != "BulkOut":
                raise ValueError(
                    f"{phase.name}: bulk injection {name!r} targets op "
                    f"{i + base_op_index}, which is not a BulkOut in the "
                    f"op program")
        out.append((name, first, last))
    out.sort(key=lambda t: t[1])
    return out


def strip_bulk_injected_data(entries: list[OpEntry],
                             bulk_injections: list[tuple[str, int, int]]) -> None:
    """Clear the captured payload of every BulkOut op a bulk injection
    covers, in place -- `entries` is LOCAL and `bulk_injections`' indices
    already are too, so no re-basing is needed here. The captured chunk
    is the reference unit's own shading table and must never be written
    to another unit (the same principle as a register injection); `len`
    is untouched (it still comes from the captured op, `emit_op_program`
    just has nothing to put in the byte blob for it -- see
    `emit_op_program`'s `nullptr` rule below). A BulkOut NOT named by any
    bulk injection is left alone and keeps its captured payload."""
    for _, first, last in bulk_injections:
        for i in range(first, last + 1):
            entries[i].data = b""


def build_park_program(phase) -> list[OpEntry]:
    """Build the semantic PARK op program (docs/sane-hook5-frame.md
    section 2/4, hook 7) directly from `phase`'s (t.PARK's) own captured
    constants -- NOT `phase.ops` replayed verbatim -- mirroring of135i/
    device.py's Scanner._park_semantic_steps() step for step. The
    captured phase supplies only the two 0x8b control-write payloads
    (wIndex 0x0b/0x0f) and whether a 0x19=0x00 write follows the
    pre-Wait-A 0x32 read-modify-write; everything else (the teardown
    writes, the RMW sites, the two waits, the closing idle round) is
    identical across every profile, matching park_semantic()'s own
    table-independence claim ("everything else in PARK is identical
    across all six tables").

    Deviations from the plan's own prose, resolved by reading
    of135i/device.py::_park_semantic_steps() directly (its docstring
    calls the offline test "the arbiter" for exactly this reason):

      * NO AckRead ops anywhere. park_semantic() writes registers via
        Scanner.io.write_regs() or a raw dev.ctrl_transfer() call,
        neither of which performs a follow-up ack read (of135i/usbio.py's
        write_regs(): one control transfer per batch, checks the byte
        count the OS call itself returned, nothing more). This is
        confirmed against tests/test_park.py's _FakeDev, whose `events`
        list never grows beyond the 3 raw control writes (0x8d, 0x8b x2)
        plus the RMW/status reads it separately tracks -- there is no
        ack-read event anywhere in that fake's model of park_semantic().
        This differs from "position"/"scan_setup", which DO carry
        AckRead ops, because those two replay the literal captured wire
        trace op for op.
      * FOUR ReadModifyWrite ops, not the three the plan's prose lists:
        reg 0x15 once, reg 0x32 TWICE (once before Wait A, once again in
        the closing idle round after Wait B) and reg 0x35 once (after
        Wait A). The closing idle round's 0x32 write-back is a genuine
        read-modify-write in the source (`v32b = self.io.read_reg(0x32);
        self.io.write_regs([(0x32, v32b)])`), so it is emitted as one
        too; validate_op_program() checks for 4, not 3, with the same
        reasoning inline.
      * The closing idle round performs NO reg-0x35 read. The plan's
        prose describes it as "the batch 36/3a/36/33, RMW 0x32
        write-back, read 0x35 as Read"; the actual source is exactly
        `write_regs(idle batch); read_reg(0x32); write_regs([(0x32,
        v32b)])` -- no third transfer, no reg-0x35 read at all.
    """
    ctrl_8b = [(op.wi, op.data) for op in phase.ops
              if op.kind == "cw" and op.wv == 0x008B]
    if len(ctrl_8b) != 2:
        raise ValueError(
            f"{phase.name}: expected 2 control writes with wValue 0x8b, "
            f"found {len(ctrl_8b)}")
    has_0x19 = any(
        op.kind == "cw" and op.wv == 0x0083
        and any(op.data[i] == 0x19 for i in range(0, len(op.data), 2))
        for op in phase.ops
    )

    entries: list[OpEntry] = []

    def W(value: int, index: int, data: bytes, request: int = 0x04) -> None:
        entries.append(OpEntry(kind="Write", request=request, value=value,
                               index=index, data=bytes(data), length=len(data),
                               dur_ms=0))

    def RMW(reg: int, and_mask: int, or_mask: int) -> None:
        entries.append(OpEntry(kind="ReadModifyWrite", request=0x04, value=0x008E,
                               index=(reg << 8) | 0x22, data=b"", length=2,
                               dur_ms=0, mask=and_mask, want=or_mask))

    def POLL(value: int, index: int, mask: int, want: int, request: int = 0x04) -> None:
        entries.append(OpEntry(kind="PollMasked", request=request, value=value,
                               index=index, data=b"", length=2, dur_ms=0,
                               mask=mask, want=want))

    idle = bytes([0x36, 0xFC, 0x3A, 0x00, 0x36, 0xFC, 0x33, 0x0E])

    # ---- real park/teardown sequence (captured ops 0-55, replayed as
    # the driver's own write_regs()/ctrl_transfer() calls) -------------
    W(0x008D, 0x0000, b"\x00", request=0x0C)
    W(0x0083, 0x0000, bytes([0x03, 0x30]))
    W(0x0083, 0x0000, bytes([0x03, 0x20]))
    W(0x0083, 0x0000, bytes([0x01, 0x22]))
    W(0x0083, 0x0000, bytes([0x3A, 0x00]))
    RMW(0x15, 0xEF, 0x00)                      # v15 & ~0x10
    W(0x0083, 0x0000, bytes([0x02, 0x30]))
    W(0x0083, 0x0000, idle)
    W(0x0083, 0x0000, bytes([0x03, 0x10]))
    W(0x0083, 0x0000, bytes([0x03, 0x00]))
    for wi, payload in ctrl_8b:
        W(0x008B, wi, payload)
    RMW(0x32, 0xFF, 0x00)                      # write back unchanged
    if has_0x19:
        W(0x0083, 0x0000, bytes([0x19, 0x00]))

    # ---- Wait A: reg 0x35 bit 0x40 set, then RMW-clear it -------------
    POLL(0x008E, 0x3522, 0x40, 0x40)
    RMW(0x35, 0xBF, 0x00)                      # v35 & ~0x40

    # ---- Wait B: PARK_COMPLETE status word after the carriage return -
    POLL(0x018E, 0x0122, 0xE3, 0xE0)

    # ---- one idle-loop round (heartbeat only, no captured 2 s pause,
    # no reg-0x35 read -- see the deviations above) ---------------------
    W(0x0083, 0x0000, idle)
    RMW(0x32, 0xFF, 0x00)

    return entries


# --------------------------------------------------------- magazine (WP-4)

# device.py/usbio.py wire constants the two hand-built magazine programs
# need. Kept here, next to the code that emits them, rather than in the
# C++: Python is the authority for every magazine transfer.
_WV_AFE = 0x008B          # AFE/EEPROM control writes (usbio.end_access 0x8b)
_WV_CHIP = 0x008A         # chip id / EEPROM reads
_WV_END_ACCESS = 0x008C   # usbio.end_access default
_WI_CHIP = 0x26FE
_REG_WRITE_CHUNK = 64     # usbio._WRITE_CHUNK: 64 B = 32 (reg, val) pairs

#: usbio.poll_status_word's budgets in cold_init (device.py): the ready
#: wait and each homing move's completion.
_COLD_READY_TIMEOUT_MS = 15000
_COLD_MOVE_TIMEOUT_MS = 30000
#: _cold_homing_round's settle loop: 30 rounds, 50 ms apart.
_COLD_SETTLE_TIMEOUT_MS = 1500
#: _eject_body's completion loop.
_EJECT_TIMEOUT_MS = 10000


def _w(entries: list[OpEntry], value: int, index: int, data: bytes,
       request: int = REQ_WRITE) -> None:
    entries.append(OpEntry("Write", request, value, index, bytes(data),
                           len(data), 0))


def _write_regs(entries: list[OpEntry], pairs) -> None:
    """usbio.write_regs(): the flattened pairs in 64 B control writes."""
    data = bytes(b for pair in pairs for b in pair)
    for i in range(0, len(data), _REG_WRITE_CHUNK):
        _w(entries, WV_REGS, 0, data[i:i + _REG_WRITE_CHUNK])


def _read(entries: list[OpEntry], value: int, index: int, length: int,
          request: int = REQ_WRITE) -> None:
    entries.append(OpEntry("Read", request, value, index, b"", length, 0))


def _read_reg(entries: list[OpEntry], reg: int) -> None:
    """usbio.read_reg(): 0xc0/0x04/0x008e, wIndex (reg << 8) | 0x22."""
    _read(entries, WV_STATUS, (reg << 8) | 0x22, 2)


def _read_status_word(entries: list[OpEntry]) -> None:
    """usbio.read_status_word(): reg 0x101 through the extended path."""
    _read(entries, WV_EXT_STATUS, WI_DATAENB, 2)


def _rmw(entries: list[OpEntry], reg: int, and_mask: int, or_mask: int) -> None:
    entries.append(OpEntry("ReadModifyWrite", REQ_WRITE, WV_STATUS,
                           (reg << 8) | 0x22, b"", 2, 0,
                           mask=and_mask, want=or_mask))


def _poll_best_effort(entries: list[OpEntry], value: int, index: int,
                      mask: int, want: int, timeout_ms: int) -> None:
    entries.append(OpEntry("PollBestEffort", REQ_WRITE, value, index, b"", 2, 0,
                           mask=mask, want=want, timeout_ms=timeout_ms))


def _end_access(entries: list[OpEntry], which: int, index: int) -> None:
    """usbio.end_access(): 0x40/0x0c, wValue = which, no payload."""
    _w(entries, which, index, b"", request=REQ_END_ACCESS)


def _buf_write(entries: list[OpEntry], addr: int, payload: bytes) -> None:
    """usbio.buf_write(): descriptor then the payload in 16 KiB bulk
    chunks (every magazine payload is one 512 B slope table)."""
    import struct
    _w(entries, WV_BUF_DESC, 1, struct.pack("<II", addr, len(payload)))
    for i in range(0, len(payload), 16384):
        chunk = payload[i:i + 16384]
        entries.append(OpEntry("BulkOut", 0, 0, 0, chunk, len(chunk), 0))


def _cold_table_and_afe(entries: list[OpEntry]) -> None:
    """device.py Scanner._cold_write_table_and_afe(), transfer for
    transfer: the cold register table, the two end-of-access acks, the
    AFE access enable, the EEPROM read sequence (logged, not consumed),
    the AFE reset and the AFE base values."""
    _write_regs(entries, tables_base.COLD_INIT_PAIRS)
    _end_access(entries, _WV_END_ACCESS, 16)
    _end_access(entries, _WV_END_ACCESS, 19)
    _write_regs(entries, [(0x0B, 0x64)])
    _write_regs(entries, [(0x13, 0x0F)])
    _write_regs(entries, [(0x0B, 0x6C)])
    _end_access(entries, _WV_AFE, 7)
    _w(entries, _WV_AFE, 0x0009, bytes(4))
    _read(entries, _WV_CHIP, 0x0010, 3)
    _w(entries, _WV_AFE, 0x000B, bytes.fromhex("00000100"))
    _read(entries, _WV_CHIP, 0x000F, 19)
    _write_regs(entries, [(0x03, 0x10)])
    _write_regs(entries, [(0x03, 0x00)])
    for adr, val in tables_base.AFE_BASE_PAIRS:
        _write_regs(entries, [(0x51, adr), (0x5D, 0x00), (0x5E, val)])


def _cold_motor_move(entries: list[OpEntry], feedl: int, full_speed_regs: bool) -> None:
    """device.py Scanner._cold_motor_move()."""
    _write_regs(entries, [(0x09, 0x08)])
    move_regs = [
        (0x02, 0x18), (0xAE, 0x00), (0xAF, 0xFF),
        (0x3D, 0x00), (0x3E, (feedl >> 8) & 0xFF), (0x3F, feedl & 0xFF),
    ]
    if full_speed_regs:
        _write_regs(entries, list(tables_base.LOADER_SPEED_PAIRS) + move_regs)
    else:
        _write_regs(entries, move_regs)
    for addr in (0x1000C000, 0x10010000):
        _buf_write(entries, addr, tables_base.SLOPE_TABLE_LOADER)
    _write_regs(entries, [(0x0F, 0x01)])
    # poll_status_word(mask=0xffff, value=0xf855): the driver compares the
    # whole word; PollBestEffort compares the status byte, so the constant
    # 0x55 ack is not re-checked here (a strictly more permissive rule, and
    # the ack byte is checked by read_reg()'s own handling everywhere else).
    _poll_best_effort(entries, WV_EXT_STATUS, WI_DATAENB, 0xFF, 0xF8,
                      _COLD_MOVE_TIMEOUT_MS)


def _cold_homing_round(entries: list[OpEntry]) -> None:
    """device.py Scanner._cold_homing_round()."""
    _rmw(entries, 0x32, 0xFF & ~0x02, 0x00)
    _read_status_word(entries)
    _write_regs(entries, [(0x36, 0xFC)])
    _write_regs(entries, [(0x33, 0x8E)])
    _rmw(entries, 0x32, 0xFF, 0x02)
    _read_status_word(entries)

    _cold_motor_move(entries, 0x1A22, full_speed_regs=False)

    _write_regs(entries, [(0x09, 0x00)])
    _rmw(entries, 0x32, 0xFF, 0x00)
    _rmw(entries, 0x35, 0xFF & ~0x40, 0x00)
    _read_reg(entries, 0x32)
    _poll_best_effort(entries, WV_EXT_STATUS, WI_DATAENB, 0xF0, 0xF0,
                      _COLD_READY_TIMEOUT_MS)
    _rmw(entries, 0x32, 0xFF & ~0x02, 0x00)
    _read_status_word(entries)
    _read_status_word(entries)

    _cold_motor_move(entries, 0x1A22, full_speed_regs=True)
    _cold_motor_move(entries, 0x0C12, full_speed_regs=False)

    _write_regs(entries, [(0x09, 0x00)])
    # The driver's settle loop reads 0x35 and 0x32 together, up to 30
    # times 50 ms apart, and continues either way. Two best-effort polls
    # with the same total budget are the same wire on the settled path
    # (one read each) and the same "log and continue" on the unsettled
    # one -- an op program cannot express "both in the same round".
    _poll_best_effort(entries, WV_STATUS, (0x35 << 8) | 0x22, 0xFF, 0xBB,
                      _COLD_SETTLE_TIMEOUT_MS)
    _poll_best_effort(entries, WV_STATUS, (0x32 << 8) | 0x22, 0xFF, 0x1F,
                      _COLD_SETTLE_TIMEOUT_MS)


def build_cold_init_program() -> list[OpEntry]:
    """The vendor cold-start sequence (docs/sane-wp4-magazine.md section
    3.1), built from of135i/device.py's Scanner._cold_init_body() rather
    than replayed from a captured phase -- the driver builds it the same
    way, from the 01-init capture, and IT is the hardware-verified form
    (the tables carry no `cold_init` phase to replay).

    Deviations from the Python, all of them in the non-gating direction
    and none of them a different transfer:

      * the motor-completion and ready polls compare the STATUS BYTE,
        where poll_status_word() compares the 16-bit word including the
        constant 0x55 ack;
      * the closing settle wait is two best-effort polls (reg 0x35, then
        reg 0x32) instead of one loop reading both;
      * the chip id and the two EEPROM reads are logged reads whose
        replies nothing consumes -- exactly what the driver does with
        them (it logs them and moves on).

    Every poll here is best-effort, as in the driver: a cold start with a
    LATCHED magazine shows a status-word timeout every time (Tests 45,
    51) and still completes, and the standing requirement is precisely
    that this case stay supported. What makes the sequence verified is
    the reg 0x01 = 0x22 read the hook does afterwards, as cold_init()
    does."""
    entries: list[OpEntry] = []

    # 1: GL chip handshake.
    _read(entries, _WV_CHIP, _WI_CHIP, 1, request=REQ_END_ACCESS)
    _w(entries, _WV_AFE, _WI_CHIP, b"", request=REQ_END_ACCESS)

    # 2: status word, then wait for the ready class.
    _read_status_word(entries)
    _poll_best_effort(entries, WV_EXT_STATUS, WI_DATAENB, 0xF0, 0xF0,
                      _COLD_READY_TIMEOUT_MS)

    # 3-7: cold register table + AFE bring-up.
    _cold_table_and_afe(entries)

    # 8: interrupt/sensor setup (two read-modify-writes on reg 0x31).
    _rmw(entries, 0x31, 0x7F, 0x00)
    _rmw(entries, 0x31, 0xFF, 0x80)

    # 9: three homing rounds, the table + AFE rewritten between them.
    for round_n in range(1, 4):
        _cold_homing_round(entries)
        if round_n < 3:
            _cold_table_and_afe(entries)

    return entries


def build_eject_program() -> list[OpEntry]:
    """The eject move (docs/sane-wp4-magazine.md section 3.4), built from
    of135i/device.py's Scanner._eject_body() -- the variant that freed
    the magazine every time through the vendor software (the post-scan
    variant stalled twice, 2026-09-02).

    The program is the BODY only: eject()'s three read-only guards (the
    start state, the loader-sensor bit, the 0x3b/0x3c base-table-state
    refusal) stay in the hook, where a refusal costs no transfer at all.

    Deviation: the completion wait compares the status byte under the
    driver's own (value & 0x21) == 0x20 rule and is best-effort, which is
    what _eject_body() does (it logs "status word stuck" and continues --
    the engine-idle bit stays clear after an eject, observed on a
    SUCCESSFUL eject 2026-09-02)."""
    entries: list[OpEntry] = []
    feedl = 3090

    _write_regs(entries, [(0x33, 0x8E)])
    _rmw(entries, 0x32, 0xFF, 0x02)
    _write_regs(entries, [(0x09, 0x08)])
    _write_regs(entries, (
        [(0x1C, 0x00), (0x02, 0x18),
         (0x3D, (feedl >> 16) & 0xFF), (0x3E, (feedl >> 8) & 0xFF), (0x3F, feedl & 0xFF)]
        + [pair for pair in tables_base.LOADER_SPEED_PAIRS if pair[0] != 0x1C]
        + [(0xAE, 0x00), (0xAF, 0xFF)]
    ))
    for addr in (0x1000C000, 0x10010000):
        _buf_write(entries, addr, tables_base.SLOPE_TABLE_LOADER)
    _write_regs(entries, [(0x0F, 0x01)])
    _poll_best_effort(entries, WV_EXT_STATUS, WI_DATAENB, 0x21, 0x20,
                      _EJECT_TIMEOUT_MS)
    _write_regs(entries, [(0x09, 0x00)])
    return entries


def emit_op_program(key: str, phase_name: str, entries: list[OpEntry],
                    injections: list[tuple[str, int, int]],
                    bulk_injections: list[tuple[str, int, int]],
                    c: list[str]) -> tuple[str, str, int, str, int]:
    """Emit one OpProgram's backing arrays (a byte blob for every op's
    `data`, the Op array, and -- if any -- the OpInjection and
    OpBulkInjection arrays) and return (ops array identifier, injections
    array identifier or "nullptr", injection count, bulk injections array
    identifier or "nullptr", bulk injection count)."""
    base = c_ident(key.upper(), phase_name.upper())
    blob = bytearray()
    offsets: list[int] = []
    for e in entries:
        offsets.append(len(blob))
        blob.extend(e.data)

    data_name = f"{base}_OPS_DATA"
    if blob:
        c.append(f"static const std::uint8_t {data_name}[{len(blob)}] = {{")
        c.append(fmt_bytes(bytes(blob)))
        c.append("};\n")

    ops_name = f"{base}_OPS"
    c.append(f"/* {key} / {phase_name}: op program, {len(entries)} ops "
             f"(docs/sane-hook2-offset.md section 6, "
             f"docs/sane-hook3-gain.md section 6, "
             f"docs/sane-hook4-shading.md section 6). */")
    c.append(f"static const Op {ops_name}[{len(entries)}] = {{")
    for e, off in zip(entries, offsets):
        data_expr = f"{data_name} + {off}" if e.data else "nullptr"
        c.append(f"    {{OpKind::{e.kind}, 0x{e.request:02x}, "
                 f"0x{e.value:04x}, 0x{e.index:04x}, {data_expr}, "
                 f"{e.length}, {e.dur_ms}, 0x{e.mask:02x}, 0x{e.want:02x}, "
                 f"{e.timeout_ms}}},")
    c.append("};\n")

    if injections:
        inj_name = f"{base}_OPS_INJ"
        c.append(f"/* Computed values patched into {ops_name} at run time "
                 f"(docs/sane-hook3-gain.md section 6). */")
        c.append(f"static const OpInjection {inj_name}[{len(injections)}] = {{")
        for name, op_idx, byte_off in injections:
            c.append(f'    {{"{name}", {op_idx}, {byte_off}}},')
        c.append("};\n")
    else:
        inj_name = "nullptr"

    if bulk_injections:
        bulk_inj_name = f"{base}_OPS_BULK_INJ"
        c.append(f"/* Bulk payloads patched into {ops_name} at run time "
                 f"(docs/sane-hook4-shading.md section 6). */")
        c.append(f"static const OpBulkInjection {bulk_inj_name}"
                 f"[{len(bulk_injections)}] = {{")
        for name, first_op, last_op in bulk_injections:
            c.append(f'    {{"{name}", {first_op}, {last_op}}},')
        c.append("};\n")
    else:
        bulk_inj_name = "nullptr"

    return ops_name, inj_name, len(injections), bulk_inj_name, len(bulk_injections)


def c_ident(*parts: str) -> str:
    return "_".join(p.replace("-", "_") for p in parts)


def fmt_pairs(pairs: list[tuple[int, int]], indent: str = "    ") -> str:
    """Four pairs per line, hex, so a diff against a capture stays readable."""
    out, line = [], []
    for reg, val in pairs:
        line.append(f"{{0x{reg:02x}, 0x{val:02x}}}")
        if len(line) == 4:
            out.append(indent + ", ".join(line) + ",")
            line = []
    if line:
        out.append(indent + ", ".join(line) + ",")
    return "\n".join(out)


def fmt_bytes(data: bytes, indent: str = "    ") -> str:
    out, line = [], []
    for b in data:
        line.append(f"0x{b:02x}")
        if len(line) == 12:
            out.append(indent + ", ".join(line) + ",")
            line = []
    if line:
        out.append(indent + ", ".join(line) + ",")
    return "\n".join(out)


def frame_geom_entries(key: str, mod, dpi: int) -> list[dict]:
    """The A+C production geometry for every frame 1-6 of one profile,
    computed by the SAME authoritative Python functions the CLI driver
    programs from (of135i/holder.py, of135i/device.py) -- NOT re-derived
    here. This is the single source bridge: Python computes, the generator
    freezes, the C++ (feedl_for_frame / frame_geometry) consumes; a table
    change that is not regenerated is caught by ``gen_sane_tables --check``.

    Six discrete values per frame, matching docs/holder-position-design.md:

      * ``feedl``          -- the commanded POSITION target (plain: window
                              centre; dual: Test-61 fixed-K re-anchor).
      * ``line_register``  -- the line count PROGRAMMED into the 24-bit scan
                              register: plain = scan_lines_for_chunks(chunks)
                              (the 8-line drain is part of this value); dual
                              = the interleaved wire count (chunks *
                              LINES_PER_CHUNK), which carries no separate
                              drain. This is what begin_scan injects.
      * ``read_lines``     -- image lines actually read off the wire
                              (chunks * image-lines-per-chunk); the pipeline
                              byte budget and chunk driver size from THIS,
                              not from line_register (they differ by the
                              drain on the plain path).
      * ``delivered_lines``-- lines the frontend receives (after the colour
                              crop / parity split): geom.delivered_lines.
      * ``chunks``         -- image chunks to read.
      * ``end_hwdpi``      -- the furthest motor position the pass reaches,
                              already range-checked against FEEDL_CEILING by
                              overscan_geometry() before return; the C++
                              re-checks this exact value before any write so
                              the transport bound is inherited verbatim.

    Proven invariant (tests/test_overscan.py + the geometry parity matrix):
    ``delivered_lines + 2*align_shift(dpi) == read_lines`` on the plain
    path and ``== read_lines/2`` on a dual path -- the relationship
    calculate_scan_session's own consistency assertion depends on.
    """
    crop = _image.align_shift(dpi)
    is_dual = hasattr(mod, "LINES_PER_CHUNK")
    out: list[dict] = []
    for frame in range(1, 7):
        if is_dual:
            geom, wire = holder.dual_overscan_geometry(
                frame, dpi=dpi, lines_per_chunk=mod.LINES_PER_CHUNK,
                colour_crop_lines=crop, default_wire_lines=mod.DEFAULT_LINES,
                overscan_mm=holder.OVERSCAN_MM)
            line_register = wire
            read_lines = geom.chunks * mod.LINES_PER_CHUNK
        else:
            geom = holder.overscan_geometry(
                frame, res_units_per_line=7200 // dpi,
                chunk_lines=mod.IMAGE_CHUNK_LINES, colour_crop_lines=crop)
            line_register = tables.scan_lines_for_chunks(geom.chunks)
            read_lines = geom.chunks * mod.IMAGE_CHUNK_LINES
        out.append(dict(
            frame=frame, feedl=geom.feedl, line_register=line_register,
            read_lines=read_lines, delivered_lines=geom.delivered_lines,
            chunks=geom.chunks, end_hwdpi=round(geom.end_hwdpi)))
    return out


def emit() -> tuple[str, str]:
    """Return (header, source) for the generated tables."""
    h: list[str] = []
    c: list[str] = []

    banner = (
        "/* GENERATED by tools/gen_sane_tables.py from of135i/tables*.py --\n"
        " * do not edit. Regenerate after any table change.\n"
        " *\n"
        " * Register values captured from the vendor driver and verified\n"
        " * byte-exact against USB traces (docs/protocol-notes.md); these are\n"
        " * interoperability facts, not vendor code. Reads and polls are not\n"
        " * reproduced here: the backend polls explicitly with timeouts\n"
        " * (docs/sane-port.md, decision 3).\n"
        " */\n")

    h.append(banner)
    h.append("#ifndef BACKEND_GENESYS_GL126_TABLES_H")
    h.append("#define BACKEND_GENESYS_GL126_TABLES_H\n")
    h.append("#include <cstddef>")
    h.append("#include <cstdint>\n")
    h.append("namespace genesys {")
    h.append("namespace gl126 {\n")
    h.append("/** One register write: the chip takes [reg][val] byte pairs. */")
    h.append("struct RegPair {")
    h.append("    std::uint8_t reg;")
    h.append("    std::uint8_t val;")
    h.append("};\n")
    h.append("/** A value the hook must compute and patch in before writing.")
    h.append(" *  `index` addresses the phase's pair array; the captured value")
    h.append(" *  standing there belongs to the reference unit and must not be")
    h.append(" *  written as-is. */")
    h.append("struct RegInjection {")
    h.append("    const char* name;")
    h.append("    std::size_t index;")
    h.append("};\n")
    h.append("/** A buffer transfer: descriptor address plus payload length. */")
    h.append("struct BufWrite {")
    h.append("    std::uint32_t addr;")
    h.append("    std::uint32_t length;")
    h.append("};\n")
    h.append("/** One phase of the captured sequence. */")
    h.append("struct Phase {")
    h.append("    const char* name;")
    h.append("    const RegPair* regs;")
    h.append("    std::size_t reg_count;")
    h.append("    const RegInjection* injections;")
    h.append("    std::size_t injection_count;")
    h.append("    const BufWrite* buffers;")
    h.append("    std::size_t buffer_count;")
    h.append("};\n")
    h.append("/** An op-program transfer kind (docs/sane-hook2-offset.md")
    h.append(" *  section 6, docs/sane-hook4-shading.md section 6);")
    h.append(" *  gl126_ops.cpp is the runner that executes these. */")
    h.append("enum class OpKind : std::uint8_t {")
    h.append("    Write,          /* control write: register batch, 0x82 buffer")
    h.append("                       descriptor, or 0x8c write */")
    h.append("    AckRead,        /* control read, 1 B, must be 0x55 */")
    h.append("    Read,           /* control read, logged only (provenance) */")
    h.append("    PollDataReady,  /* poll reg 0x101 until bit 0x01 (DATAENB) sets */")
    h.append("    PollClass,      /* poll reg 0x100 until (reply[0] & 0xf0) matches")
    h.append("                       the captured settled value's upper nibble */")
    h.append("    BulkIn,         /* bulk IN of `len` bytes from EP 0x81 */")
    h.append("    BulkOut,        /* bulk OUT of `len` bytes to EP 0x02 */")
    h.append("    BulkDone,       /* control read after a bulk transfer, logged only */")
    h.append("    PollMasked,     /* poll until (reply[0] & mask) == want (docs/sane-")
    h.append("                       hook5-frame.md section 4): POSITION's W3 (class")
    h.append("                       F), PARK's Wait A (reg 0x35 bit 0x40) and Wait B")
    h.append("                       (the PARK_COMPLETE status word) */")
    h.append("    ReadModifyWrite,/* read register (index>>8) via 0x008e/index, write")
    h.append("                       back (v & mask) | want as a 2-byte register batch,")
    h.append("                       no ack read (docs/sane-hook5-frame.md section 4:")
    h.append("                       PARK's three RMW registers, 4 sites) */")
    h.append("    Sleep,          /* no transfer: wait dur_ms (docs/sane-wp4-magazine.md")
    h.append("                       section 3) -- the Python replayer's pacing, which the")
    h.append("                       magazine flow was hardware-verified WITH */")
    h.append("    PollBestEffort, /* poll until (reply[0] & mask) == want, but a timeout")
    h.append("                       LOGS and continues instead of failing closed -- the")
    h.append("                       driver's own non-raising polls (cold start, eject")
    h.append("                       completion, the load flow's state reads) */")
    h.append("};\n")
    h.append("/** One op-program transfer. `data` is the write payload (Write, and a")
    h.append(" *  BulkOut NOT covered by a bulk injection) or the captured reply")
    h.append(" *  (AckRead/Read/PollDataReady/PollClass/BulkDone, provenance only --")
    h.append(" *  the runner does not require a live reply to match it, except")
    h.append(" *  AckRead's fixed 0x55, PollDataReady's bit 0x01 and PollClass's")
    h.append(" *  upper nibble). `data` is nullptr for BulkIn, and for a BulkOut a")
    h.append(" *  bulk injection covers -- its captured chunk is the reference")
    h.append(" *  unit's own calibration data and must not be kept; `len` still")
    h.append(" *  gives the wire length. */")
    h.append("struct Op {")
    h.append("    OpKind kind;")
    h.append("    std::uint8_t request;    /* bRequest; 0 for BulkIn/BulkOut */")
    h.append("    std::uint16_t value;     /* wValue */")
    h.append("    std::uint16_t index;     /* wIndex */")
    h.append("    const std::uint8_t* data;")
    h.append("    std::uint16_t len;       /* Write/reads: byte length; BulkIn/BulkOut: bulk length */")
    h.append("    std::uint16_t dur_ms;    /* captured poll duration, ms (0 otherwise) */")
    h.append("    std::uint8_t mask;       /* PollMasked: poll mask; ReadModifyWrite: and_mask;")
    h.append("                                0 for every other kind (docs/sane-hook5-frame.md")
    h.append("                                section 4) */")
    h.append("    std::uint8_t want;       /* PollMasked/PollBestEffort: target value;")
    h.append("                                ReadModifyWrite: or_mask; 0 for every other kind.")
    h.append("                                ReadModifyWrite's target register is (index >> 8),")
    h.append("                                the same encoding as its own read setup")
    h.append("                                (index = (reg << 8) | 0x22) */")
    h.append("    std::uint32_t timeout_ms;/* PollMasked/PollBestEffort: this site's OWN budget,")
    h.append("                                mirroring what the Python driver allows it")
    h.append("                                (device.py _poll_one: max(3x captured, 1 s);")
    h.append("                                cold start: 15 s / 30 s). 0 = use the RunPolicy")
    h.append("                                value, which is what every pre-WP-4 program has. */")
    h.append("};\n")
    h.append("/** A value the op-program runner must compute and patch into a")
    h.append(" *  Write op's payload before sending it (docs/sane-hook3-gain.md")
    h.append(" *  section 6/Part B) -- gl126_ops.cpp's run_program() takes a")
    h.append(" *  name -> byte map and refuses (OpsFailure::MissingInjection,")
    h.append(" *  before any transfer) if a name here is not in it. `op_index`")
    h.append(" *  addresses the OpProgram's own `ops` array (one-to-one with the")
    h.append(" *  captured ops); `byte_offset` is the byte inside that op's")
    h.append(" *  payload -- always odd (a value byte, never a register")
    h.append(" *  number). The captured value standing there belongs to the")
    h.append(" *  reference unit and must not be written as-is. */")
    h.append("struct OpInjection {")
    h.append("    const char* name;")
    h.append("    std::size_t op_index;")
    h.append("    std::size_t byte_offset;")
    h.append("};\n")
    h.append("/** A payload the op-program runner must compute and split across a")
    h.append(" *  run of consecutive BulkOut ops before sending them (docs/sane-")
    h.append(" *  hook4-shading.md section 6) -- run_program() takes a name ->")
    h.append(" *  byte vector map and refuses (OpsFailure::MissingInjection, before")
    h.append(" *  any transfer) if a name here is not in it, or")
    h.append(" *  OpsFailure::BadInjection if the value is longer than the ops'")
    h.append(" *  combined length. `first_op`/`last_op` address the OpProgram's own")
    h.append(" *  `ops` array, INCLUSIVE, and are always a contiguous run of")
    h.append(" *  BulkOut ops. A shorter value is zero-padded to the combined")
    h.append(" *  length before slicing, exactly of135i/tables.py's Phase.patched()")
    h.append(" *  rule for a \"bo\" injection. */")
    h.append("struct OpBulkInjection {")
    h.append("    const char* name;")
    h.append("    std::size_t first_op;")
    h.append("    std::size_t last_op;")
    h.append("};\n")
    h.append("/** An ordered op program for one phase -- prep/afe_base/cal_dark_a/")
    h.append(" *  cal_dark_b (SANE hook 2), cal_white/cal_gain_check_a/")
    h.append(" *  cal_gain_check_b (SANE hook 3, docs/sane-hook3-gain.md) and")
    h.append(" *  cal_shading_measure/cal_shading_upload/cal_shading_verify/")
    h.append(" *  cal_shading_verify_upload (SANE hook 4, docs/sane-hook4-")
    h.append(" *  shading.md -- the last two are one captured phase,")
    h.append(" *  `cal_shading_verify`, split at its own `split_at`). */")
    h.append("struct OpProgram {")
    h.append("    const char* name;")
    h.append("    const Op* ops;")
    h.append("    std::size_t count;")
    h.append("    const OpInjection* injections;  /* nullptr/0 when none */")
    h.append("    std::size_t injection_count;")
    h.append("    const OpBulkInjection* bulk_injections;  /* nullptr/0 when none */")
    h.append("    std::size_t bulk_injection_count;")
    h.append("};\n")
    h.append("/** The A+C production geometry for one frame (docs/holder-position-")
    h.append(" *  design.md), frozen from of135i/holder.py by gen_sane_tables.py.")
    h.append(" *  This is the runtime positioning/window authority since the Test 58")
    h.append(" *  migration -- feedl_for_frame()/frame_geometry() read it, NOT the")
    h.append(" *  legacy feedl_frame1/feedl_pitch/captured_lines fields below (kept as")
    h.append(" *  capture ground truth / wire-structure source only). */")
    h.append("struct FrameGeom {")
    h.append("    unsigned feedl;            /* commanded POSITION target (plain: window")
    h.append("                                  centre; dual: Test-61 fixed-K re-anchor) */")
    h.append("    unsigned line_register;    /* line count programmed into the scan register")
    h.append("                                  (plain: incl the 8-line drain; dual: the")
    h.append("                                  interleaved wire count) -- begin_scan injects it */")
    h.append("    unsigned read_lines;       /* image lines actually read off the wire; the")
    h.append("                                  byte budget and chunk driver size from THIS")
    h.append("                                  (differs from line_register by the drain) */")
    h.append("    unsigned delivered_lines;  /* lines the frontend receives (after colour")
    h.append("                                  crop / parity split) */")
    h.append("    unsigned chunks;           /* image chunks to read */")
    h.append("    unsigned end_hwdpi;        /* furthest motor position the pass reaches;")
    h.append("                                  re-checked <= FEEDL_CEILING before any write */")
    h.append("};\n")
    h.append("/** One scan profile: a resolution and its phase sequence. */")
    h.append("struct Profile {")
    h.append("    const char* name;")
    h.append("    unsigned dpi;")
    h.append("    unsigned image_width;      /* px per line as READ off the wire, RGB16LE */")
    h.append("    unsigned delivered_width;  /* px per line DELIVERED to the frontend:")
    h.append("                                  == image_width for every profile but the")
    h.append("                                  anisotropic dpi2400 (3600 across / 2400 along),")
    h.append("                                  where the sensor axis is scaled to")
    h.append("                                  round(image_width * along_dpi / across_dpi) = 3504")
    h.append("                                  so the delivered pixels are square. The RAW read")
    h.append("                                  path (chunk_len, chunk_count, byte budget) is")
    h.append("                                  sized from image_width and is UNCHANGED; the")
    h.append("                                  core's ImagePipelineNodeScaleRows resamples the")
    h.append("                                  host image from image_width to this. */")
    h.append("    unsigned chunk_len;        /* bytes per image bulk-read */")
    h.append("    unsigned lines_per_chunk;")
    h.append("    unsigned shading_lines;")
    h.append("    unsigned shading_upload_len;")
    h.append("    unsigned captured_lines;   /* LEGACY capture evidence (DEFAULT_LINES, the")
    h.append("                                  frame-1 vendor trace's line count); NOT written")
    h.append("                                  to the wire at runtime since Test 58 --")
    h.append("                                  frames[].line_register drives the scan register */")
    h.append("    unsigned chunk_count;      /* image chunks the vendor read (IMAGE_CHUNK_COUNT):")
    h.append("                                  chunk_count * lines_per_chunk lines are read,")
    h.append("                                  which for ir3600 is fewer than captured_lines */")
    h.append("    unsigned feedl_frame1;     /* LEGACY capture ground truth (vendor grid),")
    h.append("                                  NOT runtime since Test 58 -- use frames[] */")
    h.append("    unsigned feedl_pitch;      /* LEGACY capture ground truth (vendor grid),")
    h.append("                                  NOT runtime since Test 58 -- use frames[] */")
    h.append("    const FrameGeom* frames;   /* A+C production geometry, frames 1-6 (index")
    h.append("                                  frame-1); the runtime positioning/window authority */")
    h.append("    const std::uint8_t* slope_position;")
    h.append("    std::size_t slope_position_len;")
    h.append("    const std::uint8_t* slope_scan;")
    h.append("    std::size_t slope_scan_len;")
    h.append("    const Phase* phases;")
    h.append("    std::size_t phase_count;")
    h.append("    const OpProgram* programs;  /* prep/afe_base/cal_dark_a/cal_dark_b/")
    h.append("                                   cal_white/cal_gain_check_a/cal_gain_check_b/")
    h.append("                                   cal_shading_measure/cal_shading_upload/")
    h.append("                                   cal_shading_verify/cal_shading_verify_upload */")
    h.append("    std::size_t program_count;")
    h.append("};\n")

    c.append(banner)
    c.append(f'#include "{STEM}.h"\n')
    c.append("namespace genesys {")
    c.append("namespace gl126 {\n")

    # ---- flat register tables from tables_base -------------------------
    for name, pairs, doc in [
        ("BASE_INIT", tables_base.BASE_INIT_PAIRS,
         "Power-on base register table, written once per session."),
        ("AFE_BASE", tables_base.AFE_BASE_PAIRS,
         "AFE bring-up values that follow the base table."),
        ("COLD_INIT", tables_base.COLD_INIT_PAIRS,
         "Cold-start table (reg 0x01 lacks the ready bit 0x20)."),
        ("LOADER_SPEED", tables_base.LOADER_SPEED_PAIRS,
         "Loader motor speed registers used by the magazine phases."),
    ]:
        h.append(f"/** {doc} */")
        h.append(f"extern const RegPair {name}[{len(pairs)}];")
        h.append(f"constexpr std::size_t {name}_COUNT = {len(pairs)};\n")
        c.append(f"/* {doc} */")
        c.append(f"const RegPair {name}[{len(pairs)}] = {{")
        c.append(fmt_pairs(list(pairs)))
        c.append("};\n")

    # ---- slope tables, deduplicated ------------------------------------
    # The same 512 B payload is written to several addresses and shared
    # between profiles; emitting it once keeps the object small and makes
    # an accidental divergence visible as a new array.
    slopes: dict[bytes, str] = {}

    def slope_name(payload: bytes, suggested: str) -> str:
        if payload in slopes:
            return slopes[payload]
        ident = f"SLOPE_{suggested.upper()}"
        n = 2
        while ident in slopes.values():
            ident = f"SLOPE_{suggested.upper()}_{n}"
            n += 1
        slopes[payload] = ident
        h.append(f"extern const std::uint8_t {ident}[{len(payload)}];")
        h.append(f"constexpr std::size_t {ident}_LEN = {len(payload)};\n")
        c.append(f"const std::uint8_t {ident}[{len(payload)}] = {{")
        c.append(fmt_bytes(payload))
        c.append("};\n")
        return ident

    slope_name(tables_base.SLOPE_TABLE_LOADER, "loader")

    # ---- profiles -------------------------------------------------------
    profile_entries: list[str] = []
    for key, mod, dpi, doc in PROFILES:
        pos = slope_name(mod.SLOPE_TABLE_POSITION, f"{key}_position")
        scan = slope_name(mod.SLOPE_TABLE_SCAN, f"{key}_scan")

        # ---- A+C per-frame production geometry (the runtime source) ----
        frames_name = f"{key.upper()}_FRAMES"
        c.append(f"/* {key}: A+C production geometry, frames 1-6 (docs/holder-"
                 f"position-design.md; from of135i/holder.py via "
                 f"gen_sane_tables.frame_geom_entries -- Python is authoritative, "
                 f"do not hand-edit). */")
        c.append(f"static const FrameGeom {frames_name}[6] = {{")
        for fe in frame_geom_entries(key, mod, dpi):
            c.append(f"    {{{fe['feedl']}, {fe['line_register']}, "
                     f"{fe['read_lines']}, {fe['delivered_lines']}, "
                     f"{fe['chunks']}, {fe['end_hwdpi']}}},"
                     f"   /* frame {fe['frame']} */")
        c.append("};\n")

        phase_entries: list[str] = []
        for phase in mod.PHASES:
            pt = decode_phase(phase)
            base = c_ident(key.upper(), pt.name.upper())

            if pt.pairs:
                c.append(f"/* {key} / {pt.name}: {len(pt.pairs)} register writes "
                         f"from {pt.op_count} captured ops "
                         f"({pt.read_count} reads not reproduced). */")
                c.append(f"static const RegPair {base}_REGS[{len(pt.pairs)}] = {{")
                c.append(fmt_pairs(pt.pairs))
                c.append("};\n")
                regs_ref = f"{base}_REGS"
            else:
                regs_ref = "nullptr"

            if pt.injections:
                c.append(f"/* Computed values patched into {base}_REGS. */")
                c.append(f"static const RegInjection {base}_INJ"
                         f"[{len(pt.injections)}] = {{")
                for name, idx in sorted(pt.injections.items(), key=lambda kv: kv[1]):
                    reg, val = pt.pairs[idx]
                    c.append(f'    {{"{name}", {idx}}},'
                             f'   /* reg 0x{reg:02x}, captured 0x{val:02x} */')
                c.append("};\n")
                inj_ref = f"{base}_INJ"
            else:
                inj_ref = "nullptr"

            if pt.buffers:
                c.append(f"/* Buffer transfers in {key} / {pt.name}. */")
                c.append(f"static const BufWrite {base}_BUFS[{len(pt.buffers)}] = {{")
                for b in pt.buffers:
                    note = ""
                    if b.payload and b.payload in slopes:
                        note = f"   /* {slopes[b.payload]} */"
                    elif not b.payload:
                        note = "   /* payload computed at run time */"
                    c.append(f"    {{0x{b.addr:08x}, {b.length}}},{note}")
                c.append("};\n")
                bufs_ref = f"{base}_BUFS"
            else:
                bufs_ref = "nullptr"

            phase_entries.append(
                f'    {{"{pt.name}", {regs_ref}, {len(pt.pairs)}, '
                f'{inj_ref}, {len(pt.injections)}, '
                f'{bufs_ref}, {len(pt.buffers)}}},')

        c.append(f"static const Phase {key.upper()}_PHASES"
                 f"[{len(phase_entries)}] = {{")
        c.extend(phase_entries)
        c.append("};\n")

        # ---- op programs: hook 2's prep/afe_base/cal_dark_a/cal_dark_b
        # (docs/sane-hook2-offset.md section 6), hook 3's cal_white/
        # cal_gain_check_a/cal_gain_check_b (docs/sane-hook3-gain.md
        # section 6) and hook 4's cal_shading_measure/cal_shading_upload/
        # cal_shading_verify/cal_shading_verify_upload (docs/sane-hook4-
        # shading.md section 6; the last two come from splitting the one
        # captured cal_shading_verify phase at its own split_at).
        program_entries: list[str] = []
        for phase in mod.PHASES:
            if phase.name in OP_PROGRAM_PHASES:
                entries = decode_ops(phase)
                validate_op_program(phase.name, entries)
                injections = op_injections_for(phase, entries)
                bulk_injections = op_bulk_injections_for(phase, entries)
                strip_bulk_injected_data(entries, bulk_injections)
                ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                    key, phase.name, entries, injections, bulk_injections, c)
                program_entries.append(
                    f'    {{"{phase.name}", {ops_name}, {len(entries)}, '
                    f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')
            elif phase.name == _SPLIT_PHASE:
                if phase.split_at is None:
                    raise ValueError(
                        f"{phase.name}: split phase has no split_at")
                all_entries = decode_ops(phase)
                halves = (
                    (all_entries[:phase.split_at], 0),
                    (all_entries[phase.split_at:], phase.split_at),
                )
                for prog_name, (entries, base_idx) in zip(_SPLIT_PROGRAM_NAMES, halves):
                    validate_op_program(prog_name, entries)
                    injections = op_injections_for(phase, entries, base_idx)
                    bulk_injections = op_bulk_injections_for(phase, entries, base_idx)
                    strip_bulk_injected_data(entries, bulk_injections)
                    ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                        key, prog_name, entries, injections, bulk_injections, c)
                    program_entries.append(
                        f'    {{"{prog_name}", {ops_name}, {len(entries)}, '
                        f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')
            elif phase.name == "position":
                # SANE hooks 5-7 (docs/sane-hook5-frame.md section 2/4):
                # the whole captured POSITION phase, one-to-one, with the
                # FEEDL injection and its completion poll reclassified to
                # PollMasked (class F) by decode_ops() above.
                entries = decode_ops(phase)
                validate_op_program("position", entries)
                injections = op_injections_for(phase, entries)
                bulk_injections = op_bulk_injections_for(phase, entries)
                strip_bulk_injected_data(entries, bulk_injections)
                ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                    key, "position", entries, injections, bulk_injections, c)
                program_entries.append(
                    f'    {{"position", {ops_name}, {len(entries)}, '
                    f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')
            elif phase.name == "scan":
                # "scan_setup" (docs/sane-hook5-frame.md section 2/4, S1):
                # everything up to (not including) the first image-data
                # buffer descriptor -- located by matching this profile's
                # own IMAGE_DESC_DATA, not a hardcoded op index (it varies
                # per profile: 321 for plain3600/ir3600/dpi2400/dpi7200,
                # 331 for dpi600, 325 for dpi1200). The image chunks
                # themselves (S2) are NOT an OpProgram -- see
                # gl126_ops.cpp's read_image_chunk(), driven at run time
                # from Profile's own chunk_len/lines_per_chunk fields.
                desc = getattr(mod, "IMAGE_DESC_DATA", None)
                first_desc = None
                for i, op in enumerate(phase.ops):
                    if (op.kind == "cw" and op.wv == WV_BUF_DESC
                            and desc is not None and op.data == desc):
                        first_desc = i
                        break
                if first_desc is None:
                    raise ValueError(
                        f"{key}: could not locate the first image-data buffer "
                        f"descriptor in the 'scan' phase (IMAGE_DESC_DATA)")
                head_phase = dc_replace(phase, name="scan_setup",
                                        ops=phase.ops[:first_desc])
                head_entries = decode_ops(head_phase)
                validate_op_program("scan_setup", head_entries)
                injections = op_injections_for(phase, head_entries)
                bulk_injections = op_bulk_injections_for(phase, head_entries)
                strip_bulk_injected_data(head_entries, bulk_injections)
                ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                    key, "scan_setup", head_entries, injections, bulk_injections, c)
                program_entries.append(
                    f'    {{"scan_setup", {ops_name}, {len(head_entries)}, '
                    f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')
            elif phase.name == "park":
                # The semantic PARK program (docs/sane-hook5-frame.md
                # section 2/4, decision 3), built from this profile's own
                # captured constants -- see build_park_program(). No byte
                # or bulk injections: the two 0x8b payloads and the
                # optional 0x19 write are baked into the ops directly.
                entries = build_park_program(phase)
                validate_op_program("park", entries)
                ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
                    key, "park", entries, [], [], c)
                program_entries.append(
                    f'    {{"park", {ops_name}, {len(entries)}, '
                    f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')

        progs_name = f"{key.upper()}_PROGRAMS"
        c.append(f"static const OpProgram {progs_name}[{len(program_entries)}] = {{")
        c.extend(program_entries)
        c.append("};\n")

        # Delivered width: data-driven from the profile's per-axis sampling
        # (image.sampling_resolution). Only dpi2400 is anisotropic (3600
        # across, 2400 along); scaling the across axis to the along dpi makes
        # the delivered pixels square. Every isotropic profile keeps its raw
        # width. Consistency: the ratio must divide the width cleanly here
        # (5256 * 2400 / 3600 == 3504, exact), or the generator refuses.
        image_width = getattr(mod, "IMAGE_WIDTH", 0)
        across_dpi, along_dpi = _image.sampling_resolution(dpi)
        delivered_num = image_width * along_dpi
        if delivered_num % across_dpi != 0:
            raise SystemExit(
                f"{key}: delivered width {image_width}*{along_dpi}/{across_dpi} is "
                f"not integral; refuse to emit a lossy scale ratio")
        delivered_width = delivered_num // across_dpi
        profile_entries.append(
            f'    {{"{key}", {dpi}, {image_width}, {delivered_width}, '
            f'{getattr(mod, "IMAGE_CHUNK_LEN", 0)}, '
            f'{getattr(mod, "LINES_PER_CHUNK", 0)}, '
            f'{getattr(mod, "SHADING_LINES", 0)}, '
            f'{getattr(mod, "SHADING_UPLOAD_LEN", 0)}, '
            f'{mod.DEFAULT_LINES}, {mod.IMAGE_CHUNK_COUNT}, '
            f'{mod.FEEDL_FRAME1}, {mod.FEEDL_PITCH}, '
            f'{frames_name}, '
            f'{pos}, {pos}_LEN, {scan}, {scan}_LEN, '
            f'{key.upper()}_PHASES, {len(phase_entries)}, '
            f'{progs_name}, {len(program_entries)}}},   /* {doc} */')

    # ---- magazine phases (no dpi) ---------------------------------------
    load_entries: list[str] = []
    for phase in tables_load.PHASES:
        pt = decode_phase(phase)
        base = c_ident("LOAD", pt.name.upper())
        if pt.pairs:
            c.append(f"/* magazine / {pt.name}: {len(pt.pairs)} register writes "
                     f"from {pt.op_count} captured ops. */")
            c.append(f"static const RegPair {base}_REGS[{len(pt.pairs)}] = {{")
            c.append(fmt_pairs(pt.pairs))
            c.append("};\n")
            regs_ref = f"{base}_REGS"
        else:
            regs_ref = "nullptr"
        bufs_ref = "nullptr"
        if pt.buffers:
            c.append(f"static const BufWrite {base}_BUFS[{len(pt.buffers)}] = {{")
            for b in pt.buffers:
                note = f"   /* {slopes[b.payload]} */" if b.payload in slopes else ""
                c.append(f"    {{0x{b.addr:08x}, {b.length}}},{note}")
            c.append("};\n")
            bufs_ref = f"{base}_BUFS"
        load_entries.append(
            f'    {{"{pt.name}", {regs_ref}, {len(pt.pairs)}, '
            f'nullptr, 0, {bufs_ref}, {len(pt.buffers)}}},')

    h.append("/** The magazine phases (OPEN / JOG / LOAD), in order. */")
    h.append(f"extern const Phase MAGAZINE_PHASES[{len(load_entries)}];")
    h.append(f"constexpr std::size_t MAGAZINE_PHASE_COUNT = {len(load_entries)};\n")
    c.append(f"const Phase MAGAZINE_PHASES[{len(load_entries)}] = {{")
    c.extend(load_entries)
    c.append("};\n")

    # ---- magazine op programs (WP-4, docs/sane-wp4-magazine.md) --------
    # The five programs the backend's magazine hooks run. Three are the
    # captured phases decoded in "magazine" mode (replayed pacing, the
    # driver's own strict/lenient poll split); two are built from
    # of135i/device.py, which builds them itself rather than replaying a
    # phase. No dpi, so they hang off nothing in PROFILES.
    magazine_programs: list[str] = []
    _mag_sources = {
        "cold_init": build_cold_init_program,
        "eject": build_eject_program,
    }
    _mag_phases = {phase.name: phase for phase in tables_load.PHASES}
    for prog_name in _MAGAZINE_PROGRAM_NAMES:
        if prog_name in _mag_sources:
            entries = _mag_sources[prog_name]()
        else:
            entries = decode_ops(_mag_phases[prog_name], magazine=True)
        validate_op_program(prog_name, entries)
        ops_name, inj_name, inj_count, bulk_name, bulk_count = emit_op_program(
            "magazine", prog_name, entries, [], [], c)
        magazine_programs.append(
            f'    {{"{prog_name}", {ops_name}, {len(entries)}, '
            f'{inj_name}, {inj_count}, {bulk_name}, {bulk_count}}},')

    h.append("/** The magazine flow's op programs (docs/sane-wp4-magazine.md),")
    h.append(" *  in the order they run: cold_init (device.py's cold-start")
    h.append(" *  sequence), open + jog (the vendor's app start, whose jog IS")
    h.append(" *  the eject of a latched magazine), load (after the operator")
    h.append(" *  reseated it) and eject. Looked up by name through")
    h.append(" *  gl126_ops.h's magazine_program(). */")
    h.append(f"extern const OpProgram MAGAZINE_PROGRAMS[{len(magazine_programs)}];")
    h.append(f"constexpr std::size_t MAGAZINE_PROGRAM_COUNT = {len(magazine_programs)};\n")
    c.append(f"const OpProgram MAGAZINE_PROGRAMS[{len(magazine_programs)}] = {{")
    c.extend(magazine_programs)
    c.append("};\n")

    h.append("/** Every scan profile, indexed by PROFILE_COUNT. */")
    h.append(f"extern const Profile PROFILES[{len(profile_entries)}];")
    h.append(f"constexpr std::size_t PROFILE_COUNT = {len(profile_entries)};\n")
    c.append(f"const Profile PROFILES[{len(profile_entries)}] = {{")
    c.extend(profile_entries)
    c.append("};\n")

    h.append("} // namespace gl126")
    h.append("} // namespace genesys\n")
    h.append("#endif // BACKEND_GENESYS_GL126_TABLES_H")
    c.append("} // namespace gl126")
    c.append("} // namespace genesys")

    return "\n".join(h) + "\n", "\n".join(c) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="fail if the checked-in output is out of date")
    args = ap.parse_args(argv)

    header, source = emit()
    h_path = OUT_DIR / f"{STEM}.h"
    c_path = OUT_DIR / f"{STEM}.cpp"

    if args.check:
        for path, want in ((h_path, header), (c_path, source)):
            if not path.exists():
                print(f"missing generated file: {path}", file=sys.stderr)
                return 1
            if path.read_text() != want:
                print(f"{path} is out of date; run tools/gen_sane_tables.py",
                      file=sys.stderr)
                return 1
        print("generated SANE tables are up to date")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    h_path.write_text(header)
    c_path.write_text(source)
    print(f"wrote {h_path} ({len(header)} B)")
    print(f"wrote {c_path} ({len(source)} B)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
